import { FormEvent, useEffect, useState } from 'react';
import { AlertTriangle, Building2, CheckCircle2, KeyRound, ShieldCheck, UserPlus, Users } from 'lucide-react';
import { api, type BillingContext } from '../api';
import { Panel, Status } from '../ui';
import './account-settings.css';

const empty={firstName:'',lastName:'',email:'',phone:'',temporaryPassword:'',propertyIds:[] as string[]};

export default function AccountSettings(){
 const [context,setContext]=useState<BillingContext|null>(null),[team,setTeam]=useState<any[]>([]),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){setError('');try{const ctx=await api.billingContext();setContext(ctx);if(ctx.canManageTeam)setTeam(await api.team())}catch(err){setError(err instanceof Error?err.message:'Could not load account settings')}}
 useEffect(()=>{void load()},[]);
 function toggle(id:string){setForm(current=>({...current,propertyIds:current.propertyIds.includes(id)?current.propertyIds.filter(value=>value!==id):[...current.propertyIds,id]}));}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{await api.createCaretaker(form);setForm(empty);setNotice('Caretaker account created. Share the company code and temporary password securely.');await load()}catch(err){setError(err instanceof Error?err.message:'Could not create caretaker')}finally{setBusy(false)}}
 return <><div className="module-header"><div><div className="eyebrow">Settings</div><h1>Account and team</h1><p>Keep access simple and limited to the correct properties.</p></div></div>
 {notice&&<div className="settings-notice"><CheckCircle2 size={16}/>{notice}</div>}{error&&<div className="settings-error"><AlertTriangle size={16}/>{error}</div>}
 <div className="settings-summary"><article><Building2 size={18}/><div><span>Company</span><strong>{context?.organization.name||'Loading…'}</strong><small>Code: {context?.organization.slug||'—'}</small></div></article><article><ShieldCheck size={18}/><div><span>Your access</span><strong>{context?.role?.replace('_',' ')||'—'}</strong><small>{context?.properties.length||0} visible properties</small></div></article></div>
 {context?.canManageTeam?<><Panel title="Caretakers" kicker="Assigned-property access"><div className="team-list">{team.filter(member=>member.role==='caretaker').map(member=><article key={member.id}><div className="team-avatar">{member.first_name?.[0]}{member.last_name?.[0]}</div><div><strong>{member.first_name} {member.last_name}</strong><span>{member.email} · {member.phone}</span><small>{(member.assigned_properties||[]).map((p:any)=>p.name).join(', ')||'No property assigned'}</small></div><Status value={member.status}/></article>)}{!team.some(member=>member.role==='caretaker')&&<div className="settings-empty"><Users size={22}/><span>No caretakers yet.</span></div>}</div></Panel>
 <Panel title="Add caretaker" kicker="Simple, restricted account"><form className="caretaker-form" onSubmit={submit}><div className="form-grid"><label><span>First name</span><input value={form.firstName} onChange={e=>setForm(v=>({...v,firstName:e.target.value}))} required/></label><label><span>Last name</span><input value={form.lastName} onChange={e=>setForm(v=>({...v,lastName:e.target.value}))} required/></label><label><span>Email</span><input type="email" value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))} required/></label><label><span>Phone</span><input type="tel" value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))} required/></label><label className="full"><span>Temporary password</span><div className="settings-password"><KeyRound size={15}/><input type="password" minLength={12} value={form.temporaryPassword} onChange={e=>setForm(v=>({...v,temporaryPassword:e.target.value}))} required/></div><small>At least 12 characters.</small></label><fieldset className="full"><legend>Assigned properties</legend><div className="property-checks">{context.properties.map(property=><label key={property.id}><input type="checkbox" checked={form.propertyIds.includes(property.id)} onChange={()=>toggle(property.id)}/><span>{property.name}</span></label>)}</div>{!context.properties.length&&<small>Add a property before creating a caretaker.</small>}</fieldset></div><div className="modal-actions"><button className="primary-button" disabled={busy||!form.propertyIds.length||!context.properties.length}><UserPlus size={15}/>{busy?'Creating…':'Create caretaker account'}</button></div></form></Panel></>:<Panel title="Your assigned properties" kicker="Caretaker access"><div className="assigned-property-list">{context?.properties.map(property=><div key={property.id}><Building2 size={15}/><span>{property.name}</span></div>)}</div></Panel>}
 </>;
}
