import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, CheckCircle2, Droplets, FileText, Mail, MessageCircle, Phone, RefreshCw, Send, WalletCards, X } from 'lucide-react';
import { api, type BillingContext, type BillingPreview, type WaterReading, type WaterSetting } from '../api';
import { MetricCard, Panel, Status } from '../ui';
import './billing-page.css';

const money=(value:unknown)=>`KES ${Number(value||0).toLocaleString()}`;
const currentMonth=()=>`${new Date().toISOString().slice(0,7)}-01`;
function periodEnd(month:string){const [year,m]=month.split('-').map(Number);return new Date(Date.UTC(year,m,0)).toISOString().slice(0,10);}

export default function BillingPage({onAdd,refreshKey}:{onAdd:()=>void;refreshKey:number}){
 const [context,setContext]=useState<BillingContext|null>(null),[settings,setSettings]=useState<WaterSetting[]>([]),[readings,setReadings]=useState<WaterReading[]>([]),[invoices,setInvoices]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]);
 const [month,setMonth]=useState(currentMonth()),[propertyId,setPropertyId]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[preview,setPreview]=useState<BillingPreview|null>(null);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setError('');try{const ctx=await api.billingContext();setContext(ctx);const [nextSettings,nextReadings]=await Promise.all([api.waterSettings(),api.waterReadings(month,propertyId||undefined)]);setSettings(nextSettings);setReadings(nextReadings);if(ctx.canManageBilling){const [nextInvoices,nextPayments]=await Promise.all([api.invoices(),api.payments()]);setInvoices(nextInvoices);setPayments(nextPayments)}}catch(err){setError(err instanceof Error?err.message:'Could not load monthly billing')}},[month,propertyId,refreshKey]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{setPreview(null)},[month,propertyId]);
 const meterRows=readings.filter(r=>r.billing_method==='meter');
 const submitted=readings.filter(r=>r.status==='submitted');
 const approved=readings.filter(r=>r.status==='approved').length;
 const role=context?.role;
 const canManage=!!context?.canManageBilling;
 const selectedLabel=new Date(`${month}T00:00:00`).toLocaleDateString('en-KE',{month:'long',year:'numeric'});
 async function saveReading(e:FormEvent){e.preventDefault();const payload=meterRows.filter(r=>r.status!=='approved'&&values[r.unit_id]!==undefined&&values[r.unit_id]!=='').map(r=>({unitId:r.unit_id,currentReading:Number(values[r.unit_id]),notes:''}));if(!payload.length){setError('Enter at least one current meter reading');return}setBusy('readings');setError('');try{await api.submitWaterReadings(month,payload);setNotice('Water readings submitted for review.');setValues({});await load()}catch(err){setError(err instanceof Error?err.message:'Could not save readings')}finally{setBusy('')};}
 async function decide(id:string|undefined,approve:boolean){if(!id)return;setBusy(id);setError('');try{if(approve)await api.approveWaterReading(id);else{const reason=window.prompt('Why is this reading being returned?');if(!reason){setBusy('');return}await api.rejectWaterReading(id,reason)}setNotice(approve?'Reading approved.':'Reading returned to the caretaker.');await load()}catch(err){setError(err instanceof Error?err.message:'Could not update reading')}finally{setBusy('')}}
 async function saveSetting(setting:WaterSetting){setBusy(setting.property_id);setError('');try{await api.saveWaterSetting(setting.property_id,{billingMethod:setting.billing_method,ratePerUnit:Number(setting.rate_per_unit),flatAmount:Number(setting.flat_amount),sharedAmount:Number(setting.shared_amount),active:true});setNotice(`${setting.property_name} water settings saved.`);await load()}catch(err){setError(err instanceof Error?err.message:'Could not save water settings')}finally{setBusy('')}}
 function updateSetting(id:string,patch:Partial<WaterSetting>){setSettings(rows=>rows.map(row=>row.property_id===id?{...row,...patch}:row));}
 async function runPreview(){setBusy('preview');setError('');try{setPreview(await api.billingPreview(month,periodEnd(month),propertyId||undefined))}catch(err){setError(err instanceof Error?err.message:'Could not prepare invoices')}finally{setBusy('')}}
 async function createInvoices(){if(!preview?.ready)return;setBusy('post');setError('');try{const result:any=await api.postBilling(month,periodEnd(month),propertyId||undefined);setNotice(`${result.invoice_count||0} invoice${result.invoice_count===1?'':'s'} created.`);setPreview(null);await load()}catch(err){setError(err instanceof Error?err.message:'Could not create invoices')}finally{setBusy('')}}
 async function share(id:string,channel:'whatsapp'|'sms'|'email'){const popup=channel==='whatsapp'?window.open('about:blank','_blank'):null;setBusy(`share-${id}`);setError('');try{const result=await api.shareInvoice(id,channel);if(popup)popup.location.href=result.actionUrl;else window.location.href=result.actionUrl;setNotice(`Invoice opened in ${channel==='email'?'email':channel==='sms'?'messages':'WhatsApp'}.`);await load()}catch(err){popup?.close();setError(err instanceof Error?err.message:'Could not share invoice')}finally{setBusy('')}}
 const invoiceTotal=useMemo(()=>invoices.reduce((sum,row)=>sum+Number(row.total||0),0),[invoices]);
 return <><div className="module-header billing-head"><div><div className="eyebrow">Bills</div><h1>{role==='caretaker'?'Monthly water readings':'Monthly bills'}</h1><p>{role==='caretaker'?'Enter readings for your assigned properties.':'Review water, create invoices and share them with tenants.'}</p></div>{canManage&&<button className="add-button" onClick={onAdd}><WalletCards size={16}/> Record payment</button>}</div>
 <div className="billing-controls"><label><span>Billing month</span><input type="month" value={month.slice(0,7)} onChange={e=>setMonth(`${e.target.value}-01`)}/></label><label><span>Property</span><select value={propertyId} onChange={e=>setPropertyId(e.target.value)}><option value="">All assigned properties</option>{context?.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button></div>
 {notice&&<div className="billing-notice"><CheckCircle2 size={16}/><span>{notice}</span><button onClick={()=>setNotice('')}><X size={14}/></button></div>}{error&&<div className="billing-error"><AlertTriangle size={16}/>{error}</div>}
 <div className="metric-grid four"><MetricCard label="Meter units" value={String(meterRows.length)} note={selectedLabel} icon={Droplets}/><MetricCard label="Submitted" value={String(submitted.length)} note="Waiting for review" icon={Send} tone="info"/><MetricCard label="Approved" value={String(approved)} note="Ready for billing" icon={CheckCircle2} tone="success"/><MetricCard label={canManage?'Invoices':'Assigned properties'} value={String(canManage?invoices.length:context?.properties.length||0)} note={canManage?money(invoiceTotal):'Your access only'} icon={FileText}/></div>
 <Panel title={role==='caretaker'?'Enter water readings':'Water readings'} kicker={selectedLabel}><form onSubmit={saveReading}><div className="billing-reading-table"><table><thead><tr><th>Unit</th><th>Previous</th><th>Current</th><th>Usage</th><th>Amount</th><th>Status</th>{canManage&&<th>Review</th>}</tr></thead><tbody>{meterRows.map(row=>{const previous=Number(row.previous_reading??row.suggested_previous??0);const current=values[row.unit_id]!==undefined?Number(values[row.unit_id]):Number(row.current_reading??0);const projected=Math.max(0,current-previous)*Number(row.rate_per_unit||0);return <tr key={row.unit_id}><td><strong>{row.unit_number}</strong><small>{row.property_name}</small></td><td>{previous}</td><td>{row.status==='approved'?row.current_reading:<input type="number" min={previous} step="0.001" value={values[row.unit_id]??row.current_reading??''} onChange={e=>setValues(v=>({...v,[row.unit_id]:e.target.value}))} placeholder="Reading"/>}</td><td>{row.current_reading!==undefined?row.consumption:current?Math.max(0,current-previous).toFixed(3):'—'}</td><td>{row.current_reading!==undefined?money(row.amount):current?money(projected):'—'}</td><td><Status value={row.status||'not entered'}/>{row.rejection_reason&&<small className="rejection">{row.rejection_reason}</small>}</td>{canManage&&<td>{row.status==='submitted'?<div className="reading-actions"><button type="button" onClick={()=>void decide(row.id,true)} disabled={busy===row.id}><Check size={14}/> Approve</button><button type="button" className="reject" onClick={()=>void decide(row.id,false)}><X size={14}/></button></div>:'—'}</td>}</tr>})}{!meterRows.length&&<tr><td colSpan={canManage?7:6} className="billing-empty">No metered units are configured for this selection.</td></tr>}</tbody></table></div>{meterRows.some(r=>r.status!=='approved')&&<div className="billing-panel-actions"><span>Previous readings are filled automatically from the last approved month.</span><button className="primary-button" disabled={busy==='readings'}>{busy==='readings'?'Submitting…':'Submit entered readings'}</button></div>}</form></Panel>
 {canManage&&<><Panel title="Water charges" kicker="Set once per property"><div className="water-settings-grid">{settings.filter(s=>!propertyId||s.property_id===propertyId).map(setting=><article key={setting.property_id}><strong>{setting.property_name}</strong><label><span>Charging method</span><select value={setting.billing_method} onChange={e=>updateSetting(setting.property_id,{billing_method:e.target.value as WaterSetting['billing_method']})}><option value="meter">Meter reading</option><option value="flat">Flat charge per unit</option><option value="shared">Share one property bill</option></select></label>{setting.billing_method==='meter'&&<label><span>Price per water unit</span><input type="number" min="0" step="0.01" value={setting.rate_per_unit} onChange={e=>updateSetting(setting.property_id,{rate_per_unit:Number(e.target.value)})}/></label>}{setting.billing_method==='flat'&&<label><span>Charge per occupied unit</span><input type="number" min="0" step="0.01" value={setting.flat_amount} onChange={e=>updateSetting(setting.property_id,{flat_amount:Number(e.target.value)})}/></label>}{setting.billing_method==='shared'&&<label><span>Total property water bill</span><input type="number" min="0" step="0.01" value={setting.shared_amount} onChange={e=>updateSetting(setting.property_id,{shared_amount:Number(e.target.value)})}/></label>}<button onClick={()=>void saveSetting(setting)} disabled={busy===setting.property_id}>{busy===setting.property_id?'Saving…':'Save water setting'}</button></article>)}</div></Panel>
 <Panel title="Create monthly invoices" kicker="Review before creating"><div className="invoice-builder"><div><strong>{selectedLabel}</strong><span>Rent and approved water charges will appear together on each invoice.</span></div><button className="secondary-button" onClick={()=>void runPreview()} disabled={busy==='preview'}>{busy==='preview'?'Checking…':'Preview invoices'}</button>{preview&&<div className={`preview-result ${preview.ready?'ready':'blocked'}`}><div><strong>{preview.count} invoices · {money(preview.total)}</strong><span>{preview.ready?'Everything is ready.':`${preview.missingReadings} water reading${preview.missingReadings===1?' is':'s are'} missing or not approved.`}</span></div><button className="primary-button" disabled={!preview.ready||busy==='post'} onClick={()=>void createInvoices()}>{busy==='post'?'Creating…':'Create invoices'}</button></div>}</div></Panel>
 <Panel title="Tenant invoices" kicker="Share from one place"><div className="invoice-list">{invoices.map(invoice=><article key={invoice.id}><div className="invoice-main"><span>{invoice.invoice_number}</span><strong>{invoice.tenant_name}</strong><small>{invoice.property_name} · Unit {invoice.unit_number}</small></div><div className="invoice-breakdown">{(invoice.items||[]).map((item:any)=><span key={`${item.type}-${item.description}`}>{item.type==='water'?'Water':'Rent'} <b>{money(item.amount)}</b></span>)}<strong>Total {money(invoice.total)}</strong></div><div className="invoice-state"><Status value={invoice.status}/><small>Due {new Date(invoice.due_date).toLocaleDateString()}</small>{invoice.last_shared_at&&<small>Shared by {invoice.last_channel}</small>}</div><div className="share-actions"><button title="WhatsApp" onClick={()=>void share(invoice.id,'whatsapp')}><MessageCircle size={15}/></button><button title="SMS" onClick={()=>void share(invoice.id,'sms')}><Phone size={15}/></button><button title="Email" onClick={()=>void share(invoice.id,'email')}><Mail size={15}/></button></div></article>)}{!invoices.length&&<div className="billing-empty">No invoices yet. Preview the month when leases are ready.</div>}</div></Panel>
 <Panel title="Recent payments" kicker="Money received"><div className="simple-payment-list">{payments.slice(0,10).map(payment=><div key={payment.id}><span><strong>{payment.tenant_name||'Unmatched payment'}</strong><small>{payment.reference} · {String(payment.payment_method).toUpperCase()}</small></span><b>{money(payment.amount)}</b></div>)}{!payments.length&&<div className="billing-empty">No payments recorded yet.</div>}</div></Panel></>}
 </>;
}
