import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, CheckCircle2, Clock3, Droplets, FileText, Mail, MessageCircle, Phone, RefreshCw, Send, SlidersHorizontal, WalletCards, X } from 'lucide-react';
import { api, type BillingContext, type BillingPreview, type UtilityReading, type UtilitySetting, type WaterReading, type WaterSetting } from '../api';
import { MetricCard, Panel, Status } from '../ui';
import './billing-page.css';

const money=(value:unknown)=>`KES ${Number(value||0).toLocaleString()}`;
const currentMonth=()=>`${new Date().toISOString().slice(0,7)}-01`;
function periodEnd(month:string){const [year,m]=month.split('-').map(Number);return new Date(Date.UTC(year,m,0)).toISOString().slice(0,10);}
type BillingView='readings'|'charges'|'invoices'|'arrears'|'payments';

export default function BillingPage({onAdd,refreshKey}:{onAdd:()=>void;refreshKey:number}){
 const [context,setContext]=useState<BillingContext|null>(null),[settings,setSettings]=useState<WaterSetting[]>([]),[readings,setReadings]=useState<WaterReading[]>([]),[utilitySettings,setUtilitySettings]=useState<UtilitySetting[]>([]),[utilityReadings,setUtilityReadings]=useState<UtilityReading[]>([]),[invoices,setInvoices]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[arrears,setArrears]=useState<any[]>([]);
 const [month,setMonth]=useState(currentMonth()),[propertyId,setPropertyId]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[utilityValues,setUtilityValues]=useState<Record<string,string>>({}),[preview,setPreview]=useState<BillingPreview|null>(null);
 const [utilityForm,setUtilityForm]=useState({propertyId:'',utilityType:'electricity',name:'Electricity',billingMethod:'meter',amount:'0'});
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [activeView,setActiveView]=useState<BillingView>('readings');
 const load=useCallback(async()=>{setError('');try{const ctx=await api.billingContext();setContext(ctx);const [nextSettings,nextReadings,nextUtilitySettings,nextUtilityReadings]=await Promise.all([api.waterSettings(),api.waterReadings(month,propertyId||undefined),api.utilitySettings(),api.utilityReadings(month,propertyId||undefined)]);setSettings(nextSettings);setReadings(nextReadings);setUtilitySettings(nextUtilitySettings);setUtilityReadings(nextUtilityReadings);if(!utilityForm.propertyId&&ctx.properties[0])setUtilityForm(form=>({...form,propertyId:ctx.properties[0].id}));if(ctx.canManageBilling){const [nextInvoices,nextPayments,nextArrears]=await Promise.all([api.invoices(),api.payments(),api.arrears()]);setInvoices(nextInvoices);setPayments(nextPayments);setArrears(nextArrears)}}catch(err){setError(err instanceof Error?err.message:'Could not load monthly billing')}},[month,propertyId,refreshKey]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{setPreview(null)},[month,propertyId]);
 const meterRows=readings.filter(r=>r.billing_method==='meter');
 const submitted=readings.filter(r=>r.status==='submitted');
 const approved=readings.filter(r=>r.status==='approved').length;
 const role=context?.role;
 const canManage=!!context?.canManageBilling;
 const selectedLabel=new Date(`${month}T00:00:00`).toLocaleDateString('en-KE',{month:'long',year:'numeric'});
 async function saveReading(e:FormEvent){e.preventDefault();const payload=meterRows.filter(r=>r.status!=='approved'&&values[r.unit_id]!==undefined&&values[r.unit_id]!=='').map(r=>({unitId:r.unit_id,currentReading:Number(values[r.unit_id]),notes:''}));if(!payload.length){setError('Enter at least one current meter reading');return}setBusy('readings');setError('');try{await api.submitWaterReadings(month,payload);setNotice('Water readings submitted for review.');setValues({});await load()}catch(err){setError(err instanceof Error?err.message:'Could not save readings')}finally{setBusy('')};}
 async function saveUtilityReadings(e:FormEvent){e.preventDefault();const payload=utilityReadings.filter(r=>r.status!=='approved'&&utilityValues[`${r.setting_id}:${r.unit_id}`]!==undefined&&utilityValues[`${r.setting_id}:${r.unit_id}`]!=='').map(r=>({settingId:r.setting_id,unitId:r.unit_id,currentReading:Number(utilityValues[`${r.setting_id}:${r.unit_id}`]),notes:''}));if(!payload.length){setError('Enter at least one utility meter reading');return}setBusy('utility-readings');setError('');try{await api.submitUtilityReadings(month,payload);setNotice('Utility readings submitted for review.');setUtilityValues({});await load()}catch(err){setError(err instanceof Error?err.message:'Could not save utility readings')}finally{setBusy('')}}
 async function decide(id:string|undefined,approve:boolean){if(!id)return;setBusy(id);setError('');try{if(approve)await api.approveWaterReading(id);else{const reason=window.prompt('Why is this reading being returned?');if(!reason){setBusy('');return}await api.rejectWaterReading(id,reason)}setNotice(approve?'Reading approved.':'Reading returned to the caretaker.');await load()}catch(err){setError(err instanceof Error?err.message:'Could not update reading')}finally{setBusy('')}}
 async function decideUtility(id:string|undefined,approve:boolean){if(!id)return;setBusy(id);setError('');try{if(approve)await api.approveUtilityReading(id);else{const reason=window.prompt('Why is this reading being returned?');if(!reason){setBusy('');return}await api.rejectUtilityReading(id,reason)}setNotice(approve?'Reading approved.':'Reading returned to the caretaker.');await load()}catch(err){setError(err instanceof Error?err.message:'Could not update reading')}finally{setBusy('')}}
 async function saveSetting(setting:WaterSetting){setBusy(setting.property_id);setError('');try{await api.saveWaterSetting(setting.property_id,{billingMethod:setting.billing_method,ratePerUnit:Number(setting.rate_per_unit),flatAmount:Number(setting.flat_amount),sharedAmount:Number(setting.shared_amount),active:true});setNotice(`${setting.property_name} water settings saved.`);await load()}catch(err){setError(err instanceof Error?err.message:'Could not save water settings')}finally{setBusy('')}}
 function updateSetting(id:string,patch:Partial<WaterSetting>){setSettings(rows=>rows.map(row=>row.property_id===id?{...row,...patch}:row));}
 function updateUtility(id:string,patch:Partial<UtilitySetting>){setUtilitySettings(rows=>rows.map(row=>row.id===id?{...row,...patch}:row));}
 async function saveUtility(setting:UtilitySetting){setBusy(setting.id);setError('');try{await api.updateUtilitySetting(setting.id,{name:setting.name,billingMethod:setting.billing_method,ratePerUnit:Number(setting.rate_per_unit),flatAmount:Number(setting.flat_amount),sharedAmount:Number(setting.shared_amount),active:setting.active});setNotice(`${setting.name} saved.`);await load()}catch(err){setError(err instanceof Error?err.message:'Could not save utility')}finally{setBusy('')}}
 async function addUtility(e:FormEvent){e.preventDefault();setBusy('add-utility');setError('');const amount=Number(utilityForm.amount||0);try{await api.createUtilitySetting({propertyId:utilityForm.propertyId,utilityType:utilityForm.utilityType,name:utilityForm.name,billingMethod:utilityForm.billingMethod,ratePerUnit:utilityForm.billingMethod==='meter'?amount:0,flatAmount:utilityForm.billingMethod==='flat'?amount:0,sharedAmount:utilityForm.billingMethod==='shared'?amount:0,active:true});setNotice(`${utilityForm.name} added.`);setUtilityForm(form=>({...form,name:'',amount:'0'}));await load()}catch(err){setError(err instanceof Error?err.message:'Could not add utility')}finally{setBusy('')}}
 async function runPreview(){setBusy('preview');setError('');try{setPreview(await api.billingPreview(month,periodEnd(month),propertyId||undefined))}catch(err){setError(err instanceof Error?err.message:'Could not prepare invoices')}finally{setBusy('')}}
 async function createInvoices(){if(!preview?.ready)return;setBusy('post');setError('');try{const result:any=await api.postBilling(month,periodEnd(month),propertyId||undefined);setNotice(`${result.invoice_count||0} invoice${result.invoice_count===1?'':'s'} created.`);setPreview(null);await load()}catch(err){setError(err instanceof Error?err.message:'Could not create invoices')}finally{setBusy('')}}
 async function share(id:string,channel:'whatsapp'|'sms'|'email'){const popup=channel==='whatsapp'?window.open('about:blank','_blank'):null;setBusy(`share-${id}`);setError('');try{const result=await api.shareInvoice(id,channel);if(popup)popup.location.href=result.actionUrl;else window.location.href=result.actionUrl;setNotice(`Invoice opened in ${channel==='email'?'email':channel==='sms'?'messages':'WhatsApp'}.`);await load()}catch(err){popup?.close();setError(err instanceof Error?err.message:'Could not share invoice')}finally{setBusy('')}}
 const invoiceTotal=useMemo(()=>invoices.reduce((sum,row)=>sum+Number(row.total||0),0),[invoices]);
 const tabs:[BillingView,string,typeof Droplets,number?][]=[['readings','Readings',Droplets,submitted.length+utilityReadings.filter(r=>r.status==='submitted').length],['charges','Charges',SlidersHorizontal],['invoices','Invoices',FileText,invoices.length],['arrears','Arrears',Clock3,arrears.length],['payments','Payments',WalletCards]];
 return <><section className="billing-simple-head"><div><span className="panel-kicker">BILLS</span><h1>{role==='caretaker'?'Monthly readings':'Bills'}</h1><p>{role==='caretaker'?`${meterRows.length+utilityReadings.length} meter entries · ${selectedLabel}`:`${invoices.length} invoice${invoices.length===1?'':'s'} · ${money(invoiceTotal)} total`}</p></div></section>
 <div className="billing-toolbar"><div className="billing-controls"><label><span>Billing month</span><input type="month" value={month.slice(0,7)} onChange={e=>setMonth(`${e.target.value}-01`)}/></label><label><span>Property</span><select value={propertyId} onChange={e=>setPropertyId(e.target.value)}><option value="">All assigned properties</option>{context?.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button></div>{canManage&&<button className="billing-payment-button" onClick={onAdd}><WalletCards size={16}/> Record payment</button>}</div>
 {canManage&&<div className="billing-tabs" role="tablist" aria-label="Billing sections">{tabs.map(([value,label,Icon,count])=><button key={value} role="tab" aria-selected={activeView===value} className={activeView===value?'active':''} onClick={()=>setActiveView(value)}><Icon size={16}/><span>{label}</span>{count!==undefined&&count>0&&<em>{count}</em>}</button>)}</div>}
 {notice&&<div className="billing-notice"><CheckCircle2 size={16}/><span>{notice}</span><button onClick={()=>setNotice('')}><X size={14}/></button></div>}{error&&<div className="billing-error"><AlertTriangle size={16}/>{error}</div>}
 <div className="metric-grid four"><MetricCard label="Meter entries" value={String(meterRows.length+utilityReadings.length)} note={selectedLabel} icon={Droplets}/><MetricCard label="Submitted" value={String(submitted.length+utilityReadings.filter(r=>r.status==='submitted').length)} note="Waiting for review" icon={Send} tone="info"/><MetricCard label="Approved" value={String(approved+utilityReadings.filter(r=>r.status==='approved').length)} note="Ready for billing" icon={CheckCircle2} tone="success"/><MetricCard label={canManage?'Invoices':'Assigned properties'} value={String(canManage?invoices.length:context?.properties.length||0)} note={canManage?money(invoiceTotal):'Your access only'} icon={FileText}/></div>
 {activeView==='readings'&&<div className="billing-view billing-view-readings"><Panel title={role==='caretaker'?'Enter water readings':'Water readings'} kicker={selectedLabel}><form onSubmit={saveReading}><div className="billing-reading-table"><table><thead><tr><th>Unit</th><th>Previous</th><th>Current</th><th>Usage</th><th>Amount</th><th>Status</th>{canManage&&<th>Review</th>}</tr></thead><tbody>{meterRows.map(row=>{const previous=Number(row.previous_reading??row.suggested_previous??0);const current=values[row.unit_id]!==undefined?Number(values[row.unit_id]):Number(row.current_reading??0);const projected=Math.max(0,current-previous)*Number(row.rate_per_unit||0);return <tr key={row.unit_id}><td><strong>{row.unit_number}</strong><small>{row.property_name}</small></td><td>{previous}</td><td>{row.status==='approved'?row.current_reading:<input type="number" min={previous} step="0.001" value={values[row.unit_id]??row.current_reading??''} onChange={e=>setValues(v=>({...v,[row.unit_id]:e.target.value}))} placeholder="Reading"/>}</td><td>{row.current_reading!==undefined?row.consumption:current?Math.max(0,current-previous).toFixed(3):'—'}</td><td>{row.current_reading!==undefined?money(row.amount):current?money(projected):'—'}</td><td><Status value={row.status||'not entered'}/>{row.rejection_reason&&<small className="rejection">{row.rejection_reason}</small>}</td>{canManage&&<td>{row.status==='submitted'?<div className="reading-actions"><button type="button" onClick={()=>void decide(row.id,true)} disabled={busy===row.id}><Check size={14}/> Approve</button><button type="button" className="reject" onClick={()=>void decide(row.id,false)}><X size={14}/></button></div>:'—'}</td>}</tr>})}{!meterRows.length&&<tr><td colSpan={canManage?7:6} className="billing-empty">No metered units are configured for this selection.</td></tr>}</tbody></table></div>{meterRows.some(r=>r.status!=='approved')&&<div className="billing-panel-actions"><span>Previous readings are filled automatically from the last approved month.</span><button className="primary-button" disabled={busy==='readings'}>{busy==='readings'?'Submitting…':'Submit entered readings'}</button></div>}</form></Panel>
 <Panel title="Other utility meters" kicker="Electricity and custom meters"><form onSubmit={saveUtilityReadings}><div className="billing-reading-table"><table><thead><tr><th>Utility</th><th>Unit</th><th>Previous</th><th>Current</th><th>Amount</th><th>Status</th>{canManage&&<th>Review</th>}</tr></thead><tbody>{utilityReadings.map(row=>{const key=`${row.setting_id}:${row.unit_id}`,previous=Number(row.previous_reading??row.suggested_previous??0),current=utilityValues[key]!==undefined?Number(utilityValues[key]):Number(row.current_reading??0),projected=Math.max(0,current-previous)*Number(row.rate_per_unit||0);return <tr key={key}><td><strong>{row.utility_name}</strong><small>{row.property_name}</small></td><td>{row.unit_number}</td><td>{previous}</td><td>{row.status==='approved'?row.current_reading:<input type="number" min={previous} step="0.001" value={utilityValues[key]??row.current_reading??''} onChange={e=>setUtilityValues(v=>({...v,[key]:e.target.value}))} placeholder="Reading"/>}</td><td>{row.current_reading!==undefined?money(row.amount):current?money(projected):'—'}</td><td><Status value={row.status||'not entered'}/>{row.rejection_reason&&<small className="rejection">{row.rejection_reason}</small>}</td>{canManage&&<td>{row.status==='submitted'?<div className="reading-actions"><button type="button" onClick={()=>void decideUtility(row.id,true)}><Check size={14}/> Approve</button><button type="button" className="reject" onClick={()=>void decideUtility(row.id,false)}><X size={14}/></button></div>:'—'}</td>}</tr>})}{!utilityReadings.length&&<tr><td colSpan={canManage?7:6} className="billing-empty">No other metered utilities are configured.</td></tr>}</tbody></table></div>{utilityReadings.some(r=>r.status!=='approved')&&<div className="billing-panel-actions"><span>Enter only the current meter value.</span><button className="primary-button" disabled={busy==='utility-readings'}>{busy==='utility-readings'?'Submitting…':'Submit utility readings'}</button></div>}</form></Panel></div>}
 {canManage&&activeView==='charges'&&<div className="billing-view billing-view-charges"><Panel title="Water charges" kicker="Set once per property"><div className="water-settings-grid">{settings.filter(s=>!propertyId||s.property_id===propertyId).map(setting=><article key={setting.property_id}><strong>{setting.property_name}</strong><label><span>Charging method</span><select value={setting.billing_method} onChange={e=>updateSetting(setting.property_id,{billing_method:e.target.value as WaterSetting['billing_method']})}><option value="meter">Meter reading</option><option value="flat">Flat charge per unit</option><option value="shared">Share one property bill</option></select></label>{setting.billing_method==='meter'&&<label><span>Price per water unit</span><input type="number" min="0" step="0.01" value={setting.rate_per_unit} onChange={e=>updateSetting(setting.property_id,{rate_per_unit:Number(e.target.value)})}/></label>}{setting.billing_method==='flat'&&<label><span>Charge per occupied unit</span><input type="number" min="0" step="0.01" value={setting.flat_amount} onChange={e=>updateSetting(setting.property_id,{flat_amount:Number(e.target.value)})}/></label>}{setting.billing_method==='shared'&&<label><span>Total property water bill</span><input type="number" min="0" step="0.01" value={setting.shared_amount} onChange={e=>updateSetting(setting.property_id,{shared_amount:Number(e.target.value)})}/></label>}<button onClick={()=>void saveSetting(setting)} disabled={busy===setting.property_id}>{busy===setting.property_id?'Saving…':'Save water setting'}</button></article>)}</div></Panel>
 <Panel title="Other utilities" kicker="Electricity and property charges"><div className="water-settings-grid">{utilitySettings.filter(s=>!propertyId||s.property_id===propertyId).map(setting=><article key={setting.id}><strong>{setting.name}</strong><small>{setting.property_name} · {setting.utility_type.replace('_',' ')}</small><label><span>Charging method</span><select value={setting.billing_method} onChange={e=>updateUtility(setting.id,{billing_method:e.target.value as UtilitySetting['billing_method']})}><option value="meter">Meter reading</option><option value="flat">Flat charge per unit</option><option value="shared">Share one property bill</option></select></label><label><span>{setting.billing_method==='meter'?'Price per unit':setting.billing_method==='flat'?'Charge per occupied unit':'Total property charge'}</span><input type="number" min="0" step="0.01" value={setting.billing_method==='meter'?setting.rate_per_unit:setting.billing_method==='flat'?setting.flat_amount:setting.shared_amount} onChange={e=>updateUtility(setting.id,setting.billing_method==='meter'?{rate_per_unit:Number(e.target.value)}:setting.billing_method==='flat'?{flat_amount:Number(e.target.value)}:{shared_amount:Number(e.target.value)})}/></label><button onClick={()=>void saveUtility(setting)} disabled={busy===setting.id}>{busy===setting.id?'Saving…':'Save utility'}</button></article>)}</div><form className="utility-add-form" onSubmit={addUtility}><strong>Add utility</strong><select value={utilityForm.propertyId} onChange={e=>setUtilityForm(v=>({...v,propertyId:e.target.value}))} required><option value="">Choose property</option>{context?.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={utilityForm.utilityType} onChange={e=>setUtilityForm(v=>({...v,utilityType:e.target.value,name:e.target.options[e.target.selectedIndex].text}))}><option value="electricity">Electricity</option><option value="garbage">Garbage</option><option value="security">Security</option><option value="service_charge">Service charge</option><option value="other">Other</option></select><input value={utilityForm.name} onChange={e=>setUtilityForm(v=>({...v,name:e.target.value}))} placeholder="Charge name" required/><select value={utilityForm.billingMethod} onChange={e=>setUtilityForm(v=>({...v,billingMethod:e.target.value}))}><option value="meter">Meter</option><option value="flat">Flat per unit</option><option value="shared">Shared bill</option></select><input type="number" min="0" step="0.01" value={utilityForm.amount} onChange={e=>setUtilityForm(v=>({...v,amount:e.target.value}))} placeholder="Rate or amount" required/><button className="primary-button" disabled={busy==='add-utility'}>{busy==='add-utility'?'Adding…':'Add utility'}</button></form></Panel></div>}
 {canManage&&activeView==='invoices'&&<div className="billing-view billing-view-invoices"><Panel title="Create monthly invoices" kicker="Review before creating"><div className="invoice-builder"><div><strong>{selectedLabel}</strong><span>Rent, water and other approved utility charges will appear together.</span></div><button className="secondary-button" onClick={()=>void runPreview()} disabled={busy==='preview'}>{busy==='preview'?'Checking…':'Preview invoices'}</button>{preview&&<div className={`preview-result ${preview.ready?'ready':'blocked'}`}><div><strong>{preview.count} invoices · {money(preview.total)}</strong><span>{preview.ready?'Everything is ready.':`${preview.missingReadings} unit${preview.missingReadings===1?' has':'s have'} missing or unapproved meter readings.`}</span></div><button className="primary-button" disabled={!preview.ready||busy==='post'} onClick={()=>void createInvoices()}>{busy==='post'?'Creating…':'Create invoices'}</button></div>}</div></Panel>
 <Panel title="Tenant invoices" kicker="Share from one place"><div className="invoice-list">{invoices.map(invoice=><article key={invoice.id}><div className="invoice-main"><span>{invoice.invoice_number}</span><strong>{invoice.tenant_name}</strong><small>{invoice.property_name} · Unit {invoice.unit_number}</small></div><div className="invoice-breakdown">{(invoice.items||[]).map((item:any)=><span key={`${item.type}-${item.description}`}>{item.description||item.type} <b>{money(item.amount)}</b></span>)}<strong>Total {money(invoice.total)}</strong></div><div className="invoice-state"><Status value={invoice.status}/><small>Due {new Date(invoice.due_date).toLocaleDateString()}</small>{invoice.last_shared_at&&<small>Shared by {invoice.last_channel}</small>}</div><div className="share-actions"><button title="WhatsApp" onClick={()=>void share(invoice.id,'whatsapp')}><MessageCircle size={15}/></button><button title="SMS" onClick={()=>void share(invoice.id,'sms')}><Phone size={15}/></button><button title="Email" onClick={()=>void share(invoice.id,'email')}><Mail size={15}/></button></div></article>)}{!invoices.length&&<div className="billing-empty">No invoices yet. Preview the month when leases are ready.</div>}</div></Panel></div>}
 {canManage&&activeView==='arrears'&&<Panel title="People owing" kicker="Arrears"><div className="arrears-summary"><span><strong>{money(arrears.reduce((sum,row)=>sum+Number(row.balance||0),0))}</strong><small>Total outstanding</small></span><span><strong>{arrears.filter(row=>Number(row.age_days)<=30).length}</strong><small>Due / 1–30 days</small></span><span><strong>{arrears.filter(row=>Number(row.age_days)>30&&Number(row.age_days)<=60).length}</strong><small>31–60 days</small></span><span><strong>{arrears.filter(row=>Number(row.age_days)>60).length}</strong><small>Over 60 days</small></span></div><div className="arrears-list">{arrears.map(row=><article key={row.id}><div><strong>{row.tenant_name}</strong><small>{row.property_name} · Unit {row.unit_number}</small></div><span><b>{money(row.balance)}</b><small>{Math.max(0,Number(row.age_days))} days overdue</small></span><div className="share-actions"><button title="WhatsApp reminder" onClick={()=>void share(row.id,'whatsapp')}><MessageCircle size={15}/></button><button title="SMS reminder" onClick={()=>void share(row.id,'sms')}><Phone size={15}/></button><button title="Email reminder" onClick={()=>void share(row.id,'email')}><Mail size={15}/></button></div></article>)}{!arrears.length&&<div className="billing-empty">No overdue balances.</div>}</div></Panel>}
 {canManage&&activeView==='payments'&&<Panel title="Recent payments" kicker="Money received"><div className="simple-payment-list">{payments.slice(0,10).map(payment=><div key={payment.id}><span><strong>{payment.tenant_name||'Unmatched payment'}</strong><small>{payment.reference} · {String(payment.payment_method).toUpperCase()}</small></span><b>{money(payment.amount)}</b></div>)}{!payments.length&&<div className="billing-empty">No payments recorded yet.</div>}</div></Panel>}
 </>;
}
