import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Building2, CalendarClock, Car, CheckCircle2, Clock3, DoorOpen, LogOut, MessageSquareWarning, Phone, Plus, Search, ShieldCheck, UserCheck, Users, X } from 'lucide-react';
import { api } from '../api';
import './community-pages.css';

type Row=Record<string,any>;
const when=(value:unknown)=>value?new Date(String(value)).toLocaleString('en-KE',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const sameDay=(value:unknown,date=new Date())=>!!value&&new Date(String(value)).toDateString()===date.toDateString();

function PageError({message}:{message:string}){return message?<div className="community-error"><AlertTriangle size={15}/>{message}</div>:null}
function Modal({title,kicker,onClose,children}:{title:string;kicker:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal community-modal"><div className="modal-head"><div><span className="panel-kicker">{kicker}</span><h2>{title}</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={17}/></button></div>{children}</div></div>}

export function VisitorsPage(){
  const [rows,setRows]=useState<Row[]>([]),[properties,setProperties]=useState<Row[]>([]),[units,setUnits]=useState<Row[]>([]),[role,setRole]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState(false),[busy,setBusy]=useState('');
  const [query,setQuery]=useState(''),[view,setView]=useState<'inside'|'today'|'all'>('inside'),[form,setForm]=useState({propertyId:'',unitId:'',visitorName:'',phone:'',vehiclePlate:'',approvedBy:''});
  const load=async()=>{setLoading(true);setError('');try{const [visitors,nextProperties,nextUnits,context]=await Promise.all([api.visitors(),api.properties(),api.units(),api.billingContext()]);setRows(visitors);setProperties(nextProperties);setUnits(nextUnits);setRole(context.role)}catch(err){setError(err instanceof Error?err.message:'Could not load visitors')}finally{setLoading(false)}};
  useEffect(()=>{void load();const timer=window.setInterval(()=>{api.visitors().then(setRows).catch(()=>undefined)},15000);return()=>window.clearInterval(timer)},[]);
  const caretakerView=role==='caretaker'||role==='maintenance';
  const inside=rows.filter(row=>!row.checked_out_at),today=rows.filter(row=>sameDay(row.checked_in_at)),vehicles=inside.filter(row=>row.vehicle_plate);
  const visible=useMemo(()=>rows.filter(row=>{const matchesView=view==='all'||view==='inside'&&!row.checked_out_at||view==='today'&&sameDay(row.checked_in_at);const text=`${row.visitor_name||''} ${row.phone||''} ${row.vehicle_plate||''} ${row.property_name||''} ${row.unit_number||''}`.toLowerCase();return matchesView&&(!query||text.includes(query.toLowerCase()))}),[rows,query,view]);
  const relevantUnits=units.filter(unit=>!form.propertyId||unit.property_id===form.propertyId);
  async function submit(event:FormEvent){event.preventDefault();setBusy('save');setError('');try{await api.createVisitor({...form,unitId:form.unitId||undefined,phone:form.phone||undefined,vehiclePlate:form.vehiclePlate||undefined,approvedBy:form.approvedBy||undefined});setModal(false);setForm({propertyId:'',unitId:'',visitorName:'',phone:'',vehiclePlate:'',approvedBy:''});await load()}catch(err){setError(err instanceof Error?err.message:'Could not check in visitor')}finally{setBusy('')}}
  async function checkout(id:string){setBusy(id);setError('');try{await api.checkoutVisitor(id);await load()}catch(err){setError(err instanceof Error?err.message:'Could not check out visitor')}finally{setBusy('')}}
  return <div className="community-workspace visitors-workspace">
    <section className="community-simple-head"><div><span className="panel-kicker">{caretakerView?'GATE REGISTER':'VISITORS'}</span><h1>{caretakerView?'Visitor register':'Visitors'}</h1><p>{caretakerView?'Register visitors as they arrive and check them out when they leave.':`${inside.length} inside now · ${today.length} visit${today.length===1?'':'s'} today`}</p></div>{caretakerView&&<button className="community-add-icon" onClick={()=>setModal(true)} aria-label="Check in visitor" title="Check in visitor"><Plus size={18}/></button>}</section>
    <PageError message={error}/>
    {!caretakerView&&role&&<div className="community-role-note"><ShieldCheck size={15}/><span><strong>Admin view</strong> · Caretakers register and check out visitors. This list refreshes automatically every 15 seconds.</span></div>}
    <div className="community-metrics"><article><Users/><span><small>Visits today</small><strong>{today.length}</strong><em>All check-ins today</em></span></article><article><DoorOpen/><span><small>Inside now</small><strong>{inside.length}</strong><em>Awaiting checkout</em></span></article><article><Car/><span><small>Vehicles</small><strong>{vehicles.length}</strong><em>Currently on site</em></span></article><article><ShieldCheck/><span><small>Checked out</small><strong>{today.filter(row=>row.checked_out_at).length}</strong><em>Completed today</em></span></article></div>
    <section className="community-directory"><header><div><span className="panel-kicker">VISITOR LOG</span><h2>{caretakerView?'Gate activity':'Caretaker visitor activity'}</h2><p>{loading?'Loading visitors…':`${visible.length} record${visible.length===1?'':'s'} shown`}</p></div>{caretakerView&&<button onClick={()=>setModal(true)}><Plus size={15}/> Check in visitor</button>}</header><label className="community-search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search visitor, phone, vehicle or unit"/></label><div className="community-tabs"><button className={view==='inside'?'active':''} onClick={()=>setView('inside')}>Inside now <em>{inside.length}</em></button><button className={view==='today'?'active':''} onClick={()=>setView('today')}>Today <em>{today.length}</em></button><button className={view==='all'?'active':''} onClick={()=>setView('all')}>All visits <em>{rows.length}</em></button></div>
      <div className="visitor-list-head"><span>Visitor</span><span>Destination</span><span>Check-in</span><span>Vehicle</span><span>Status</span></div><div className="visitor-list">{visible.map(row=><article key={row.id}><div className="community-person"><span>{String(row.visitor_name||'V').charAt(0).toUpperCase()}</span><div><strong>{row.visitor_name}</strong><small><Phone size={11}/>{row.phone||'No phone'}</small></div></div><div className="community-place"><Building2 size={15}/><span><strong>{row.property_name}</strong><small>{row.unit_number?`Unit ${row.unit_number}`:'Reception / common area'}</small></span></div><div className="community-time"><Clock3 size={15}/><span><strong>{when(row.checked_in_at)}</strong><small>{row.registered_by_name?`By ${row.registered_by_name}`:row.approved_by?`Expected by ${row.approved_by}`:'Visitor register'}</small></span></div><div className="vehicle-cell"><strong>{row.vehicle_plate||'No vehicle'}</strong></div><div className="community-status-action">{row.checked_out_at?<><span className="community-status done">Checked out</span><small>{when(row.checked_out_at)}</small></>:<><span className="community-status live">Inside</span>{caretakerView&&<button onClick={()=>void checkout(row.id)} disabled={busy===row.id}><LogOut size={13}/>{busy===row.id?'Saving…':'Check out'}</button>}</>}</div></article>)}{!loading&&!visible.length&&<div className="community-empty"><UserCheck size={26}/><strong>No visitor records here</strong><span>{caretakerView?'Use Check in visitor when someone arrives.':'Caretaker registrations will appear here automatically.'}</span></div>}</div>
    </section>
    {modal&&caretakerView&&<Modal title="Check in a visitor" kicker="New visitor" onClose={()=>setModal(false)}><form onSubmit={submit}><div className="form-grid"><label><span>Visitor name</span><input required value={form.visitorName} onChange={e=>setForm(v=>({...v,visitorName:e.target.value}))} placeholder="Full name"/></label><label><span>Phone (optional)</span><input value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))} placeholder="07…"/></label><label><span>Property</span><select required value={form.propertyId} onChange={e=>setForm(v=>({...v,propertyId:e.target.value,unitId:''}))}><option value="">Choose property</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span>Unit / destination</span><select value={form.unitId} onChange={e=>setForm(v=>({...v,unitId:e.target.value}))}><option value="">Reception / common area</option>{relevantUnits.map(unit=><option key={unit.id} value={unit.id}>{unit.unit_number}</option>)}</select></label><label><span>Expected by</span><input value={form.approvedBy} onChange={e=>setForm(v=>({...v,approvedBy:e.target.value}))} placeholder="Tenant or staff name"/></label><label><span>Vehicle plate</span><input value={form.vehiclePlate} onChange={e=>setForm(v=>({...v,vehiclePlate:e.target.value.toUpperCase()}))} placeholder="KAA 123A"/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" disabled={busy==='save'}>{busy==='save'?'Checking in…':'Check in visitor'}</button></div></form></Modal>}
  </div>
}

export function ComplaintsPage(){
  const [rows,setRows]=useState<Row[]>([]),[properties,setProperties]=useState<Row[]>([]),[units,setUnits]=useState<Row[]>([]),[tenants,setTenants]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState(false),[busy,setBusy]=useState('');
  const [query,setQuery]=useState(''),[view,setView]=useState<'open'|'in_progress'|'resolved'|'all'>('open'),[form,setForm]=useState({propertyId:'',unitId:'',tenantId:'',category:'noise',priority:'normal',subject:'',description:''});
  const load=async()=>{setLoading(true);setError('');try{const [complaints,nextProperties,nextUnits,nextTenants]=await Promise.all([api.complaints(),api.properties(),api.units(),api.tenants()]);setRows(complaints);setProperties(nextProperties);setUnits(nextUnits);setTenants(nextTenants)}catch(err){setError(err instanceof Error?err.message:'Could not load complaints')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const open=rows.filter(row=>row.status==='open'),progress=rows.filter(row=>row.status==='in_progress'),resolved=rows.filter(row=>['resolved','closed'].includes(row.status)),urgent=rows.filter(row=>row.priority==='urgent'&&!['resolved','closed'].includes(row.status));
  const visible=useMemo(()=>rows.filter(row=>{const matchesView=view==='all'||view==='resolved'&&['resolved','closed'].includes(row.status)||row.status===view;const text=`${row.subject||''} ${row.category||''} ${row.tenant_name||''} ${row.property_name||''} ${row.unit_number||''}`.toLowerCase();return matchesView&&(!query||text.includes(query.toLowerCase()))}),[rows,query,view]);
  const selectedProperty=properties.find(p=>p.id===form.propertyId),relevantUnits=units.filter(unit=>!form.propertyId||unit.property_id===form.propertyId),relevantTenants=tenants.filter(tenant=>!selectedProperty||tenant.property_name===selectedProperty.name);
  async function submit(event:FormEvent){event.preventDefault();setBusy('save');setError('');try{await api.createComplaint({...form,unitId:form.unitId||undefined,tenantId:form.tenantId||undefined,description:form.description||undefined});setModal(false);setForm({propertyId:'',unitId:'',tenantId:'',category:'noise',priority:'normal',subject:'',description:''});await load()}catch(err){setError(err instanceof Error?err.message:'Could not save complaint')}finally{setBusy('')}}
  async function update(id:string,status:'in_progress'|'resolved'){setBusy(id);setError('');try{await api.updateComplaintStatus(id,status);await load()}catch(err){setError(err instanceof Error?err.message:'Could not update complaint')}finally{setBusy('')}}
  return <div className="community-workspace complaints-workspace">
    <section className="community-simple-head"><div><span className="panel-kicker">COMPLAINTS</span><h1>Resident concerns</h1><p>{open.length+progress.length} open · {urgent.length} urgent</p></div><button className="community-add-icon" onClick={()=>setModal(true)} aria-label="Add complaint" title="Add complaint"><Plus size={18}/></button></section>
    <PageError message={error}/>
    <div className="community-metrics"><article><MessageSquareWarning/><span><small>New</small><strong>{open.length}</strong><em>Waiting for action</em></span></article><article><Clock3/><span><small>In progress</small><strong>{progress.length}</strong><em>Being handled</em></span></article><article><AlertTriangle/><span><small>Urgent</small><strong>{urgent.length}</strong><em>Needs priority</em></span></article><article><CheckCircle2/><span><small>Resolved</small><strong>{resolved.length}</strong><em>Completed cases</em></span></article></div>
    <section className="community-directory"><header><div><span className="panel-kicker">COMPLAINTS DESK</span><h2>Resident concerns</h2><p>{loading?'Loading complaints…':`${visible.length} case${visible.length===1?'':'s'} shown`}</p></div><button onClick={()=>setModal(true)}><Plus size={15}/> Add complaint</button></header><label className="community-search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search subject, tenant, property or unit"/></label><div className="community-tabs four"><button className={view==='open'?'active':''} onClick={()=>setView('open')}>New <em>{open.length}</em></button><button className={view==='in_progress'?'active':''} onClick={()=>setView('in_progress')}>In progress <em>{progress.length}</em></button><button className={view==='resolved'?'active':''} onClick={()=>setView('resolved')}>Resolved <em>{resolved.length}</em></button><button className={view==='all'?'active':''} onClick={()=>setView('all')}>All <em>{rows.length}</em></button></div>
      <div className="complaint-list">{visible.map(row=><article key={row.id} className={`priority-${row.priority}`}><div className="complaint-top"><span className={`priority priority-${row.priority}`}>{row.priority}</span><span className={`community-status ${['resolved','closed'].includes(row.status)?'done':row.status==='in_progress'?'working':'live'}`}>{String(row.status).replace('_',' ')}</span><small>{when(row.created_at)}</small></div><h3>{row.subject}</h3><p>{row.description||'No additional description.'}</p><div className="complaint-meta"><span><Building2 size={14}/>{row.property_name||'No property'}{row.unit_number?` · Unit ${row.unit_number}`:''}</span><span><Users size={14}/>{row.tenant_name||'General / anonymous'}</span><span><CalendarClock size={14}/>{row.category}</span></div>{!['resolved','closed'].includes(row.status)&&<div className="complaint-actions">{row.status==='open'&&<button onClick={()=>void update(row.id,'in_progress')} disabled={busy===row.id}><Clock3 size={14}/> Start working</button>}<button className="resolve" onClick={()=>void update(row.id,'resolved')} disabled={busy===row.id}><CheckCircle2 size={14}/>{busy===row.id?'Saving…':'Resolve'}</button></div>}</article>)}{!loading&&!visible.length&&<div className="community-empty"><MessageSquareWarning size={26}/><strong>No complaints in this view</strong><span>New concerns will appear here.</span></div>}</div>
    </section>
    {modal&&<Modal title="Add a complaint" kicker="New concern" onClose={()=>setModal(false)}><form onSubmit={submit}><div className="form-grid"><label><span>Property</span><select required value={form.propertyId} onChange={e=>setForm(v=>({...v,propertyId:e.target.value,unitId:'',tenantId:''}))}><option value="">Choose property</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span>Unit (optional)</span><select value={form.unitId} onChange={e=>setForm(v=>({...v,unitId:e.target.value}))}><option value="">Whole property</option>{relevantUnits.map(unit=><option key={unit.id} value={unit.id}>{unit.unit_number}</option>)}</select></label><label><span>Tenant (optional)</span><select value={form.tenantId} onChange={e=>setForm(v=>({...v,tenantId:e.target.value}))}><option value="">General / anonymous</option>{relevantTenants.map(tenant=><option key={tenant.id} value={tenant.id}>{tenant.first_name} {tenant.last_name}</option>)}</select></label><label><span>Category</span><select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))}><option value="noise">Noise</option><option value="security">Security</option><option value="repairs">Repairs</option><option value="neighbour">Neighbour dispute</option><option value="billing">Billing</option><option value="cleanliness">Cleanliness</option><option value="other">Other</option></select></label><label><span>Priority</span><select value={form.priority} onChange={e=>setForm(v=>({...v,priority:e.target.value}))}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="full"><span>Subject</span><input required value={form.subject} onChange={e=>setForm(v=>({...v,subject:e.target.value}))} placeholder="Short summary of the concern"/></label><label className="full"><span>Description</span><textarea rows={4} value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))} placeholder="What happened, when and what help is needed?"/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" disabled={busy==='save'}>{busy==='save'?'Saving…':'Save complaint'}</button></div></form></Modal>}
  </div>
}
