import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowUpRight, Banknote, Building2, CalendarClock, CheckCircle2, CircleGauge, Clock3, MessageSquareText, ShieldCheck, Sparkles, TrendingUp, Users, Wrench } from 'lucide-react';
import { api, getToken } from '../api';
import { MetricCard, Panel, Status } from '../ui';
import { WorkflowExecutionCenter } from '../workflow-execution';

type Dashboard={properties:number;units:number;occupied:number;occupancyRate:number;outstanding:number;collectedThisMonth:number;openMaintenance:number;expiringLeases:number;scoped?:boolean};
type Property={id:string;name:string;unit_count:number;occupied_count:number};
type Arrear={property_name?:string;balance:number|string;age_days?:number};
type Job={property_name?:string;priority?:string;status?:string};
const demoHealth=[{name:'Greenview Apartments',units:148,occ:96.6,collection:'94.8%',arrears:'KES 188K',maintenance:2,score:94},{name:'Riverside Heights',units:96,occ:93.8,collection:'91.2%',arrears:'KES 241K',maintenance:1,score:91},{name:'Parkline Residences',units:124,occ:88.7,collection:'83.4%',arrears:'KES 392K',maintenance:4,score:78},{name:'The Junction Offices',units:72,occ:97.2,collection:'96.1%',arrears:'KES 76K',maintenance:0,score:96}];
const money=(n:number)=>n>=1_000_000?`KES ${(n/1_000_000).toFixed(2)}M`:n>=1_000?`KES ${(n/1_000).toFixed(0)}K`:`KES ${n.toLocaleString()}`;

export function CommandCenterPage(){
 const [dashboard,setDashboard]=useState<Dashboard|null>(null),[properties,setProperties]=useState<Property[]>([]),[arrears,setArrears]=useState<Arrear[]>([]),[jobs,setJobs]=useState<Job[]>([]),[source,setSource]=useState<'loading'|'api'|'demo'>(getToken()?'loading':'demo');
 useEffect(()=>{
  if(!getToken())return;
  let mounted=true;
  Promise.all([api.dashboard() as Promise<Dashboard>,api.properties() as Promise<Property[]>,api.arrears() as Promise<Arrear[]>,api.maintenance() as Promise<Job[]>]).then(([d,p,a,j])=>{if(mounted){setDashboard(d);setProperties(p);setArrears(a);setJobs(j);setSource('api')}}).catch(()=>{if(mounted)setSource('demo')});
  return()=>{mounted=false};
 },[]);
 const liveHealth=useMemo(()=>properties.slice(0,6).map(p=>{
  const units=Number(p.unit_count||0),occupied=Number(p.occupied_count||0),occ=units?Math.round(occupied/units*1000)/10:0;
  const debt=arrears.filter(a=>a.property_name===p.name).reduce((s,a)=>s+Number(a.balance||0),0),maintenance=jobs.filter(j=>j.property_name===p.name&&!['closed','completed','cancelled'].includes(String(j.status))).length;
  const score=Math.max(45,Math.min(99,Math.round(100-(100-occ)*.55-Math.min(25,debt/50000)-maintenance*2)));
  return {name:p.name,units,occ,collection:'—',arrears:money(debt),maintenance,score};
 }),[properties,arrears,jobs]);
 const health=source==='api'&&liveHealth.length?liveHealth:demoHealth;
 const collected=dashboard?.collectedThisMonth??12_960_000,outstanding=dashboard?.outstanding??1_860_000,expected=dashboard?collected+outstanding:14_820_000;
 const rate=expected?Math.round(collected/expected*1000)/10:0;
 const aged=arrears.filter(a=>Number(a.age_days||0)>30),agedValue=aged.reduce((s,a)=>s+Number(a.balance||0),0),urgent=jobs.filter(j=>j.priority==='urgent').length;
 return <>
  <div className="command-hero"><div><div className="eyebrow"><Sparkles size={14}/> Executive intelligence · {source==='api'?'Live API':source==='loading'?'Connecting…':'Designed demo'}</div><h1>Portfolio Command Center</h1><p>{dashboard?.scoped?'Decision intelligence is restricted to your assigned property scope.':'A decision layer for money, occupancy, tenant risk, operations and upcoming obligations—not just another dashboard.'}</p></div><div className="command-health"><span><i/> {source==='api'?'API connected':'Systems healthy'}</span><strong>{source==='api'?Math.round((dashboard?.occupancyRate||0)*.55+Math.min(100,rate)*.45):94}</strong><small>portfolio health</small></div></div>
  <div className="metric-grid four"><MetricCard label="Expected this month" value={source==='loading'?'—':money(expected)} note={`${dashboard?.units??742} units · posted + outstanding`} icon={Banknote}/><MetricCard label="Collected" value={source==='loading'?'—':money(collected)} note={`${rate}% of current receivable position`} icon={TrendingUp} tone="success"/><MetricCard label="Revenue at risk" value={source==='api'?money(agedValue):'KES 624K'} note={source==='api'?`${aged.length} balances over 30 days`:'18 accounts >30 days overdue'} icon={AlertTriangle} tone="danger"/><MetricCard label="Open operations" value={source==='api'?String(dashboard?.openMaintenance??0):'92.4%'} note={source==='api'?`${urgent} urgent maintenance requests`:'Jobs resolved within target window'} icon={CircleGauge} tone="info"/></div>
  <div className="command-grid"><Panel title="Today’s operating brief" kicker={source==='api'?'Live prioritized':'AI prioritized'}><div className="brief-list">
   <article className="brief critical"><div className="brief-icon"><AlertTriangle size={17}/></div><div><span>COLLECTION RISK · HIGH</span><strong>{source==='api'?`${aged.length} aged balances carry ${money(agedValue)} exposure`:'6 tenants account for 61% of aged arrears'}</strong><p>{source==='api'?'Work the oldest and highest-value accounts first. The command layer is now reading the organization-scoped arrears queue from the API.':'Prioritize Parkline C-18, A-07 and Riverside B-04 before broad reminders. Combined exposure is KES 381,500.'}</p><button>Open collection queue <ArrowUpRight size={13}/></button></div></article>
   <article className="brief warning"><div className="brief-icon"><CalendarClock size={17}/></div><div><span>LEASE RISK · NEXT 30 DAYS</span><strong>{source==='api'?`${dashboard?.expiringLeases??0} leases expire within 30 days`:'12 leases expire; 8 offers are still unsent'}</strong><p>{source==='api'?'Move expiring leases into renewal, notice or move-out workflows before they become vacancy exposure.':'Three high-value units have no renewal action and could create KES 146K/month vacancy exposure.'}</p><button>Review renewals <ArrowUpRight size={13}/></button></div></article>
   <article className="brief positive"><div className="brief-icon"><CheckCircle2 size={17}/></div><div><span>OPERATIONS</span><strong>{source==='api'?`${jobs.length} maintenance records visible in your scope`:'The Junction Offices reached 96.1% collection'}</strong><p>{source==='api'?`${urgent} are currently marked urgent. Property scope and organization isolation are applied before these signals reach the command center.`:'Best-performing property this month. Owner statement can be prepared early after two pending bank matches clear.'}</p><button>Open operations <ArrowUpRight size={13}/></button></div></article>
  </div></Panel>
  <Panel title="Cash position" kicker="September"><div className="cash-waterfall"><div><span>Receivable position</span><strong>{money(expected)}</strong></div><i>−</i><div className="good"><span>Collected</span><strong>{money(collected)}</strong></div><i>=</i><div className="risk"><span>Outstanding</span><strong>{money(outstanding)}</strong></div></div><div className="progress-stack"><div><span>Collected</span><strong>{rate}%</strong></div><div><span>Outstanding</span><strong>{Math.max(0,Math.round((100-rate)*10)/10)}%</strong></div><div><span>Data source</span><strong>{source==='api'?'API':'Demo'}</strong></div></div><div className="forecast-box"><TrendingUp size={18}/><div><span>Current collection position</span><strong>{money(collected)} · {rate}%</strong><small>{source==='api'?'Calculated from posted payments and open receivables.':'Designed demonstration forecast.'}</small></div></div></Panel></div>
  <div className="command-grid second"><Panel title="Property health matrix" kicker={source==='api'?'Scoped portfolio data':'Portfolio comparison'}><div className="health-table"><div className="health-head"><span>Property</span><span>Occ.</span><span>Collection</span><span>Arrears</span><span>Open jobs</span><span>Health</span></div>{health.map(p=><div className="health-row" key={p.name}><strong>{p.name}<small>{p.units} units</small></strong><span>{p.occ}%</span><span>{p.collection}</span><span>{p.arrears}</span><span>{p.maintenance}</span><b className={p.score<80?'low':p.score<90?'mid':''}>{p.score}</b></div>)}</div></Panel><Panel title="Live activity" kicker="Workspace pulse"><div className="timeline">
   <div><i><Banknote size={14}/></i><p><strong>{source==='api'?'Finance API connected':'M-Pesa payment matched'}</strong><span>{source==='api'?`${money(collected)} posted this month`:'Mercy Wanjiku · Greenview A-12 · KES 32,000'}</span></p><time>now</time></div>
   <div><i><Wrench size={14}/></i><p><strong>{urgent?`${urgent} urgent work order${urgent===1?'':'s'}`:'Maintenance queue available'}</strong><span>{source==='api'?`${jobs.length} records currently visible`:'Riverside B-04 · Water leak · Kamau Plumbing'}</span></p><time>live</time></div>
   <div><i><Users size={14}/></i><p><strong>Lease horizon</strong><span>{source==='api'?`${dashboard?.expiringLeases??0} expirations in the next 30 days`:'Brian Otieno · Parkline C-03'}</span></p><time>live</time></div>
   <div><i><MessageSquareText size={14}/></i><p><strong>Workflow execution</strong><span>Approval state is persisted and policy-checked server-side when authenticated.</span></p><time>live</time></div>
   <div><i><ShieldCheck size={14}/></i><p><strong>Security context</strong><span>{dashboard?.scoped?'Property scope enforced':'Organization session verified'}</span></p><time>now</time></div>
  </div></Panel></div>
  <div className="command-footer-grid"><div className="mini-command"><Activity size={18}/><div><span>Workspace source</span><strong>{source==='api'?'Authenticated API data':'Demo fallback data'}</strong></div><Status value={source==='api'?'Connected':'Demo'}/></div><div className="mini-command"><Clock3 size={18}/><div><span>Next critical deadline</span><strong>{source==='api'?`${dashboard?.expiringLeases??0} lease expirations · 30-day window`:'Rent reminder batch · 17:00'}</strong></div><button>Review</button></div><div className="mini-command"><Building2 size={18}/><div><span>Portfolio visibility</span><strong>{dashboard?.scoped?'Assigned properties only':`${dashboard?.properties??12} active properties`}</strong></div><span className="positive-text">{source==='api'?'Live':'Demo'}</span></div></div>
  <WorkflowExecutionCenter/>
 </>;
}
