import { useEffect, useState } from 'react';
import { AlertTriangle, Building2, CalendarDays, ChevronDown, ChevronRight, PieChart, ShieldCheck, WalletCards } from 'lucide-react';
import { api, getToken } from '../api';
import { payments as demoPayments } from '../data';
import { MetricCard, Status } from '../ui';

type DashboardData={properties:number;units:number;occupied:number;occupancyRate:number;outstanding:number;collectedThisMonth:number;openMaintenance:number;expiringLeases:number;scoped?:boolean};
type PaymentRow={reference?:string;tenant_name?:string;amount?:number|string;payment_method?:string;status?:string;paid_at?:string};
const money=(value:number)=>value>=1_000_000?`KES ${(value/1_000_000).toFixed(2)}M`:value>=1_000?`KES ${(value/1_000).toFixed(0)}K`:`KES ${value.toLocaleString()}`;

export function OverviewPage(){
  const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'];
  const [live,setLive]=useState<DashboardData|null>(null),[livePayments,setLivePayments]=useState<PaymentRow[]>([]),[loading,setLoading]=useState(!!getToken()),[apiError,setApiError]=useState('');
  useEffect(()=>{
    if(!getToken()){setLoading(false);return;}
    let mounted=true;
    Promise.all([api.dashboard() as Promise<DashboardData>,api.payments() as Promise<PaymentRow[]>]).then(([d,p])=>{if(mounted){setLive(d);setLivePayments(p.slice(0,4));setApiError('')}}).catch(e=>{if(mounted)setApiError(e instanceof Error?e.message:'Live portfolio data unavailable')}).finally(()=>{if(mounted)setLoading(false)});
    return()=>{mounted=false};
  },[]);
  const units=live?.units??742,occupied=live?.occupied??681,occupancy=live?.occupancyRate??91.8,collected=live?.collectedThisMonth??12_960_000,outstanding=live?.outstanding??1_860_000;
  const vacant=Math.max(0,units-occupied),maintenance=live?.openMaintenance??19;
  return <>
    <div className="hero-head"><div><div className="eyebrow"><ShieldCheck size={14}/> Portfolio intelligence {live&&<span className="live-source-dot">· Live API</span>}</div><h1>Good morning, Alex.</h1><p>{live?.scoped?'This overview reflects only the properties assigned to your account.':'Here’s what needs your attention across the portfolio today.'}</p></div><div className="period"><CalendarDays size={16}/> September 2026 <ChevronDown size={14}/></div></div>
    {apiError&&<div className="overview-source-note"><AlertTriangle size={14}/><span>Live API unavailable. Showing the designed demo dataset.</span><small>{apiError}</small></div>}
    <div className="metric-grid four"><MetricCard label="Portfolio units" value={loading?'—':units.toLocaleString()} note={live?`Across ${live.properties} properties${live.scoped?' · scoped view':''}`:'Across 12 properties · +18 this month'} icon={Building2}/><MetricCard label="Occupancy" value={loading?'—':`${occupancy}%`} note={`${occupied.toLocaleString()} occupied${live?'':' · +2.4%'}`} icon={PieChart} tone="success"/><MetricCard label="Rent collected" value={loading?'—':money(Number(collected))} note={live?'Posted payments this month':'87.5% of KES 14.82M expected'} icon={WalletCards} tone="info"/><MetricCard label="Outstanding" value={loading?'—':money(Number(outstanding))} note={live?'Open issued, partial and overdue invoices':'24 tenants · 18 need attention'} icon={AlertTriangle} tone="danger"/></div>
    <div className="dashboard-grid"><article className="panel chart-panel"><div className="panel-head"><div><span className="panel-kicker">Collection performance</span><h2>Rent collection</h2></div><button className="ghost-button">Last 9 months</button></div><div className="chart-summary"><div><strong>{money(Number(collected))}</strong><span>September collected</span></div><div className="rate"><strong>{live?'Live':'87.5%'}</strong><span>{live?'posted this month':'collection rate'}</span></div></div><div className="chart-wrap"><svg viewBox="0 0 900 260" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".22"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path className="gridline" d="M0 40H900 M0 100H900 M0 160H900 M0 220H900"/><path className="area" d="M0 210 C60 198,70 175,112 179 S180 198,225 188 S295 140,337 146 S405 130,450 121 S520 104,562 112 S635 78,675 86 S750 63,787 70 S860 42,900 50 L900 260 L0 260Z"/><path className="line" d="M0 210 C60 198,70 175,112 179 S180 198,225 188 S295 140,337 146 S405 130,450 121 S520 104,562 112 S635 78,675 86 S750 63,787 70 S860 42,900 50"/></svg><div className="chart-labels">{months.map(m=><span key={m}>{m}</span>)}</div></div></article><article className="panel occupancy-panel"><div className="panel-head"><div><span className="panel-kicker">Live portfolio</span><h2>Occupancy</h2></div></div><div className="donut"><div><strong>{occupancy}%</strong><span>occupied</span></div></div><div className="legend"><div><i className="dot primary"/><span>Occupied</span><strong>{occupied}</strong></div><div><i className="dot amber"/><span>Not occupied</span><strong>{vacant}</strong></div><div><i className="dot danger"/><span>Open maintenance</span><strong>{maintenance}</strong></div></div></article></div>
    <div className="dashboard-grid lower"><article className="panel"><div className="panel-head"><div><span className="panel-kicker">Action center</span><h2>Needs attention</h2></div></div><div className="attention-list">{(live?[[outstanding>0?'danger':'info',`${money(Number(outstanding))} outstanding`,'Open tenant receivables'],[live.expiringLeases>0?'warning':'info',`${live.expiringLeases} leases expire within 30 days`,'Renewal action recommended'],[live.openMaintenance>0?'amber':'info',`${live.openMaintenance} maintenance requests open`,'Review priority and SLA'],['info',live.scoped?'Property scope is active':'Full portfolio access','Data access follows your current membership']]:[['danger','18 tenants overdue >30 days','KES 624,000 outstanding'],['warning','12 leases expire within 30 days','8 renewal offers not sent'],['amber','7 maintenance tickets overdue','2 marked urgent'],['info','4 inspections awaiting review','Move-in and routine inspections']]).map(a=><div className="attention-row" key={String(a[1])}><i className={`pulse ${a[0]}`}/><div><strong>{a[1]}</strong><span>{a[2]}</span></div><ChevronRight size={15}/></div>)}</div></article><article className="panel"><div className="panel-head"><div><span className="panel-kicker">Transactions</span><h2>Recent payments</h2></div></div><div className="payment-list">{live&&livePayments.length?livePayments.map((p,i)=><div className="payment-row" key={p.reference||i}><div className="tenant-avatar">{(p.tenant_name||'UN').split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div className="payment-person"><strong>{p.tenant_name||'Unmatched payer'}</strong><span>{p.reference||'No reference'}</span></div><div className="payment-amount"><strong>{money(Number(p.amount||0))}</strong><span>{String(p.payment_method||'payment').toUpperCase()}</span></div><Status value={p.status||'Posted'}/></div>):demoPayments.slice(0,4).map(p=><div className="payment-row" key={p[0]}><div className="tenant-avatar">{p[1].split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div className="payment-person"><strong>{p[1]}</strong><span>{p[2]}</span></div><div className="payment-amount"><strong>{p[3]}</strong><span>{p[4]}</span></div><Status value={p[6]}/></div>)}</div></article></div>
  </>;
}
