import { AlertTriangle, Building2, CalendarDays, ChevronDown, ChevronRight, PieChart, ShieldCheck, WalletCards } from 'lucide-react';
import { payments } from '../data';
import { MetricCard, Status } from '../ui';

export function OverviewPage(){
  const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'];
  return <>
    <div className="hero-head"><div><div className="eyebrow"><ShieldCheck size={14}/> Portfolio intelligence</div><h1>Good morning, Alex.</h1><p>Here’s what needs your attention across the portfolio today.</p></div><div className="period"><CalendarDays size={16}/> September 2026 <ChevronDown size={14}/></div></div>
    <div className="metric-grid four"><MetricCard label="Portfolio units" value="742" note="Across 12 properties · +18 this month" icon={Building2}/><MetricCard label="Occupancy" value="91.8%" note="681 occupied · +2.4%" icon={PieChart} tone="success"/><MetricCard label="Rent collected" value="KES 12.96M" note="87.5% of KES 14.82M expected" icon={WalletCards} tone="info"/><MetricCard label="Outstanding" value="KES 1.86M" note="24 tenants · 18 need attention" icon={AlertTriangle} tone="danger"/></div>
    <div className="dashboard-grid"><article className="panel chart-panel"><div className="panel-head"><div><span className="panel-kicker">Collection performance</span><h2>Rent collection</h2></div><button className="ghost-button">Last 9 months</button></div><div className="chart-summary"><div><strong>KES 12.96M</strong><span>September collected</span></div><div className="rate"><strong>87.5%</strong><span>collection rate</span></div></div><div className="chart-wrap"><svg viewBox="0 0 900 260" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".22"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path className="gridline" d="M0 40H900 M0 100H900 M0 160H900 M0 220H900"/><path className="area" d="M0 210 C60 198,70 175,112 179 S180 198,225 188 S295 140,337 146 S405 130,450 121 S520 104,562 112 S635 78,675 86 S750 63,787 70 S860 42,900 50 L900 260 L0 260Z"/><path className="line" d="M0 210 C60 198,70 175,112 179 S180 198,225 188 S295 140,337 146 S405 130,450 121 S520 104,562 112 S635 78,675 86 S750 63,787 70 S860 42,900 50"/></svg><div className="chart-labels">{months.map(m=><span key={m}>{m}</span>)}</div></div></article><article className="panel occupancy-panel"><div className="panel-head"><div><span className="panel-kicker">Live portfolio</span><h2>Occupancy</h2></div></div><div className="donut"><div><strong>91.8%</strong><span>occupied</span></div></div><div className="legend"><div><i className="dot primary"/><span>Occupied</span><strong>681</strong></div><div><i className="dot amber"/><span>Vacant</span><strong>42</strong></div><div><i className="dot danger"/><span>Maintenance</span><strong>19</strong></div></div></article></div>
    <div className="dashboard-grid lower"><article className="panel"><div className="panel-head"><div><span className="panel-kicker">Action center</span><h2>Needs attention</h2></div></div><div className="attention-list">{[['danger','18 tenants overdue >30 days','KES 624,000 outstanding'],['warning','12 leases expire within 30 days','8 renewal offers not sent'],['amber','7 maintenance tickets overdue','2 marked urgent'],['info','4 inspections awaiting review','Move-in and routine inspections']].map(a=><div className="attention-row" key={a[1]}><i className={`pulse ${a[0]}`}/><div><strong>{a[1]}</strong><span>{a[2]}</span></div><ChevronRight size={15}/></div>)}</div></article><article className="panel"><div className="panel-head"><div><span className="panel-kicker">Transactions</span><h2>Recent payments</h2></div></div><div className="payment-list">{payments.slice(0,4).map(p=><div className="payment-row" key={p[0]}><div className="tenant-avatar">{p[1].split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div className="payment-person"><strong>{p[1]}</strong><span>{p[2]}</span></div><div className="payment-amount"><strong>{p[3]}</strong><span>{p[4]}</span></div><Status value={p[6]}/></div>)}</div></article></div>
  </>;
}
