import { Activity, AlertTriangle, BellRing, CheckCircle2, Clock3, FileCheck2, KeyRound, LockKeyhole, MessageSquareText, ShieldCheck, UserCog, Users } from 'lucide-react';
import { DataTable, MetricCard, Panel, Status } from '../ui';

function Head({eyebrow,title,sub,action}:{eyebrow:string;title:string;sub:string;action:string}){return <div className="deep-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div><button className="primary-button">{action}</button></div>}

export function ApprovalCenter(){
 const rows=[['APR-882','Owner payout','KES 4,960,000','John M. Kamau','Grace Muthoni','High','Pending'],['APR-879','Vendor invoice','KES 86,400','Elevate Kenya','Sarah Njeri','Medium','Pending'],['APR-874','Deposit deduction','KES 12,800','Brian Otieno','Peter Mwangi','Medium','Review'],['APR-871','Rent write-off','KES 28,000','Former tenant A-04','Grace Muthoni','High','Pending']];
 return <><Head eyebrow="Control tower · Four-eyes approval" title="Approval Center" sub="Put money movement and sensitive operational actions behind explicit, auditable approval gates." action="Approval policies"/><div className="metric-grid four"><MetricCard label="Awaiting approval" value="12" note="KES 5.41M financial exposure" icon={Clock3}/><MetricCard label="High risk" value="3" note="Payouts, write-offs and refunds" icon={AlertTriangle} tone="danger"/><MetricCard label="Approved today" value="28" note="Median decision 18 minutes" icon={CheckCircle2} tone="success"/><MetricCard label="Policy coverage" value="96%" note="Sensitive actions protected" icon={ShieldCheck} tone="info"/></div><div className="approval-layout"><Panel title="Approval inbox" kicker="Risk-ranked"><DataTable headers={['ID','Type','Amount','Related to','Requested by','Risk','State']} rows={rows.map(r=>[...r.slice(0,5),<span className={`risk-badge ${r[5].toLowerCase()}`}>{r[5]}</span>,<Status value={r[6]}/>])}/></Panel><Panel title="Decision context" kicker="Selected · APR-882"><div className="approval-summary"><div><span>Request</span><strong>Owner distribution</strong></div><div><span>Amount</span><strong>KES 4,960,000</strong></div><div><span>Beneficiary</span><strong>John M. Kamau</strong></div><div><span>Prepared by</span><strong>Grace Muthoni</strong></div></div><div className="policy-checks"><p><CheckCircle2/> Bank account verified</p><p><CheckCircle2/> Statement generated</p><p><CheckCircle2/> Reconciliation complete</p><p><AlertTriangle/> Director approval required</p></div><div className="approval-buttons"><button className="secondary-button">Reject</button><button className="primary-button">Approve securely</button></div></Panel></div></>;
}

export function AuditExplorer(){
 const events=[['11:42:18','Grace Muthoni','payment.allocate','INV-2026-09041','192.168.1.22','Success'],['11:31:04','Sarah Njeri','tenant.update','TEN-00418','197.248.4.19','Success'],['11:18:51','System','automation.execute','AUTO-019','internal','Success'],['10:54:03','Alex N.','organization.role.update','USR-0044','41.90.72.14','Success'],['10:32:26','Peter Mwangi','deposit.adjustment.request','DEP-2025-203','105.160.18.2','Review']];
 return <><Head eyebrow="Security & accountability" title="Audit Explorer" sub="Trace who changed what, when, from where, and what the system looked like before and after the action." action="Export audit bundle"/><div className="audit-query"><span>Search event, actor, entity or IP</span><div><button>All modules</button><button>Last 24 hours</button><button>All actors</button><button className="active">Run query</button></div></div><div className="metric-grid four"><MetricCard label="Events today" value="1,284" note="Across 14 active users" icon={Activity}/><MetricCard label="Sensitive actions" value="46" note="Payments, roles and deletions" icon={LockKeyhole} tone="info"/><MetricCard label="Failed actions" value="7" note="Mostly permission denials" icon={AlertTriangle} tone="danger"/><MetricCard label="Integrity" value="Verified" note="Append-only audit chain" icon={ShieldCheck} tone="success"/></div><Panel title="Event stream" kicker="Immutable workspace history"><DataTable headers={['Time','Actor','Action','Entity','Source','Result']} rows={events.map(r=>[...r.slice(0,5),<Status value={r[5]}/>])}/></Panel><div className="audit-detail"><div><span>Selected event</span><strong>payment.allocate</strong><small>evt_01J8Z0R7XB2N</small></div><div className="diff-block"><section><span>Before</span><code>{`{ invoice_balance: 32000, paid: 0 }`}</code></section><section><span>After</span><code>{`{ invoice_balance: 0, paid: 32000 }`}</code></section></div></div></>;
}

export function NotificationCenter(){
 const items=[['Critical','Payment gateway','7 unmatched M-Pesa transactions require review','2m','Open'],['Warning','Collections','6 high-value arrears cases have no activity in 48h','18m','Open'],['Info','Leasing','8 renewal offers are ready to send','34m','Ready'],['Success','Month close','KCB settlement batch reconciled with zero variance','1h','Resolved'],['Warning','Maintenance','WO-2217 is approaching SLA breach in 42 minutes','1h','Open']];
 return <><Head eyebrow="Attention management" title="Notification Center" sub="A prioritized signal layer for money, risk, deadlines, approvals and operational exceptions across the workspace." action="Notification rules"/><div className="notification-shell"><aside><div className="notification-filters"><button className="active">Inbox <b>17</b></button><button>Financial <b>8</b></button><button>Operations <b>5</b></button><button>Leasing <b>3</b></button><button>Security <b>1</b></button><button>Resolved</button></div></aside><main><div className="notification-toolbar"><strong>Priority inbox</strong><span>Only actionable signals are surfaced here.</span><button>Mark all read</button></div><div className="notification-list">{items.map(n=><article key={n[2]}><i className={n[0].toLowerCase()}>{n[0]==='Critical'?<AlertTriangle/>:n[0]==='Success'?<CheckCircle2/>:<BellRing/>}</i><div><span>{n[1]}</span><strong>{n[2]}</strong><small>{n[3]} ago</small></div><Status value={n[4]}/></article>)}</div></main></div></>;
}

export function AccessReviewWorkspace(){
 const users=[['Alex N.','Company Admin','All properties','MFA on','Today','Active'],['Grace Muthoni','Accountant','Finance + all properties','MFA on','Today','Active'],['Sarah Njeri','Property Manager','4 properties','MFA on','Today','Active'],['Peter Mwangi','Caretaker','Greenview only','MFA off','Yesterday','Review'],['API Integration','Service account','Payments read/write','Key auth','Today','Active']];
 return <><Head eyebrow="Identity governance" title="Access Review" sub="Continuously verify that people and service accounts only retain the access they need." action="Start quarterly review"/><div className="metric-grid four"><MetricCard label="Principals" value="19" note="14 people · 5 service accounts" icon={Users}/><MetricCard label="Privileged" value="4" note="Admin or finance approval rights" icon={KeyRound} tone="info"/><MetricCard label="MFA coverage" value="92.9%" note="1 user requires remediation" icon={ShieldCheck} tone="success"/><MetricCard label="Stale access" value="2" note="No activity in 45+ days" icon={AlertTriangle} tone="danger"/></div><div className="approval-layout"><Panel title="Workspace access" kicker="Users & service accounts"><DataTable headers={['Principal','Role','Scope','Authentication','Last active','State']} rows={users.map(r=>[...r.slice(0,5),<Status value={r[5]}/>])}/></Panel><Panel title="Access posture" kicker="Least privilege"><div className="posture-score"><strong>91</strong><span>Strong</span><small>2 recommendations</small></div><div className="policy-checks"><p><CheckCircle2/> Finance approvals separated</p><p><CheckCircle2/> Service accounts scoped</p><p><AlertTriangle/> Caretaker missing MFA</p><p><AlertTriangle/> 2 dormant accounts</p></div></Panel></div></>;
}
