import { AlertTriangle, ArrowRight, Banknote, Building2, CheckCircle2, ClipboardCheck, CreditCard, FileCheck2, FileText, KeyRound, Landmark, LockKeyhole, MessageSquareText, ReceiptText, ShieldCheck, Sparkles, UserCheck, Users, WalletCards } from 'lucide-react';
import { DataTable, MetricCard, Panel, Status } from '../ui';

function WorkspaceHeader({kicker,title,subtitle,actions}:{kicker:string;title:string;subtitle:string;actions?:string[]}){
  return <div className="deep-header"><div><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{subtitle}</p></div><div className="deep-actions">{(actions||['Save']).map((a,i)=><button key={a} className={i===(actions?.length||1)-1?'primary-button':'secondary-button'}>{a}</button>)}</div></div>;
}

export function MoveInWorkspace(){
 const checks=[['Lease signed','Complete'],['Deposit received','Complete'],['First rent received','Complete'],['ID & KYC verified','Complete'],['Move-in inspection','Scheduled'],['Utility meter captured','Pending'],['Access credentials issued','Pending'],['Welcome pack delivered','Pending']];
 return <><WorkspaceHeader kicker="Move-in orchestration · MOV-1028" title="Mercy Wanjiku · Greenview A-12" subtitle="Coordinate every legal, financial and operational step before possession." actions={['Message tenant','Complete move-in']}/><div className="journey-strip">{['Approved','Lease','Payments','Inspection','Access','Handover'].map((x,i)=><div className={i<4?'done':''} key={x}><i>{i<4?'✓':i+1}</i><span>{x}</span></div>)}</div><div className="deep-grid"><Panel title="Readiness checklist" kicker="8-step control"><div className="readiness-list">{checks.map((c,i)=><div key={c[0]}><span className={c[1]==='Complete'?'check-dot done':'check-dot'}>{c[1]==='Complete'?'✓':i+1}</span><strong>{c[0]}</strong><Status value={c[1]}/></div>)}</div></Panel><Panel title="Move-in intelligence" kicker="Risk & completeness"><div className="score-hero"><strong>82%</strong><span>ready for handover</span></div><div className="risk-note"><Sparkles size={17}/><p>Primary blockers are the utility reading and access handover. Completing both would reduce first-week support risk substantially.</p></div></Panel></div><div className="deep-grid"><Panel title="Financial clearance" kicker="Before possession"><DataTable headers={['Charge','Expected','Received','Status']} rows={[["Deposit","KES 64,000","KES 64,000",<Status value="Complete"/>],["First month rent","KES 32,000","KES 32,000",<Status value="Complete"/>],["Utility float","KES 5,000","KES 0",<Status value="Pending"/>]]}/></Panel><Panel title="Handover pack" kicker="Tenant experience"><div className="handover-cards"><div><KeyRound/><span>Access</span><strong>2 keys · 1 gate tag</strong></div><div><FileText/><span>Documents</span><strong>Lease + rules + inventory</strong></div><div><MessageSquareText/><span>Welcome</span><strong>WhatsApp journey scheduled</strong></div></div></Panel></div></>;
}

export function MoveOutWorkspace(){
 return <><WorkspaceHeader kicker="Move-out control · MOUT-088" title="Brian Otieno · Parkline C-03" subtitle="Protect the asset, close the tenant ledger and return the deposit with a defensible audit trail." actions={['Contact tenant','Approve settlement']}/><div className="moveout-summary"><div><span>Notice date</span><strong>01 Sep 2026</strong></div><div><span>Vacate date</span><strong>30 Sep 2026</strong></div><div><span>Deposit held</span><strong>KES 56,000</strong></div><div><span>Provisional deductions</span><strong>KES 12,800</strong></div><div><span>Estimated refund</span><strong>KES 43,200</strong></div></div><div className="deep-grid"><Panel title="Exit checklist" kicker="Property possession"><div className="readiness-list">{[['Notice accepted','Complete'],['Pre-exit inspection','Complete'],['Final meter reading','Pending'],['Keys returned','Pending'],['Final inspection','Scheduled'],['Ledger closed','Pending']].map((x,i)=><div key={x[0]}><span className={x[1]==='Complete'?'check-dot done':'check-dot'}>{x[1]==='Complete'?'✓':i+1}</span><strong>{x[0]}</strong><Status value={x[1]}/></div>)}</div></Panel><Panel title="Deposit settlement" kicker="Provisional"><div className="settlement-card"><div><span>Deposit held</span><strong>KES 56,000</strong></div><div className="deduct"><span>Less: repainting</span><strong>− KES 8,000</strong></div><div className="deduct"><span>Less: final water bill</span><strong>− KES 4,800</strong></div><div className="total"><span>Refund due</span><strong>KES 43,200</strong></div></div></Panel></div></>;
}

export function DepositLedgerWorkspace(){
 const rows=[['DEP-2024-118','Mercy Wanjiku','Greenview A-12','KES 64,000','Escrow','Held','02 Feb 2024'],['DEP-2025-203','Brian Otieno','Parkline C-03','KES 56,000','Escrow','Pending refund','03 Mar 2025'],['DEP-2026-041','Alice Njeri','Riverside B-08','KES 70,000','Escrow','Held','12 Jan 2026']];
 return <><WorkspaceHeader kicker="Trust money · Deposit control" title="Security Deposit Ledger" subtitle="Track protected tenant deposits separately from operating cash, with movement history and refund controls." actions={['Export ledger','Record adjustment']}/><div className="metric-grid four"><MetricCard label="Deposits held" value="KES 8.94M" note="661 active deposit balances" icon={LockKeyhole}/><MetricCard label="Pending refunds" value="KES 412K" note="8 move-outs in settlement" icon={WalletCards} tone="info"/><MetricCard label="Unallocated" value="KES 0" note="No unmatched trust balances" icon={CheckCircle2} tone="success"/><MetricCard label="Control exceptions" value="2" note="Require finance review" icon={AlertTriangle} tone="danger"/></div><Panel title="Deposit register" kicker="Protected balances"><DataTable headers={['Deposit ID','Tenant','Unit','Balance','Account','Status','Received']} rows={rows.map(r=>[...r.slice(0,5),<Status value={r[5]}/>,r[6]])}/></Panel></>;
}

export function CollectionsCaseWorkspace(){
 return <><WorkspaceHeader kicker="Collections case · COL-991" title="Peter Kamau · Parkline A-07" subtitle="Turn arrears into an accountable case with promises, communications, tasks and escalation history." actions={['Send message','Record promise','Escalate']}/><div className="case-banner"><div><span>Outstanding</span><strong>KES 84,000</strong><small>48 days overdue</small></div><div><span>Last payment</span><strong>KES 28,000</strong><small>22 Jul 2026</small></div><div><span>Risk score</span><strong>78 / 100</strong><small>High collection risk</small></div><div><span>Case owner</span><strong>Sarah Njeri</strong><small>Property manager</small></div></div><div className="deep-grid"><Panel title="Recovery strategy" kicker="Next best actions"><div className="strategy-steps"><div className="active"><i>1</i><p><strong>Payment-plan follow-up</strong><span>Promise of KES 40K by 10 Sep has not been confirmed.</span></p></div><div><i>2</i><p><strong>Manager call</strong><span>Trigger if no response within 24 hours.</span></p></div><div><i>3</i><p><strong>Formal demand</strong><span>Generate notice with ledger attachment.</span></p></div><div><i>4</i><p><strong>Legal escalation</strong><span>Requires admin approval.</span></p></div></div></Panel><Panel title="Case intelligence" kicker="Polyizon collections AI"><div className="risk-note"><Sparkles size={18}/><p>Tenant historically pays after personal reminders, not broadcast messages. A manager-led WhatsApp followed by a call has the highest predicted recovery probability.</p></div><div className="probability"><span>Predicted 14-day recovery</span><strong>72%</strong><i><b style={{width:'72%'}}/></i></div></Panel></div><Panel title="Case timeline" kicker="Evidence trail"><div className="case-timeline">{[['08 Sep · 10:12','WhatsApp delivered','Payment-plan reminder viewed'],['06 Sep · 15:44','Promise recorded','Tenant promised KES 40,000 by 10 Sep'],['01 Sep · 09:00','Reminder automation','Day-30 arrears workflow triggered'],['22 Aug · 14:21','Phone call','Tenant requested additional time']].map(x=><div key={x[0]}><time>{x[0]}</time><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div></Panel></>;
}

export function BankReconciliationWorkspace(){
 const rows=[['02 Sep','M-Pesa settlement','KES 1,842,400','KES 1,842,400','KES 0','Matched'],['03 Sep','KCB rent account','KES 684,200','KES 680,200','KES 4,000','Review'],['04 Sep','M-Pesa settlement','KES 2,116,800','KES 2,116,800','KES 0','Matched'],['05 Sep','Equity operating','KES 418,500','KES 418,500','KES 0','Matched']];
 return <><WorkspaceHeader kicker="Finance control · September 2026" title="Bank Reconciliation" subtitle="Prove that gateway settlements, bank statements, tenant receipts and the general ledger agree." actions={['Import statement','Reconcile selected']}/><div className="recon-hero"><div><span>Statement balance</span><strong>KES 6.84M</strong></div><ArrowRight/><div><span>Ledger balance</span><strong>KES 6.836M</strong></div><ArrowRight/><div className="warn"><span>Difference</span><strong>KES 4,000</strong></div></div><div className="deep-grid"><Panel title="Settlement matching" kicker="Bank vs ledger"><DataTable headers={['Date','Source','Statement','Ledger','Variance','Status']} rows={rows.map(r=>[...r.slice(0,5),<Status value={r[5]}/>])}/></Panel><Panel title="Control checklist" kicker="Close readiness"><div className="readiness-list">{[['M-Pesa settlements','Complete'],['Bank charges','Complete'],['Unidentified credits','Complete'],['KCB variance KES 4K','Review'],['Manager approval','Pending']].map((x,i)=><div key={x[0]}><span className={x[1]==='Complete'?'check-dot done':'check-dot'}>{x[1]==='Complete'?'✓':i+1}</span><strong>{x[0]}</strong><Status value={x[1]}/></div>)}</div></Panel></div></>;
}

export function OwnerDistributionWorkspace(){
 return <><WorkspaceHeader kicker="Owner payout run · SEP-2026" title="September Owner Distribution" subtitle="Calculate, approve and pay owner proceeds after rent, expenses, fees and reserves are fully reconciled." actions={['Preview statements','Approve payout run']}/><div className="distribution-flow"><div><span>Gross collected</span><strong>KES 12.96M</strong></div><i>−</i><div><span>Expenses</span><strong>KES 2.31M</strong></div><i>−</i><div><span>Management fees</span><strong>KES 1.18M</strong></div><i>−</i><div><span>Reserves</span><strong>KES 1.05M</strong></div><i>=</i><div className="final"><span>Owner payable</span><strong>KES 8.42M</strong></div></div><div className="deep-grid"><Panel title="Distribution batch" kicker="18 owners"><DataTable headers={['Owner','Properties','Gross','Deductions','Net payable','Status']} rows={[["John M. Kamau","3","KES 5.48M","KES 520K","KES 4.96M",<Status value="Ready"/>],["Amina Holdings Ltd","2","KES 2.18M","KES 268K","KES 1.91M",<Status value="Ready"/>],["Grace Wambui","1","KES 924K","KES 104K","KES 820K",<Status value="Review"/>]]}/></Panel><Panel title="Payout controls" kicker="Approval gate"><div className="readiness-list">{[['All rent receipts posted','Complete'],['Vendor expenses approved','Complete'],['Management fees posted','Complete'],['Owner statements generated','Complete'],['Bank account validation','Review'],['Director approval','Pending']].map((x,i)=><div key={x[0]}><span className={x[1]==='Complete'?'check-dot done':'check-dot'}>{x[1]==='Complete'?'✓':i+1}</span><strong>{x[0]}</strong><Status value={x[1]}/></div>)}</div></Panel></div></>;
}

export function ApplicationWorkspace(){
 return <><WorkspaceHeader kicker="Applicant · APP-2204" title="Faith Njeri · Greenview B-08" subtitle="Prospect screening, affordability, references and approval decision in one workspace." actions={['Request document','Reject','Approve application']}/><div className="applicant-hero"><div className="applicant-avatar">FN</div><div><strong>Faith Njeri</strong><span>2-bedroom application · KES 35,000 monthly rent</span></div><div className="applicant-score"><span>Application score</span><strong>88</strong><small>Low risk</small></div></div><div className="deep-grid"><Panel title="Screening" kicker="Decision inputs"><div className="screening-grid"><div><UserCheck/><span>Identity</span><strong>Verified</strong><small>ID + selfie match</small></div><div><Banknote/><span>Affordability</span><strong>3.8× rent</strong><small>Net income KES 134K</small></div><div><ShieldCheck/><span>References</span><strong>2 / 2 passed</strong><small>Employer + landlord</small></div><div><ReceiptText/><span>Payment risk</span><strong>Low</strong><small>No adverse flags</small></div></div></Panel><Panel title="AI recommendation" kicker="Decision support"><div className="risk-note"><Sparkles size={18}/><p>Applicant meets affordability threshold, identity is verified and landlord reference is positive. Recommend approval subject to deposit and lease execution.</p></div><button className="primary-button">Generate approval pack</button></Panel></div><Panel title="Application documents" kicker="Completeness"><DataTable headers={['Document','Status','Verified by','Updated']} rows={[["National ID",<Status value="Verified"/>,"Automated KYC","08 Sep"],["3-month payslips",<Status value="Verified"/>,"Grace Muthoni","08 Sep"],["Bank statement",<Status value="Verified"/>,"Grace Muthoni","08 Sep"],["Employer letter",<Status value="Complete"/>,"Sarah Njeri","07 Sep"]]}/></Panel></>;
}
