import { Activity, BadgeCheck, Banknote, Building2, CalendarClock, CheckCircle2, ClipboardCheck, FileCheck2, FileText, Gauge, Landmark, MapPin, MessageSquareText, PackageCheck, ReceiptText, ShieldCheck, Sparkles, TrendingUp, UserRoundCog, Users, WalletCards, Wrench } from 'lucide-react';
import { DataTable, MetricCard, Panel, Status } from '../ui';

function WorkspaceHeader({eyebrow,title,subtitle,status,avatar,actions=[]}:{eyebrow:string;title:string;subtitle:string;status:string;avatar:string;actions?:string[]}){
 return <><div className="deep-hero"><div className="deep-avatar">{avatar}</div><div className="deep-copy"><span>{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p><div><Status value={status}/><small>Live workspace · synced moments ago</small></div></div><div className="deep-actions">{actions.map((a,i)=><button key={a} className={i===actions.length-1?'primary-button':'secondary-button'}>{a}</button>)}</div></div></>;
}
function Tabs({items}:{items:string[]}){return <div className="entity-tabs deep-tabs">{items.map((x,i)=><button key={x} className={i===0?'active':''}>{x}</button>)}</div>}

export function OwnerProfilePage(){
 return <><WorkspaceHeader eyebrow="Owner profile · OWN-0018" title="John M. Kamau" subtitle="Individual owner · 3 properties · 214 units" status="Active" avatar="JK" actions={['Message','Statement','Owner actions']}/><Tabs items={['Overview','Properties','Statements','Payments','Expenses','Documents','Activity']}/>
 <div className="metric-grid four"><MetricCard label="Gross rent" value="KES 6.24M" note="September portfolio income" icon={Banknote} tone="success"/><MetricCard label="Net payable" value="KES 4.96M" note="After fees and expenses" icon={WalletCards}/><MetricCard label="Portfolio occupancy" value="95.1%" note="204 / 214 units occupied" icon={Building2} tone="info"/><MetricCard label="YTD return" value="10.8%" note="Net operating yield" icon={TrendingUp}/></div>
 <div className="detail-grid"><Panel title="Owner portfolio" kicker="Asset performance"><DataTable headers={['Property','Units','Occupancy','Gross rent','Expenses','Net payable']} rows={[["Greenview Apartments","148","96.6%","KES 4.82M","KES 910K","KES 3.38M"],["Westfield Court","42","92.9%","KES 920K","KES 148K","KES 674K"],["Karen Villas","24","91.7%","KES 500K","KES 96K","KES 906K"]]}/></Panel><Panel title="Owner intelligence" kicker="Polyizon AI"><div className="intel-card"><Sparkles size={18}/><div><strong>Portfolio is outperforming benchmark</strong><p>Occupancy is 3.4 points above comparable assets. Greenview carries most income concentration, while Karen Villas has the strongest rent-growth potential.</p><button>Generate owner briefing</button></div></div><div className="owner-payout"><span>Next distribution</span><strong>KES 4.96M</strong><small>Scheduled 03 Oct · 2 reconciliation checks remaining</small></div></Panel></div>
 <Panel title="Statement activity" kicker="Recent owner ledger"><div className="detail-feed timeline-large"><div><ReceiptText/><p><strong>September draft statement generated</strong><span>3 properties · 214 units · pending 2 expense approvals</span></p><b>Today</b></div><div><WalletCards/><p><strong>August owner payout completed</strong><span>KES 4.71M · Equity Bank ending 3421</span></p><b>05 Sep</b></div><div><FileText/><p><strong>Owner agreement renewed</strong><span>Management fee retained at 7.5%</span></p><b>22 Aug</b></div></div></Panel></>;
}

export function UnitProfilePage(){
 return <><WorkspaceHeader eyebrow="Unit profile · UNI-GV-A12" title="Greenview · A-12" subtitle="2 Bedroom Apartment · 3rd Floor · 86 m²" status="Occupied" avatar="A12" actions={['Inspect','Message tenant','Unit actions']}/><Tabs items={['Overview','Tenant','Lease','Ledger','Maintenance','Utilities','Inspections','Documents','Activity']}/>
 <div className="unit-dossier"><div className="unit-visual"><div className="unit-plan"><span>LIVING</span><span>BED 1</span><span>BED 2</span><span>KITCHEN</span></div><div className="unit-caption"><strong>Unit A-12</strong><span>2 bed · 2 bath · balcony · parking P12</span></div></div><div className="unit-facts"><div><span>Current tenant</span><strong>Mercy Wanjiku</strong></div><div><span>Monthly rent</span><strong>KES 32,000</strong></div><div><span>Market rent</span><strong>KES 34,500</strong></div><div><span>Deposit held</span><strong>KES 64,000</strong></div><div><span>Lease expiry</span><strong>31 Jan 2027</strong></div><div><span>Condition score</span><strong>92 / 100</strong></div></div></div>
 <div className="detail-grid"><Panel title="Revenue history" kicker="12 month unit economics"><div className="unit-economics"><div><span>Gross billed</span><strong>KES 384K</strong><small>12 months</small></div><div><span>Collected</span><strong>KES 384K</strong><small>100% realization</small></div><div><span>Maintenance</span><strong>KES 11.4K</strong><small>3.0% of rent</small></div><div><span>Net unit income</span><strong>KES 372.6K</strong><small>Before shared OPEX</small></div></div></Panel><Panel title="Unit intelligence" kicker="Pricing & risk"><div className="intel-card"><Sparkles size={18}/><div><strong>Under market by ~7.2%</strong><p>Comparable occupied units are averaging KES 34,300. Tenant reliability is excellent, making a measured renewal increase viable.</p><button>Prepare renewal pricing</button></div></div></Panel></div>
 <Panel title="Unit timeline" kicker="Complete lifecycle"><div className="detail-feed timeline-large"><div><WalletCards/><p><strong>September rent paid</strong><span>KES 32,000 · M-Pesa · auto reconciled</span></p><b>02 Sep</b></div><div><Wrench/><p><strong>Plumbing work order completed</strong><span>Kitchen pressure restored · KES 4,800</span></p><b>28 Aug</b></div><div><ClipboardCheck/><p><strong>Routine inspection passed</strong><span>Condition score 92 · no material defects</span></p><b>15 Jul</b></div></div></Panel></>;
}

export function InvoiceWorkspacePage(){
 return <><WorkspaceHeader eyebrow="Invoice workspace · INV-2026-09041" title="September Rent · Greenview A-12" subtitle="Mercy Wanjiku · Due 05 Sep 2026" status="Paid" avatar="INV" actions={['Send receipt','Download PDF','Invoice actions']}/><Tabs items={['Summary','Line items','Payments','Ledger','Communications','Activity']}/>
 <div className="invoice-sheet"><div className="invoice-top"><div><span>BILLED TO</span><strong>Mercy Wanjiku</strong><small>Greenview Apartments · A-12</small></div><div><span>INVOICE TOTAL</span><strong>KES 32,000</strong><small>Balance KES 0</small></div></div><div className="invoice-line"><span>Monthly residential rent</span><small>September 2026 · Lease LEA-2026-041</small><strong>KES 32,000</strong></div><div className="invoice-total"><span>Subtotal</span><strong>KES 32,000</strong><span>Paid</span><strong className="good-text">KES 32,000</strong><span>Balance</span><strong>KES 0</strong></div></div>
 <div className="detail-grid"><Panel title="Payment allocation" kicker="Matched automatically"><div className="allocation-card"><CheckCircle2 size={22}/><div><span>M-Pesa QK28P9J7HL</span><strong>KES 32,000</strong><small>02 Sep 2026 · 08:41 · account GV-A12</small></div><Status value="Posted"/></div></Panel><Panel title="Accounting trail" kicker="Journal posting"><div className="journal"><div><span>DR</span><strong>M-Pesa clearing</strong><b>KES 32,000</b></div><div><span>CR</span><strong>Tenant receivables</strong><b>KES 32,000</b></div></div></Panel></div></>;
}

export function VendorProfilePage(){
 return <><WorkspaceHeader eyebrow="Vendor profile · VEN-0007" title="Kamau Plumbing Ltd" subtitle="Approved plumbing contractor · Nairobi region" status="Active" avatar="KP" actions={['New work order','Message','Vendor actions']}/><Tabs items={['Overview','Jobs','Quotes','Invoices','Properties','Compliance','Documents','Activity']}/>
 <div className="metric-grid four"><MetricCard label="Jobs completed" value="124" note="Last 12 months" icon={Wrench}/><MetricCard label="Average rating" value="4.7 / 5" note="112 rated jobs" icon={BadgeCheck} tone="success"/><MetricCard label="Avg response" value="38 min" note="Target 60 minutes" icon={Gauge} tone="info"/><MetricCard label="Spend YTD" value="KES 684K" note="Across 14 properties" icon={Banknote}/></div>
 <div className="detail-grid"><Panel title="Performance scorecard" kicker="Service quality"><div className="performance-lines">{[['Response SLA','96.2%',96],['Completion SLA','93.8%',94],['First-time fix','89.4%',89],['Tenant satisfaction','94.1%',94]].map(x=><div key={x[0]}><div><span>{x[0]}</span><strong>{x[1]}</strong></div><i><b style={{width:`${x[2]}%`}}/></i></div>)}</div></Panel><Panel title="Compliance" kicker="Vendor controls"><div className="compliance-list"><div><CheckCircle2/><span>Business registration</span><strong>Verified</strong></div><div><CheckCircle2/><span>KRA PIN</span><strong>Verified</strong></div><div><CheckCircle2/><span>Insurance</span><strong>Valid to Mar 2027</strong></div><div><CalendarClock/><span>Safety certificate</span><strong>Renew in 42 days</strong></div></div></Panel></div>
 <Panel title="Recent jobs" kicker="Operational history"><DataTable headers={['Work order','Property / unit','Issue','Response','Cost','Rating','Status']} rows={[["WO-2183","Greenview · A-12","Low water pressure","8 min","KES 4,800","5.0","Completed"],["WO-2144","Parkline · C-18","Kitchen leak","22 min","KES 6,200","4.5","Completed"],["WO-2098","Riverside · B-04","Blocked drain","31 min","KES 3,400","4.8","Completed"]].map(r=>[...r.slice(0,6),<Status value={r[6]}/>])}/></Panel></>;
}

export function InspectionDetailPage(){
 return <><WorkspaceHeader eyebrow="Inspection · INS-2026-091" title="Routine Inspection · Greenview A-12" subtitle="Completed 06 Sep 2026 · Inspector Sarah Njeri" status="Approved" avatar="IN" actions={['Share report','Download PDF','Inspection actions']}/><Tabs items={['Summary','Checklist','Photos','Defects','Signatures','Activity']}/>
 <div className="inspection-scorecard"><div className="condition-ring"><strong>92</strong><span>Condition score</span></div><div className="condition-grid">{[['Kitchen','95','Excellent'],['Living room','94','Excellent'],['Bedroom 1','91','Good'],['Bedroom 2','93','Good'],['Bathrooms','88','Good'],['Balcony','90','Good']].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></div>)}</div></div>
 <div className="detail-grid"><Panel title="Findings" kicker="Inspector notes"><div className="finding-list"><div className="finding ok"><CheckCircle2/><p><strong>No structural concerns</strong><span>Walls, ceiling and flooring remain in good condition.</span></p></div><div className="finding warn"><Wrench/><p><strong>Bathroom sealant aging</strong><span>Preventive resealing recommended within 60 days.</span></p></div><div className="finding ok"><CheckCircle2/><p><strong>Appliances operational</strong><span>All supplied fittings and appliances tested successfully.</span></p></div></div></Panel><Panel title="Sign-off" kicker="Audit integrity"><div className="signature-box"><FileCheck2 size={24}/><strong>Digitally approved</strong><span>Sarah Njeri · Property Manager</span><small>06 Sep 2026 · 16:42 EAT · audit hash stored</small></div></Panel></div></>;
}

export function DocumentDetailPage(){
 return <><WorkspaceHeader eyebrow="Document · DOC-00981" title="Greenview Lease · A-12.pdf" subtitle="Residential lease · Mercy Wanjiku · 1.8 MB" status="Signed" avatar="PDF" actions={['Share','Download','Document actions']}/><Tabs items={['Preview','Signatures','Related records','Access log','Versions']}/>
 <div className="document-workspace"><div className="doc-preview"><div className="paper"><span>POLYIZON PROPOS</span><h2>RESIDENTIAL TENANCY AGREEMENT</h2><p>Property: Greenview Apartments, Unit A-12</p><p>Tenant: Mercy Wanjiku</p><p>Term: 01 February 2026 — 31 January 2027</p><hr/><div className="paper-lines"/><div className="signature-line"><span>Tenant signature</span><strong>Digitally signed</strong></div></div></div><aside className="doc-meta"><div><span>Document type</span><strong>Lease agreement</strong></div><div><span>Version</span><strong>v3 · Final</strong></div><div><span>Uploaded</span><strong>29 Jan 2026</strong></div><div><span>Signed</span><strong>31 Jan 2026</strong></div><div><span>Linked records</span><strong>Tenant · Unit · Lease</strong></div><div><span>Retention</span><strong>7 years</strong></div><div className="verified-doc"><ShieldCheck/><strong>Integrity verified</strong><small>Hash matches original signed version</small></div></aside></div></>;
}

export function OrganizationDetailPage(){
 return <><WorkspaceHeader eyebrow="Organization · ORG-0184" title="Alpha Properties Ltd" subtitle="Business plan · Kenya · 742 units managed" status="Active" avatar="AP" actions={['Impersonate safely','Billing','Organization actions']}/><Tabs items={['Overview','Users','Usage','Subscription','Integrations','Security','Audit','Support']}/>
 <div className="metric-grid four"><MetricCard label="MRR" value="KES 92,000" note="Business subscription" icon={Banknote} tone="success"/><MetricCard label="Units" value="742 / 1,000" note="74.2% plan utilization" icon={Building2}/><MetricCard label="Admin users" value="14" note="12 active · 2 invited" icon={Users} tone="info"/><MetricCard label="API health" value="99.98%" note="30-day availability" icon={Activity}/></div>
 <div className="detail-grid"><Panel title="Workspace health" kicker="Platform telemetry"><div className="performance-lines">{[['API success','99.98%',100],['Payment callbacks','99.7%',100],['Automation success','99.4%',99],['Storage health','100%',100]].map(x=><div key={x[0]}><div><span>{x[0]}</span><strong>{x[1]}</strong></div><i><b style={{width:`${x[2]}%`}}/></i></div>)}</div></Panel><Panel title="Security posture" kicker="Isolation & access"><div className="compliance-list"><div><ShieldCheck/><span>Organization isolation</span><strong>Enforced</strong></div><div><ShieldCheck/><span>MFA adoption</span><strong>11 / 12 admins</strong></div><div><ShieldCheck/><span>Suspicious sessions</span><strong>0</strong></div><div><Activity/><span>Audit events</span><strong>284 / 7 days</strong></div></div></Panel></div>
 <Panel title="Connected services" kicker="Integration health"><div className="integration-strip">{[['M-Pesa Daraja','Connected','99.7% callbacks'],['WhatsApp','Connected','98.9% delivery'],['Email','Connected','99.5% delivery'],['Object storage','Healthy','18.7 GB used']].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></div>)}</div></Panel></>;
}

export function MpesaReconciliationPage(){
 const tx=[['QK28P9J7HL','0712 345 678','GV-A12','Mercy Wanjiku','KES 32,000','1.4s','Matched'],['QK28R31KBC','0724 441 903','PL-C18','Alice Njeri','KES 28,000','1.9s','Matched'],['QK28T9PA22','0791 803 120','—','Unknown payer','KES 18,500','—','Review'],['QK28U7B9DM','0701 226 811','RS-B04','David Kimani','KES 42,000','1.2s','Matched']];
 return <><WorkspaceHeader eyebrow="Finance operations" title="M-Pesa Reconciliation Center" subtitle="Live C2B matching, exceptions, allocations and settlement controls" status="Healthy" avatar="MP" actions={['Import statement','Re-run matching','Reconciliation actions']}/><Tabs items={['Live feed','Exceptions','Settlements','Rules','Audit']}/>
 <div className="recon-hero"><div><span>Today processed</span><strong>KES 1.84M</strong><small>64 transactions</small></div><div><span>Auto-matched</span><strong>98.4%</strong><small>63 / 64 transactions</small></div><div><span>Median match time</span><strong>1.6 sec</strong><small>callback → ledger</small></div><div className="recon-risk"><span>Needs review</span><strong>KES 18,500</strong><small>1 unmatched payment</small></div></div>
 <div className="recon-flow"><div><PackageCheck/><span>1 · Callback received</span><strong>Validate receipt + amount</strong></div><b>→</b><div><UserRoundCog/><span>2 · Resolve account</span><strong>Reference + phone + history</strong></div><b>→</b><div><ReceiptText/><span>3 · Allocate invoice</span><strong>Oldest eligible balance</strong></div><b>→</b><div><Landmark/><span>4 · Post ledger</span><strong>Double-entry journal</strong></div></div>
 <div className="detail-grid recon-layout"><Panel title="Live payment feed" kicker="Daraja C2B"><DataTable headers={['Receipt','Phone','Reference','Resolved tenant','Amount','Match time','Status']} rows={tx.map(r=>[...r.slice(0,6),<Status value={r[6]}/>])}/></Panel><Panel title="Exception inspector" kicker="Requires attention"><div className="exception-card"><div className="exception-top"><span>QK28T9PA22</span><Status value="Review"/></div><strong>KES 18,500</strong><p>Reference did not match an active unit, lease or tenant account. Payer phone has no prior payment history.</p><div className="exception-candidates"><span>Possible action</span><button>Search tenant</button><button>Create unapplied credit</button><button>Contact payer</button></div></div></Panel></div>
 <Panel title="Settlement control" kicker="Bank vs platform"><div className="settlement-bar"><div><span>Platform C2B total</span><strong>KES 1,842,500</strong></div><div><span>Bank settlement</span><strong>KES 1,842,500</strong></div><div><span>Variance</span><strong className="good-text">KES 0</strong></div><div><span>Status</span><strong>Balanced</strong></div></div></Panel></>;
}
