import { Activity, ArrowLeft, Building2, CalendarDays, CheckCircle2, CircleDollarSign, CreditCard, FileText, KeyRound, Mail, MapPin, MessageSquareText, MoreHorizontal, Phone, ReceiptText, ShieldCheck, Sparkles, UserRound, WalletCards, Wrench } from 'lucide-react';
import { DataTable, MetricCard, Panel, Status } from '../ui';

function DetailHeader({eyebrow,title,subtitle,badge,avatar}:{eyebrow:string;title:string;subtitle:string;badge:string;avatar:string}){
 return <><div className="detail-back"><ArrowLeft size={14}/> Back to workspace</div><div className="entity-hero"><div className="entity-avatar">{avatar}</div><div className="entity-title"><span>{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p><div className="entity-meta"><Status value={badge}/><span>Last updated 8 minutes ago</span></div></div><div className="entity-actions"><button className="secondary-button"><MessageSquareText size={14}/> Message</button><button className="secondary-button"><FileText size={14}/> Document</button><button className="primary-button">Actions <MoreHorizontal size={14}/></button></div></div></>;
}

export function PropertyProfilePage(){
 return <><DetailHeader eyebrow="Asset dossier · PROP-0012" title="Greenview Apartments" subtitle="Kilimani, Nairobi · Residential · 148 units" badge="Healthy" avatar="GV"/>
 <div className="entity-tabs"><button className="active">Overview</button><button>Units</button><button>Tenants</button><button>Financials</button><button>Maintenance</button><button>Utilities</button><button>Documents</button><button>Activity</button></div>
 <div className="metric-grid four"><MetricCard label="Occupancy" value="96.6%" note="143 occupied · 5 vacant" icon={Building2} tone="success"/><MetricCard label="Monthly rent" value="KES 4.82M" note="94.8% collected" icon={WalletCards}/><MetricCard label="NOI" value="KES 3.91M" note="81.1% operating margin" icon={CircleDollarSign} tone="info"/><MetricCard label="Open work orders" value="2" note="0 urgent · SLA healthy" icon={Wrench}/></div>
 <div className="detail-grid"><Panel title="Asset performance" kicker="Trailing 6 months"><div className="performance-lines">{[['Collection rate','94.8%',95],['Occupancy','96.6%',97],['Lease renewal','88.2%',88],['Maintenance SLA','96.1%',96]].map(x=><div key={x[0]}><div><span>{x[0]}</span><strong>{x[1]}</strong></div><i><b style={{width:`${x[2]}%`}}/></i></div>)}</div></Panel><Panel title="Property intelligence" kicker="Polyizon AI"><div className="intel-card"><Sparkles size={18}/><div><strong>Strong asset, moderate rent upside</strong><p>Current occupancy is excellent. Nine leases renew in the next 90 days and comparable units indicate a potential 4–6% rent increase without materially increasing vacancy risk.</p><button>Generate rent strategy</button></div></div></Panel></div>
 <div className="detail-grid"><Panel title="Financial snapshot" kicker="September"><DataTable headers={['Metric','Current','Budget','Variance']} rows={[["Gross rent","KES 4.82M","KES 4.75M","+1.5%"],["Operating expense","KES 910K","KES 840K","+8.3%"],["NOI","KES 3.91M","KES 3.91M","0.0%"],["Owner payable","KES 3.38M","KES 3.31M","+2.1%"]]}/></Panel><Panel title="Upcoming obligations" kicker="Next 30 days"><div className="detail-feed"><div><CalendarDays/><p><strong>5 lease renewals due</strong><span>3 offers drafted · 2 not started</span></p><b>12 Sep</b></div><div><Wrench/><p><strong>Lift service contract</strong><span>Quarterly preventive maintenance</span></p><b>18 Sep</b></div><div><ReceiptText/><p><strong>Owner statement close</strong><span>2 unreconciled expense lines</span></p><b>30 Sep</b></div></div></Panel></div></>;
}

export function TenantProfilePage(){
 return <><DetailHeader eyebrow="Tenant 360 · TEN-00418" title="Mercy Wanjiku" subtitle="Greenview Apartments · Unit A-12 · Tenant since Feb 2024" badge="Good standing" avatar="MW"/>
 <div className="entity-tabs"><button className="active">Profile</button><button>Lease</button><button>Ledger</button><button>Payments</button><button>Maintenance</button><button>Messages</button><button>Documents</button><button>Activity</button></div>
 <div className="detail-grid profile-layout"><div><div className="metric-grid three"><MetricCard label="Monthly rent" value="KES 32,000" note="Due on the 5th" icon={WalletCards}/><MetricCard label="Current balance" value="KES 0" note="Paid through September" icon={CheckCircle2} tone="success"/><MetricCard label="Lease expiry" value="31 Jan 2027" note="145 days remaining" icon={KeyRound} tone="info"/></div><Panel title="Tenant timeline" kicker="Recent activity"><div className="detail-feed timeline-large"><div><CreditCard/><p><strong>Rent payment matched</strong><span>KES 32,000 · M-Pesa · QK28P9J7HL</span></p><b>2 Sep</b></div><div><MessageSquareText/><p><strong>Maintenance update sent</strong><span>Water pressure issue resolved and tenant notified</span></p><b>28 Aug</b></div><div><Wrench/><p><strong>Work order WO-2183 closed</strong><span>Kitchen water pressure · Kamau Plumbing</span></p><b>28 Aug</b></div><div><FileText/><p><strong>Lease document viewed</strong><span>Tenant portal · Android device</span></p><b>14 Aug</b></div></div></Panel></div><aside className="identity-card"><div className="identity-head"><div className="entity-avatar large">MW</div><h3>Mercy Wanjiku</h3><span>Verified tenant</span></div><div className="identity-list"><div><Phone size={14}/><span>Phone</span><strong>0712 345 678</strong></div><div><Mail size={14}/><span>Email</span><strong>mercy.w@example.com</strong></div><div><MapPin size={14}/><span>Residence</span><strong>Greenview · A-12</strong></div><div><ShieldCheck size={14}/><span>National ID</span><strong>••••••4821</strong></div></div><div className="tenant-score"><span>Tenant reliability</span><strong>96</strong><small>Excellent · 18/18 on-time payments</small></div></aside></div></>;
}

export function LeaseWorkspacePage(){
 return <><DetailHeader eyebrow="Lease workspace · LEA-2026-041" title="Greenview A-12 · Mercy Wanjiku" subtitle="Residential lease · 01 Feb 2026 — 31 Jan 2027" badge="Active" avatar="L"/>
 <div className="entity-tabs"><button className="active">Summary</button><button>Charges</button><button>Documents</button><button>Renewal</button><button>Activity</button></div>
 <div className="lease-scoreboard"><div><span>Monthly rent</span><strong>KES 32,000</strong><small>Next due 05 Oct</small></div><div><span>Deposit held</span><strong>KES 64,000</strong><small>2 months · secured</small></div><div><span>Term progress</span><strong>60%</strong><small>145 days remaining</small></div><div><span>Escalation</span><strong>5.0%</strong><small>At next renewal</small></div></div>
 <div className="detail-grid"><Panel title="Lease terms" kicker="Commercial terms"><div className="term-grid">{[['Rent frequency','Monthly'],['Due date','5th of month'],['Grace period','3 days'],['Late fee','5% after grace'],['Notice period','60 days'],['Renewal type','Offer required'],['Utilities','Tenant billed'],['Parking','1 bay included']].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div></Panel><Panel title="Renewal readiness" kicker="AI assessment"><div className="renewal-ring"><strong>92</strong><span>Likely to renew</span></div><p className="muted-copy">Excellent payment history, no unresolved complaints and current rent is 4.8% below comparable units.</p><button className="primary-button">Prepare renewal offer</button></Panel></div></>;
}

export function PaymentDetailPage(){
 return <><DetailHeader eyebrow="Payment detail · PAY-QK28P9J7HL" title="KES 32,000 received" subtitle="M-Pesa · Mercy Wanjiku · 02 Sep 2026 at 08:41" badge="Posted" avatar="P"/>
 <div className="payment-receipt"><div className="receipt-success"><CheckCircle2 size={28}/><span>Successfully reconciled</span><strong>KES 32,000</strong><small>Applied automatically in 1.4 seconds</small></div><div className="receipt-flow"><div><span>Source</span><strong>M-Pesa Paybill</strong><small>254712345678</small></div><i>→</i><div><span>Matched account</span><strong>Mercy Wanjiku</strong><small>Account GV-A12</small></div><i>→</i><div><span>Applied invoice</span><strong>INV-2026-09041</strong><small>September rent</small></div><i>→</i><div><span>Ledger</span><strong>Posted</strong><small>CR Tenant receivable</small></div></div></div>
 <div className="detail-grid"><Panel title="Transaction metadata" kicker="Gateway data"><div className="term-grid">{[['Reference','QK28P9J7HL'],['Channel','M-Pesa C2B'],['Transaction time','02 Sep · 08:41:22'],['Account reference','GV-A12'],['Payer phone','0712 345 678'],['Callback latency','620 ms']].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div></Panel><Panel title="Accounting impact" kicker="Double entry"><div className="journal"><div><span>DR</span><strong>M-Pesa clearing</strong><b>KES 32,000</b></div><div><span>CR</span><strong>Tenant receivables</strong><b>KES 32,000</b></div></div></Panel></div></>;
}

export function WorkOrderDetailPage(){
 return <><DetailHeader eyebrow="Work order · WO-2183" title="Low kitchen water pressure" subtitle="Greenview Apartments · A-12 · Reported by Mercy Wanjiku" badge="Completed" avatar="WO"/>
 <div className="workorder-progress"><div className="done"><i>1</i><span>Reported</span><small>08:41</small></div><b/><div className="done"><i>2</i><span>Assigned</span><small>08:49</small></div><b/><div className="done"><i>3</i><span>In progress</span><small>09:22</small></div><b/><div className="done"><i>4</i><span>Completed</span><small>10:14</small></div><b/><div className="done"><i>5</i><span>Tenant confirmed</span><small>10:31</small></div></div>
 <div className="detail-grid"><Panel title="Job summary" kicker="Maintenance"><div className="term-grid">{[['Priority','Medium'],['Category','Plumbing'],['Assigned vendor','Kamau Plumbing Ltd'],['Response time','8 minutes'],['Resolution time','1h 33m'],['Final cost','KES 4,800']].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div></Panel><Panel title="SLA performance" kicker="Operational quality"><div className="sla-score"><strong>100%</strong><span>Resolved within target</span><small>Target 4h · Actual 1h 33m</small></div></Panel></div><Panel title="Activity & evidence" kicker="Full audit trail"><div className="detail-feed timeline-large"><div><UserRound/><p><strong>Tenant reported issue</strong><span>“Water pressure is very low again in the kitchen.”</span></p><b>08:41</b></div><div><Activity/><p><strong>Rule triggered automatically</strong><span>Plumbing category detected · caretaker notified</span></p><b>08:42</b></div><div><Wrench/><p><strong>Vendor accepted assignment</strong><span>Kamau Plumbing Ltd · ETA 25 minutes</span></p><b>08:49</b></div><div><CheckCircle2/><p><strong>Repair completed</strong><span>Blocked inlet valve cleaned and pressure restored</span></p><b>10:14</b></div></div></Panel></>;
}
