import { AlertTriangle, ArrowUpRight, BadgeCheck, Banknote, BarChart3, BriefcaseBusiness, Building2, CalendarRange, CheckCircle2, CircleDollarSign, ClipboardList, FileCheck2, FileSearch, Gauge, Headphones, Landmark, Layers3, LockKeyhole, Mail, PackageCheck, PieChart, ReceiptText, RefreshCw, ShieldCheck, Sparkles, TrendingUp, UserCog, Users, WalletCards, Wrench } from 'lucide-react';
import { DataTable, MetricCard, Panel, Status } from '../ui';

function Header({eyebrow,title,subtitle,action}:{eyebrow:string;title:string;subtitle:string;action:string}){
 return <div className="enterprise-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div><button className="primary-button">{action}</button></div>;
}

export function BudgetingWorkspace(){
 const rows=[['Rental income','KES 14.82M','KES 14.31M','KES 14.67M','+2.5%'],['Service charge','KES 1.22M','KES 1.18M','KES 1.20M','+1.7%'],['Maintenance','KES 840K','KES 824K','KES 892K','+8.3%'],['Security','KES 410K','KES 408K','KES 410K','+0.5%'],['Utilities','KES 588K','KES 621K','KES 603K','-2.9%'],['Management fees','KES 962K','KES 951K','KES 958K','+0.7%']];
 return <><Header eyebrow="Planning & forecasting" title="Property budgeting" subtitle="Build annual operating budgets, compare actuals, forecast year-end performance and surface portfolio variance before it becomes a problem." action="Create FY2027 budget"/>
 <div className="metric-grid four"><MetricCard label="FY2026 budget" value="KES 192.4M" note="12 properties · approved plan" icon={BarChart3}/><MetricCard label="YTD actual" value="KES 126.8M" note="1.9% ahead of budget" icon={TrendingUp} tone="success"/><MetricCard label="Forecast NOI" value="KES 148.2M" note="+3.4% vs approved budget" icon={CircleDollarSign} tone="info"/><MetricCard label="Variance alerts" value="7" note="3 require manager action" icon={AlertTriangle} tone="danger"/></div>
 <div className="enterprise-grid"><Panel title="September operating plan" kicker="Budget vs actual"><DataTable headers={['Category','Budget','Actual','Forecast','Variance']} rows={rows}/></Panel><Panel title="Forecast confidence" kicker="Polyizon planning"><div className="forecast-dial"><strong>91%</strong><span>forecast confidence</span></div><div className="forecast-signals"><div><span>Occupancy</span><strong>Stable</strong></div><div><span>Rent collection</span><strong>Improving</strong></div><div><span>Maintenance cost</span><strong className="warn-text">Elevated</strong></div><div><span>Utility expense</span><strong>Normalizing</strong></div></div></Panel></div>
 <Panel title="Property variance heatmap" kicker="Management attention"><div className="variance-grid">{[['Greenview','+2.8%','good'],['Riverside','-1.1%','neutral'],['Parkline','-6.4%','bad'],['The Junction','+4.2%','good'],['Juja Homes','-3.6%','warn'],['Westfield','+1.4%','good']].map(x=><div className={`variance-cell ${x[2]}`} key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>NOI variance</small></div>)}</div></Panel></>;
}

export function ServiceChargeWorkspace(){
 const allocations=[['Cleaning','KES 840,000','15.2%','Occupied area'],['Security','KES 1,420,000','25.6%','Equal unit'],['Common power','KES 1,180,000','21.3%','Metered/common'],['Lift maintenance','KES 620,000','11.2%','Floor factor'],['Insurance','KES 760,000','13.7%','Area share'],['Management','KES 720,000','13.0%','Fixed %']];
 return <><Header eyebrow="Commercial property controls" title="Service charge & CAM" subtitle="Pool common-area costs, apply allocation rules, recover tenant shares and manage year-end true-ups with a transparent audit trail." action="Run allocation"/>
 <div className="metric-grid four"><MetricCard label="Annual pool" value="KES 5.54M" note="The Junction Offices" icon={ReceiptText}/><MetricCard label="Recovered" value="KES 4.72M" note="85.2% billed YTD" icon={WalletCards} tone="success"/><MetricCard label="Under-recovery" value="KES 312K" note="Forecast before true-up" icon={AlertTriangle} tone="danger"/><MetricCard label="Allocation rules" value="6" note="Area, floor, meter, fixed" icon={Layers3} tone="info"/></div>
 <div className="enterprise-grid"><Panel title="Cost pool" kicker="Recoverable operating cost"><DataTable headers={['Cost category','Annual cost','Share','Allocation method']} rows={allocations}/></Panel><Panel title="Recovery engine" kicker="Tenant allocation"><div className="allocation-flow"><div><Building2/><span>Property cost pool</span><strong>KES 5.54M</strong></div><i>→</i><div><PieChart/><span>Allocation rules</span><strong>6 active</strong></div><i>→</i><div><Users/><span>Tenant shares</span><strong>72 occupiers</strong></div><i>→</i><div><ReceiptText/><span>Invoices</span><strong>Auto-posted</strong></div></div></Panel></div></>;
}

export function ProcurementWorkspace(){
 const pos=[['PO-2026-184','Kamau Plumbing','Greenview','KES 128,000','Sarah Njeri','Approved'],['PO-2026-183','Elevate Kenya','The Junction','KES 342,000','Alex N.','Pending'],['PO-2026-181','SafeGuard Systems','Parkline','KES 214,500','Grace Muthoni','Approved'],['PO-2026-179','CleanCity Services','Portfolio','KES 480,000','Sarah Njeri','Ordered'],['PO-2026-176','BrightSpark Electrical','Riverside','KES 96,800','Peter Mwangi','Received']];
 return <><Header eyebrow="Spend control" title="Procurement & purchase orders" subtitle="Control purchasing from request to approval, purchase order, goods receipt, invoice match and final payment." action="New purchase request"/>
 <div className="metric-grid four"><MetricCard label="Open POs" value="24" note="KES 2.84M committed" icon={ClipboardList}/><MetricCard label="Awaiting approval" value="6" note="KES 718K pending authority" icon={FileCheck2} tone="danger"/><MetricCard label="3-way matched" value="94.6%" note="PO · receipt · vendor invoice" icon={BadgeCheck} tone="success"/><MetricCard label="Savings YTD" value="KES 1.16M" note="Negotiated vs requested spend" icon={TrendingUp} tone="info"/></div>
 <Panel title="Purchase order register" kicker="Procure-to-pay"><DataTable headers={['PO','Vendor','Scope','Amount','Requester','Status']} rows={pos.map(x=>[...x.slice(0,5),<Status value={x[5]}/>])}/></Panel>
 <div className="procure-flow"><div><ClipboardList/><span>Request</span></div><b/><div><ShieldCheck/><span>Approval</span></div><b/><div><FileCheck2/><span>PO issued</span></div><b/><div><PackageCheck/><span>Goods / service received</span></div><b/><div><ReceiptText/><span>Invoice matched</span></div><b/><div><Banknote/><span>Payment released</span></div></div></>;
}

export function RenewalComposerWorkspace(){
 return <><Header eyebrow="Lease revenue strategy" title="Renewal & rent increase composer" subtitle="Price renewals using lease history, market position, occupancy risk and tenant reliability before sending a polished offer." action="Generate offer"/>
 <div className="renewal-layout"><section className="renewal-composer"><div className="renewal-tenant"><div className="entity-avatar">MW</div><div><span>Tenant</span><strong>Mercy Wanjiku · Greenview A-12</strong><small>18/18 payments on time · 0 unresolved issues</small></div><Status value="Excellent"/></div><div className="renewal-price"><div><span>Current rent</span><strong>KES 32,000</strong></div><div><span>Market estimate</span><strong>KES 34,200</strong></div><div className="proposed"><span>Proposed renewal</span><strong>KES 33,600</strong><small>+5.0%</small></div></div><div className="renewal-slider"><div><span>Rent uplift</span><strong>5.0%</strong></div><input type="range" min="0" max="12" defaultValue="5"/></div><div className="term-grid"><div><span>New term</span><strong>12 months</strong></div><div><span>Start date</span><strong>01 Feb 2027</strong></div><div><span>Deposit top-up</span><strong>KES 3,200</strong></div><div><span>Offer expiry</span><strong>14 days</strong></div></div><div className="composer-actions"><button className="secondary-button">Preview letter</button><button className="primary-button">Send renewal offer</button></div></section><aside className="renewal-intel"><Sparkles size={20}/><span>POLYIZON PRICING INTELLIGENCE</span><h3>5% is the recommended increase.</h3><p>The unit is currently 6.4% below comparable asking rents. A 5% increase preserves a strong renewal probability while capturing most of the market gap.</p><div><span>Renewal probability</span><strong>92%</strong></div><div><span>Vacancy risk</span><strong>Low</strong></div><div><span>12-month revenue gain</span><strong>KES 19,200</strong></div></aside></div></>;
}

export function ExpenseApprovalWorkspace(){
 const approvals=[['EXP-8821','Lift motor replacement','The Junction','Elevate Kenya','KES 342,000','Capital repair','Level 2'],['EXP-8814','Water tank cleaning','Greenview','CleanCity Services','KES 68,000','Operating','Level 1'],['EXP-8809','CCTV expansion','Parkline','SafeGuard Systems','KES 214,500','Capital improvement','Level 2']];
 return <><Header eyebrow="Financial governance" title="Expense approval workspace" subtitle="Review the evidence, budget impact, vendor history, property context and approval authority before releasing spend." action="Approval policy"/>
 <div className="metric-grid four"><MetricCard label="Awaiting approval" value="9" note="KES 1.26M total" icon={FileSearch}/><MetricCard label="Within budget" value="7 / 9" note="2 require variance approval" icon={Gauge} tone="success"/><MetricCard label="High-value" value="3" note="Above KES 200K threshold" icon={AlertTriangle} tone="danger"/><MetricCard label="Median approval" value="2.4 hrs" note="-31% this quarter" icon={RefreshCw} tone="info"/></div>
 <Panel title="Approval queue" kicker="Segregation of duties"><DataTable headers={['Expense','Description','Property','Vendor','Amount','Classification','Authority']} rows={approvals}/></Panel>
 <div className="approval-dossier"><div><span>Selected request</span><strong>EXP-8821 · Lift motor replacement</strong><p>Emergency capital repair following inspection defect. Vendor quote is 4.8% below the secondary quote and the asset reserve has sufficient balance.</p></div><div className="approval-facts"><div><span>Budget remaining</span><strong>KES 614K</strong></div><div><span>Vendor rating</span><strong>4.9 / 5</strong></div><div><span>Prior spend YTD</span><strong>KES 880K</strong></div><div><span>Approval required</span><strong>Level 2</strong></div></div><div className="approval-actions"><button className="secondary-button">Request changes</button><button className="danger-outline">Reject</button><button className="primary-button">Approve KES 342,000</button></div></div></>;
}

export function SupportConsoleWorkspace(){
 return <><Header eyebrow="Platform operations" title="Support & impersonation console" subtitle="Help customer organizations safely using time-bound, reason-coded support sessions with full audit logging and restricted financial actions." action="Start support session"/>
 <div className="support-warning"><LockKeyhole size={19}/><div><strong>Privileged support mode</strong><span>Impersonation sessions are read-only by default. Financial posting, deletions and permission changes remain blocked.</span></div><Status value="Audited"/></div>
 <div className="metric-grid four"><MetricCard label="Active sessions" value="3" note="All operator-initiated" icon={Headphones}/><MetricCard label="Avg resolution" value="18 min" note="Last 30 days" icon={CheckCircle2} tone="success"/><MetricCard label="Blocked actions" value="12" note="Policy prevented risky writes" icon={ShieldCheck} tone="info"/><MetricCard label="Escalations" value="4" note="Engineering review open" icon={AlertTriangle} tone="danger"/></div>
 <div className="enterprise-grid"><Panel title="Organization lookup" kicker="Customer support"><div className="support-lookup"><div className="search-shell"><FileSearch/><input placeholder="Search company, admin email, workspace ID..."/></div>{[['Alpha Properties Ltd','org_01PX7A','Business','Healthy'],['Metro Homes','org_01PZ4K','Growth','Healthy'],['Karibu Realtors','org_01Q1AF','Starter','Payment issue']].map(x=><button key={x[1]}><div className="entity-avatar">{x[0].split(' ').map(y=>y[0]).join('').slice(0,2)}</div><div><strong>{x[0]}</strong><span>{x[1]} · {x[2]}</span></div><Status value={x[3]}/><ArrowUpRight size={14}/></button>)}</div></Panel><Panel title="Support session controls" kicker="Safety boundaries"><div className="control-list"><div><ShieldCheck/><span>Read tenant & property data</span><strong>Allowed</strong></div><div><Mail/><span>View communications</span><strong>Allowed</strong></div><div><ReceiptText/><span>Post or reverse payments</span><strong className="blocked">Blocked</strong></div><div><UserCog/><span>Change roles / permissions</span><strong className="blocked">Blocked</strong></div><div><Landmark/><span>Release owner distributions</span><strong className="blocked">Blocked</strong></div></div></Panel></div></>;
}

export function IncidentCenterWorkspace(){
 const incidents=[['INC-2026-041','M-Pesa callback delay','Payments','P2','Investigating','08:46'],['INC-2026-038','WhatsApp delivery degradation','Messaging','P3','Monitoring','07 Sep'],['INC-2026-031','Bank feed duplicate rows','Accounting','P3','Resolved','04 Sep']];
 return <><Header eyebrow="Reliability engineering" title="Platform incident center" subtitle="Track production incidents, customer impact, containment, recovery and post-incident actions from one operational cockpit." action="Declare incident"/>
 <div className="incident-banner"><div><span>P2 · ACTIVE INCIDENT</span><h2>M-Pesa callback delay</h2><p>Daraja callbacks are arriving 4–7 minutes late for a subset of transactions. Payments are safe and will reconcile automatically when callbacks land.</p></div><div className="incident-clock"><strong>36m</strong><span>elapsed</span></div></div>
 <div className="metric-grid four"><MetricCard label="Services healthy" value="11 / 12" note="Payments degraded" icon={Gauge} tone="success"/><MetricCard label="Affected payments" value="84" note="KES 1.72M pending callbacks" icon={WalletCards} tone="danger"/><MetricCard label="Customer impact" value="17 orgs" note="No payment loss detected" icon={Building2} tone="info"/><MetricCard label="Next update" value="09:30" note="Status communication scheduled" icon={CalendarRange}/></div>
 <div className="enterprise-grid"><Panel title="Incident timeline" kicker="Command log"><div className="incident-timeline">{[['08:46','Alert triggered','Callback latency exceeded 90-second threshold'],['08:51','Incident declared','Payment service moved to degraded state'],['09:02','Daraja confirmed','Provider-side callback queue delay identified'],['09:14','Mitigation active','Polling fallback matching pending transactions'],['09:22','Recovery improving','Median callback latency down to 2m 18s']].map(x=><div key={x[0]}><time>{x[0]}</time><i/><p><strong>{x[1]}</strong><span>{x[2]}</span></p></div>)}</div></Panel><Panel title="Incident register" kicker="Reliability history"><DataTable headers={['Incident','Title','Service','Severity','State','Started']} rows={incidents.map(x=>[...x.slice(0,4),<Status value={x[4]}/>,x[5]])}/></Panel></div></>;
}
