import { Activity, ArchiveRestore, BadgeCheck, Building2, Calculator, CheckCircle2, CircleDollarSign, FileCheck2, FileText, Gavel, HardHat, Landmark, LineChart, ListChecks, LockKeyhole, ReceiptText, Scale, ShieldCheck, Sparkles, UploadCloud, WalletCards } from 'lucide-react';
import { DataTable, MetricCard, Panel, Status } from '../ui';

function WorkspaceHeader({eyebrow,title,subtitle,action}:{eyebrow:string;title:string;subtitle:string;action:string}){
  return <div className="module-header enterprise-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div><button className="primary-button">{action}</button></div>;
}

export function AssetAcquisitionWorkspace(){
 const pipeline=[['Nairobi West Apartments','Acquisition','KES 312M','7.6%','Due diligence'],['Kiambu Retail Court','Acquisition','KES 184M','8.2%','Investment committee'],['Riverside Heights','Disposal','KES 426M','6.9%','Buyer negotiation']];
 return <><WorkspaceHeader eyebrow="Investment management" title="Acquisitions & disposals" subtitle="Underwrite property opportunities, manage diligence and control investment approvals." action="+ New opportunity"/>
 <div className="metric-grid four"><MetricCard label="Active opportunities" value="9" note="KES 1.84B gross value" icon={Building2}/><MetricCard label="In diligence" value="4" note="2 decision-ready" icon={ListChecks} tone="info"/><MetricCard label="Target IRR" value="18.4%" note="Weighted pipeline" icon={LineChart} tone="success"/><MetricCard label="Capital at risk" value="KES 42M" note="Deposits + transaction costs" icon={CircleDollarSign} tone="danger"/></div>
 <div className="investment-grid"><Panel title="Investment pipeline" kicker="Deal flow"><DataTable headers={['Asset','Transaction','Indicative value','Yield','Stage']} rows={pipeline.map(r=>[...r.slice(0,4),<Status value={r[4]}/>])}/></Panel><Panel title="IC decision pack" kicker="Investment committee"><div className="decision-pack"><div><span>Asset</span><strong>Nairobi West Apartments</strong></div><div><span>Purchase price</span><strong>KES 312,000,000</strong></div><div><span>Stabilized NOI</span><strong>KES 28.7M</strong></div><div><span>Going-in yield</span><strong>7.6%</strong></div><div><span>5-year levered IRR</span><strong>19.2%</strong></div><div><span>Downside IRR</span><strong>13.8%</strong></div></div><div className="intel-card compact"><Sparkles size={17}/><div><strong>Decision signal: attractive with diligence caveat</strong><p>Occupancy is strong, but deferred lift replacement could reduce year-one cash yield by ~40 bps.</p></div></div></Panel></div></>;
}

export function ValuationWorkspace(){
 return <><WorkspaceHeader eyebrow="Asset intelligence" title="Valuation & market value" subtitle="Track carrying value, market value, yield movement and valuation evidence across the portfolio." action="Run valuation"/>
 <div className="metric-grid four"><MetricCard label="Portfolio market value" value="KES 4.82B" note="+4.8% since last review" icon={Landmark}/><MetricCard label="Annual NOI" value="KES 412M" note="8.55% implied yield" icon={WalletCards} tone="success"/><MetricCard label="Unrealized gain" value="KES 284M" note="vs carrying value" icon={LineChart} tone="info"/><MetricCard label="Review due" value="3 assets" note="Within 30 days" icon={Calculator} tone="danger"/></div>
 <div className="detail-grid"><Panel title="Valuation bridge" kicker="Greenview Apartments"><div className="valuation-bridge"><div><span>Prior value</span><strong>KES 580M</strong></div><b>+</b><div><span>NOI uplift</span><strong>KES 34M</strong></div><b>−</b><div><span>Cap-rate expansion</span><strong>KES 18M</strong></div><b>=</b><div className="accent"><span>Current estimate</span><strong>KES 596M</strong></div></div></Panel><Panel title="Evidence quality" kicker="Confidence"><div className="confidence-score"><strong>91</strong><span>High confidence</span><small>3 comparable sales · 2 rent datasets · audited NOI</small></div></Panel></div>
 <Panel title="Asset valuation register" kicker="Portfolio"><DataTable headers={['Property','Carrying value','Market value','Yield','Last review','Confidence']} rows={[["Greenview Apartments","KES 552M","KES 596M","8.1%","08 Sep 2026","91%"],["Riverside Heights","KES 398M","KES 426M","7.4%","28 Aug 2026","87%"],["Parkline Residences","KES 341M","KES 365M","8.7%","18 Aug 2026","84%"],["The Junction Offices","KES 624M","KES 688M","9.0%","05 Sep 2026","93%"]]}/></Panel></>;
}

export function CapitalProjectsWorkspace(){
 const projects=[['CP-026','Greenview lift modernization','KES 18.4M','KES 17.1M','74%','On track'],['CP-031','Parkline solar retrofit','KES 9.8M','KES 7.6M','61%','On track'],['CP-034','Riverside façade repairs','KES 6.2M','KES 6.9M','88%','Over budget']];
 return <><WorkspaceHeader eyebrow="Capital expenditure" title="Capital projects" subtitle="Control major works from approved scope and tender through progress claims and asset capitalization." action="+ Capital project"/>
 <div className="metric-grid four"><MetricCard label="Active capex" value="KES 74.2M" note="Across 8 projects" icon={HardHat}/><MetricCard label="Committed" value="KES 51.6M" note="69.5% of approved budget" icon={CircleDollarSign}/><MetricCard label="Forecast variance" value="+KES 1.2M" note="1 project over budget" icon={Activity} tone="danger"/><MetricCard label="On-time" value="87.5%" note="7 of 8 projects" icon={CheckCircle2} tone="success"/></div>
 <div className="detail-grid"><Panel title="Project portfolio" kicker="Capex controls"><DataTable headers={['Project','Scope','Budget','Committed','Progress','Health']} rows={projects.map(r=>[...r.slice(0,5),<Status value={r[5]}/>])}/></Panel><Panel title="Greenview modernization" kicker="Milestones"><div className="milestone-list">{[['Design & approvals','Complete','100%'],['Supplier mobilization','Complete','100%'],['Lift 1 installation','In progress','72%'],['Lift 2 installation','Scheduled','0%'],['Commissioning','Scheduled','0%']].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><i><b style={{width:x[2]}}/></i></div>)}</div></Panel></div></>;
}

export function InsuranceClaimsWorkspace(){
 return <><WorkspaceHeader eyebrow="Risk & insurance" title="Insurance & claims" subtitle="Maintain policies, insured values, claims, evidence and insurer response across every property." action="+ Register claim"/>
 <div className="metric-grid four"><MetricCard label="Insured value" value="KES 4.66B" note="12 properties covered" icon={ShieldCheck}/><MetricCard label="Annual premium" value="KES 18.2M" note="0.39% of insured value" icon={ReceiptText}/><MetricCard label="Open claims" value="3" note="KES 8.4M claimed" icon={FileCheck2} tone="info"/><MetricCard label="Coverage gaps" value="1" note="Renewal due in 9 days" icon={LockKeyhole} tone="danger"/></div>
 <div className="detail-grid"><Panel title="Claims register" kicker="Active claims"><DataTable headers={['Claim','Property','Loss event','Claimed','Insurer','Status']} rows={[["CLM-204","Riverside Heights","Water damage","KES 3.8M","Britam","Assessment"],["CLM-198","Greenview Apartments","Lift surge damage","KES 2.1M","Jubilee","Approved"],["CLM-191","Parkline Residences","Storm damage","KES 2.5M","CIC","Documents requested"]].map(r=>[...r.slice(0,5),<Status value={r[5]}/>])}/></Panel><Panel title="Policy health" kicker="Coverage controls"><div className="compliance-stack"><div><BadgeCheck/><p><strong>Property all-risks</strong><span>12 / 12 properties covered</span></p><Status value="Compliant"/></div><div><BadgeCheck/><p><strong>Public liability</strong><span>All active properties included</span></p><Status value="Compliant"/></div><div><ShieldCheck/><p><strong>Machinery breakdown</strong><span>The Junction renewal due 17 Sep</span></p><Status value="Attention"/></div></div></Panel></div></>;
}

export function ComplianceCenter(){
 const certs=[['Fire certificate','Greenview Apartments','31 Dec 2026','Valid'],['Lift inspection','Greenview Apartments','18 Sep 2026','Renewal due'],['NEMA license','The Junction Offices','14 Feb 2027','Valid'],['Public health permit','Parkline Residences','30 Nov 2026','Valid'],['Electrical inspection','Riverside Heights','10 Sep 2026','Critical']];
 return <><WorkspaceHeader eyebrow="Regulatory control" title="Compliance center" subtitle="Track licenses, statutory inspections, certificates and property-specific obligations before they become operational risk." action="+ Add obligation"/>
 <div className="metric-grid four"><MetricCard label="Compliance score" value="94.6%" note="Portfolio-wide" icon={BadgeCheck} tone="success"/><MetricCard label="Active obligations" value="86" note="12 properties" icon={FileCheck2}/><MetricCard label="Due in 30 days" value="7" note="3 high priority" icon={ListChecks} tone="info"/><MetricCard label="Critical overdue" value="1" note="Electrical inspection" icon={ShieldCheck} tone="danger"/></div>
 <div className="detail-grid"><Panel title="Compliance register" kicker="Statutory obligations"><DataTable headers={['Obligation','Property','Expiry / due','Status']} rows={certs.map(r=>[...r.slice(0,3),<Status value={r[3]}/>])}/></Panel><Panel title="Risk concentration" kicker="By category"><div className="performance-lines">{[['Fire & life safety','98%',98],['Building systems','91%',91],['Environmental','100%',100],['Public health','96%',96],['Electrical','82%',82]].map(x=><div key={x[0]}><div><span>{x[0]}</span><strong>{x[1]}</strong></div><i><b style={{width:`${x[2]}%`}}/></i></div>)}</div></Panel></div></>;
}

export function TaxWithholdingWorkspace(){
 return <><WorkspaceHeader eyebrow="Tax operations" title="Tax & withholding" subtitle="Calculate, evidence and reconcile tax obligations arising from rent, vendors, management fees and owner distributions." action="Prepare filing"/>
 <div className="metric-grid four"><MetricCard label="Tax payable" value="KES 4.82M" note="Current filing period" icon={Scale}/><MetricCard label="Withholding captured" value="KES 1.26M" note="Vendor + professional fees" icon={ReceiptText} tone="success"/><MetricCard label="Certificates pending" value="6" note="Awaiting attachment" icon={FileText} tone="info"/><MetricCard label="Exceptions" value="2" note="Need tax review" icon={Gavel} tone="danger"/></div>
 <div className="detail-grid"><Panel title="Tax control account" kicker="September"><DataTable headers={['Tax type','Taxable base','Rate','Calculated','Reconciled']} rows={[["Withholding tax — professional","KES 8.4M","5%","KES 420K","KES 420K"],["Withholding tax — rent","KES 14.2M","10%","KES 1.42M","KES 1.39M"],["VAT on management fees","KES 6.1M","16%","KES 976K","KES 976K"],["Other statutory taxes","KES 2.0M","Variable","KES 2.00M","KES 1.98M"]]}/></Panel><Panel title="Filing readiness" kicker="Controls"><div className="close-checklist"><div><CheckCircle2 className="done"/><span>Tax base reconciled</span><strong>Complete</strong></div><div><CheckCircle2 className="done"/><span>Vendor PIN validation</span><strong>Complete</strong></div><div><FileCheck2/><span>6 certificates attached</span><strong>Pending</strong></div><div><Scale/><span>Controller review</span><strong>Pending</strong></div></div></Panel></div></>;
}

export function PolicyEngineWorkspace(){
 const rules=[['Owner payout approval','Finance','Amount > KES 500K','CFO + Director','Active'],['Deposit deduction approval','Tenancy','Deduction > KES 20K','Property manager + Finance','Active'],['Vendor invoice escalation','Procurement','Invoice > PO by 5%','Procurement lead','Active'],['High-risk access','Security','Admin role granted','Security admin','Active']];
 return <><WorkspaceHeader eyebrow="Workflow governance" title="Policy engine" subtitle="Define machine-enforced business rules so high-risk actions follow the right controls every time." action="+ New policy"/>
 <div className="policy-banner"><div><LockKeyhole size={22}/><div><span>ENFORCEMENT MODE</span><strong>Policies block non-compliant actions before posting</strong><p>Approval routing, separation of duties and evidence requirements are evaluated in real time.</p></div></div><strong>38 active policies</strong></div>
 <div className="detail-grid"><Panel title="Active controls" kicker="Policy library"><DataTable headers={['Policy','Domain','Trigger','Required control','Status']} rows={rules.map(r=>[...r.slice(0,4),<Status value={r[4]}/>])}/></Panel><Panel title="Policy simulator" kicker="Test decision"><div className="policy-sim"><span>Scenario</span><strong>Owner distribution · KES 3.38M</strong><div className="sim-flow"><i>1</i><p><strong>Amount threshold</strong><span>&gt; KES 500K</span></p><b>Passed</b></div><div className="sim-flow"><i>2</i><p><strong>Segregation of duties</strong><span>Preparer ≠ approver</span></p><b>Passed</b></div><div className="sim-flow"><i>3</i><p><strong>Required approvals</strong><span>CFO + Director</span></p><b className="waiting">1 pending</b></div></div></Panel></div></>;
}

export function MigrationCenter(){
 return <><WorkspaceHeader eyebrow="Data operations" title="Import & migration center" subtitle="Bring legacy portfolios into PropOS with mapping, validation, duplicate detection and staged cutover controls." action="New migration"/>
 <div className="metric-grid four"><MetricCard label="Rows staged" value="48,216" note="7 source files" icon={UploadCloud}/><MetricCard label="Validated" value="47,982" note="99.5% pass rate" icon={CheckCircle2} tone="success"/><MetricCard label="Exceptions" value="234" note="Needs mapping or review" icon={ArchiveRestore} tone="danger"/><MetricCard label="Cutover readiness" value="96%" note="2 blockers remain" icon={Activity} tone="info"/></div>
 <div className="migration-flow"><div className="done"><i>1</i><span>Upload</span><small>7 files</small></div><b/><div className="done"><i>2</i><span>Map fields</span><small>Complete</small></div><b/><div className="done"><i>3</i><span>Validate</span><small>99.5%</small></div><b/><div className="active"><i>4</i><span>Resolve</span><small>234 exceptions</small></div><b/><div><i>5</i><span>Dry run</span><small>Pending</small></div><b/><div><i>6</i><span>Cutover</span><small>Pending</small></div></div>
 <div className="detail-grid"><Panel title="Migration domains" kicker="Source → PropOS"><DataTable headers={['Dataset','Rows','Valid','Exceptions','Status']} rows={[["Properties","12","12","0","Ready"],["Units","742","742","0","Ready"],["Tenants","681","676","5","Review"],["Leases","704","698","6","Review"],["Payments","31,880","31,731","149","Review"],["Opening balances","4,197","4,123","74","Review"]].map(r=>[...r.slice(0,4),<Status value={r[4]}/>])}/></Panel><Panel title="Cutover guardrails" kicker="Protection"><div className="compliance-stack"><div><CheckCircle2/><p><strong>Organization isolation</strong><span>Target workspace locked</span></p><Status value="Ready"/></div><div><CheckCircle2/><p><strong>Duplicate detection</strong><span>Phone, ID, reference and unit checks enabled</span></p><Status value="Ready"/></div><div><ShieldCheck/><p><strong>Opening balances</strong><span>74 lines need controller review</span></p><Status value="Blocked"/></div></div></Panel></div></>;
}
