import { ArrowUpRight, Bot, BriefcaseBusiness, CheckCircle2, Droplets, FileText, Gauge, Mail, MessageSquareText, ReceiptText, ShieldCheck, Smartphone, Sparkles, Users, Workflow, Wrench, Zap } from 'lucide-react';
import { DataTable, MetricCard, Panel, Status } from '../ui';

function Header({title,subtitle,action}:{title:string;subtitle:string;action:string}){
  return <div className="module-header"><div><div className="eyebrow">Polyizon PropOS · Operations</div><h1>{title}</h1><p>{subtitle}</p></div><button className="primary-button">+ {action}</button></div>;
}

export function UtilitiesPage(){
  const rows=[['Water','Greenview · A-12','01947','01822','125','KES 4,375','Ready'],['Water','Greenview · A-14','00841','00796','45','KES 1,575','Ready'],['Electricity','Riverside · B-04','Prepaid','—','—','Tenant prepaid','Active'],['Water','Parkline · C-18','02314','02292','22','KES 770','Ready'],['Service charge','The Junction · OF-12','Fixed','—','—','KES 18,000','Billed']];
  return <><Header title="Utilities" subtitle="Meter readings, service charges and tenant utility billing in one place." action="Add reading"/><div className="metric-grid four"><MetricCard label="Meters" value="538" note="497 active · 41 shared" icon={Gauge}/><MetricCard label="Water usage" value="18,420 m³" note="September portfolio usage" icon={Droplets} tone="info"/><MetricCard label="Utility billed" value="KES 1.84M" note="96.7% posted to tenants" icon={ReceiptText} tone="success"/><MetricCard label="Readings due" value="23" note="Due before month-end" icon={Zap} tone="danger"/></div><Panel title="Current readings" kicker="Meter & service billing"><DataTable headers={['Utility','Unit','Current','Previous','Usage','Charge','Status']} rows={rows.map(r=>[...r.slice(0,6),<Status value={r[6]}/>])}/></Panel></>;
}

export function VendorsPage(){
  const rows=[['Kamau Plumbing Ltd','Plumbing','14 properties','124','4.7 / 5','38 min','Active'],['BrightSpark Electrical','Electrical','9 properties','88','4.6 / 5','52 min','Active'],['Elevate Kenya','Lifts','3 properties','41','4.9 / 5','1h 12m','Active'],['CleanCity Services','Cleaning','6 properties','176','4.4 / 5','2h 04m','Active'],['SafeGuard Systems','Security','8 properties','53','4.8 / 5','47 min','Active']];
  return <><Header title="Vendors" subtitle="Approved contractors, job performance, response times and maintenance spend." action="Add vendor"/><div className="metric-grid three"><MetricCard label="Approved vendors" value="34" note="Across 11 service categories" icon={BriefcaseBusiness}/><MetricCard label="Jobs completed" value="482" note="Last 90 days" icon={CheckCircle2} tone="success"/><MetricCard label="Average rating" value="4.7 / 5" note="Based on 396 completed jobs" icon={Sparkles} tone="info"/></div><Panel title="Vendor network" kicker="Service providers"><DataTable headers={['Vendor','Category','Coverage','Jobs','Rating','Avg response','Status']} rows={rows.map(r=>[...r.slice(0,6),<Status value={r[6]}/>])}/></Panel></>;
}

export function DocumentsPage(){
 const rows=[['Greenview Lease - A12.pdf','Lease','Mercy Wanjiku','Greenview · A-12','1.8 MB','08 Sep 2026','Signed'],['Owner Statement - Aug.pdf','Owner statement','John M. Kamau','3 properties','842 KB','05 Sep 2026','Ready'],['Move-out Inspection A07.pdf','Inspection','Alice Njeri','Parkline · A-07','3.2 MB','07 Sep 2026','Ready'],['Kamau Plumbing INV-882.pdf','Vendor invoice','Kamau Plumbing','WO-2183','414 KB','08 Sep 2026','Review'],['Title Deed - Greenview.pdf','Property document','John M. Kamau','Greenview','6.1 MB','19 Aug 2026','Verified']];
 return <><Header title="Documents" subtitle="Secure leases, owner records, inspection reports, invoices and property files." action="Upload document"/><div className="metric-grid three"><MetricCard label="Documents" value="2,814" note="18.7 GB workspace storage" icon={FileText}/><MetricCard label="Signed leases" value="668" note="98.1% digitally signed" icon={ShieldCheck} tone="success"/><MetricCard label="Awaiting review" value="17" note="Invoices and inspection files" icon={ReceiptText} tone="danger"/></div><Panel title="Document library" kicker="Secure workspace"><DataTable headers={['File','Type','Related to','Scope','Size','Uploaded','Status']} rows={rows.map(r=>[...r.slice(0,6),<Status value={r[6]}/>])}/></Panel></>;
}

export function AutomationsPage(){
 const rules=[['Rent reminder · 3 days before due','Rent schedule','WhatsApp + SMS','681 tenants','Active'],['Overdue escalation · Day 7','Invoice overdue','SMS + task + manager alert','24 matches','Active'],['Lease renewal · 60 days','Lease expiry','Email + task','12 upcoming','Active'],['Emergency maintenance','Priority = urgent','Manager + caretaker + vendor','4 this month','Active'],['Owner statement ready','Month close','Email owner + portal notice','18 owners','Active'],['Move-in welcome journey','Lease activated','WhatsApp + portal checklist','9 this month','Paused']];
 return <><Header title="Automations" subtitle="Turn recurring property operations into reliable event-driven workflows." action="Create workflow"/><div className="metric-grid four"><MetricCard label="Active workflows" value="14" note="Across finance and operations" icon={Workflow}/><MetricCard label="Runs this month" value="3,842" note="99.4% successful" icon={Zap} tone="success"/><MetricCard label="Messages automated" value="2,911" note="WhatsApp, SMS and email" icon={MessageSquareText} tone="info"/><MetricCard label="Tasks prevented" value="184 hrs" note="Estimated staff time saved" icon={Bot} tone="primary"/></div><Panel title="Workflow library" kicker="Automation engine"><DataTable headers={['Workflow','Trigger','Actions','Reach','Status']} rows={rules.map(r=>[...r.slice(0,4),<Status value={r[4]}/>])}/></Panel><div className="automation-builder"><div><Workflow size={24}/><span>WHEN</span><strong>Invoice becomes overdue by 3 days</strong></div><ArrowUpRight size={18}/><div><ShieldCheck size={24}/><span>IF</span><strong>Outstanding balance is greater than KES 0</strong></div><ArrowUpRight size={18}/><div><Smartphone size={24}/><span>THEN</span><strong>Send WhatsApp + create collection task</strong></div></div></>;
}

export function PortalsPage(){
 return <><Header title="Portals" subtitle="Self-service experiences for tenants and property owners, controlled from one workspace." action="Invite portal user"/><div className="portal-showcase"><article className="portal-preview tenant-preview"><div className="portal-top"><div><span>Tenant portal</span><strong>Hello, Mercy 👋</strong></div><Smartphone size={22}/></div><div className="portal-balance"><span>September rent</span><strong>KES 32,000</strong><em>PAID</em></div><div className="portal-actions"><button>Pay rent</button><button>Receipt</button><button>Report issue</button><button>My lease</button></div></article><article className="portal-preview owner-preview"><div className="portal-top"><div><span>Owner portal</span><strong>John M. Kamau</strong></div><Users size={22}/></div><div className="owner-numbers"><div><span>Properties</span><strong>3</strong></div><div><span>Occupancy</span><strong>95%</strong></div><div><span>Net payable</span><strong>KES 4.96M</strong></div></div><div className="portal-actions"><button>Statements</button><button>Expenses</button><button>Maintenance</button><button>Documents</button></div></article></div><div className="metric-grid three"><MetricCard label="Portal users" value="612" note="574 tenants · 38 owners" icon={Users}/><MetricCard label="Digital payments" value="73.1%" note="Payments initiated through self-service" icon={Smartphone} tone="success"/><MetricCard label="Self-service requests" value="86%" note="Maintenance and documents without staff" icon={Mail} tone="info"/></div></>;
}
