import { useState } from 'react';
import { AlertTriangle, ArrowUpRight, BarChart3, Bot, CalendarDays, CheckCircle2, ClipboardCheck, Landmark, MessageSquareText, PieChart, Send, Sparkles, WalletCards, Wrench } from 'lucide-react';
import { conversations, inspections, workOrders } from '../data';
import { DataTable, MetricCard, ModuleHeader, Panel, Status } from '../ui';

export function MaintenancePage({onAdd}:{onAdd:()=>void}){
  return <><ModuleHeader page="Maintenance" onAdd={onAdd}/><div className="metric-grid four"><MetricCard label="Open work orders" value="31" note="Across 9 properties" icon={Wrench}/><MetricCard label="Urgent" value="4" note="Average response 28 min" icon={AlertTriangle} tone="danger"/><MetricCard label="SLA compliance" value="92.4%" note="+3.1% this month" icon={CheckCircle2} tone="success"/><MetricCard label="Monthly spend" value="KES 824K" note="12.4% above budget" icon={WalletCards} tone="info"/></div><Panel title="Work order board" kicker="Live maintenance"><DataTable headers={['Work order','Issue','Location','Priority','Assigned to','Age','Status']} rows={workOrders.map(w=>[...w.slice(0,6),<Status value={w[6]}/>])}/></Panel></>;
}

export function InspectionsPage({onAdd}:{onAdd:()=>void}){
  return <><ModuleHeader page="Inspections" onAdd={onAdd}/><div className="metric-grid three"><MetricCard label="This week" value="18" note="12 routine · 4 move-in · 2 move-out" icon={ClipboardCheck}/><MetricCard label="Completed" value="11" note="61% of weekly schedule" icon={CheckCircle2} tone="success"/><MetricCard label="Awaiting review" value="4" note="3 have flagged defects" icon={AlertTriangle} tone="danger"/></div><Panel title="Inspection schedule" kicker="Property condition"><DataTable headers={['Inspection','Type','Property / unit','Schedule','Inspector','Status']} rows={inspections.map(i=>[...i.slice(0,5),<Status value={i[5]}/>])}/></Panel></>;
}

export function InboxPage({onAdd}:{onAdd:()=>void}){
  const [selected,setSelected]=useState(0);
  return <><ModuleHeader page="Inbox" onAdd={onAdd}/><div className="inbox-shell"><div className="conversation-list">{conversations.map((c,i)=><button className={`conversation ${i===selected?'active':''}`} onClick={()=>setSelected(i)} key={c.name}><div className="tenant-avatar">{c.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{c.name}</strong><span>{c.meta} · {c.channel}</span><p>{c.preview}</p></div><div><small>{c.time}</small>{c.unread&&<i/>}</div></button>)}</div><div className="chat-panel"><div className="chat-head"><div className="tenant-avatar">{conversations[selected].name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{conversations[selected].name}</strong><span>{conversations[selected].meta} · {conversations[selected].channel}</span></div></div><div className="chat-body"><div className="bubble incoming">Hello, the water pressure is very low again in the kitchen.<span>08:41</span></div><div className="bubble outgoing">Thanks for reporting this. I’ve created a maintenance request and alerted the property team.<span>08:42</span></div><div className="system-message"><Wrench size={14}/> WO-2183 created automatically · Priority: Medium</div><div className="bubble incoming">Okay, thank you. Please let me know when someone is coming.<span>08:43</span></div></div><div className="composer"><input placeholder="Write a message…"/><button><Send size={16}/></button></div></div></div></>;
}

export function ReportsPage({onAdd}:{onAdd:()=>void}){
  const cards=[['Rent roll','Current tenant, unit, rent and balance register',BarChart3],['Owner statements','Income, expenses, fees and owner payable',Landmark],['Income statement','Portfolio revenue and operating expenses',BarChart3],['Arrears aging','Outstanding balances grouped by age',AlertTriangle],['Occupancy report','Vacancy and occupancy performance',PieChart],['Maintenance cost','Work-order cost by property and vendor',Wrench],['Lease expirations','Upcoming renewals and move-outs',CalendarDays],['Collection report','Payment methods and collection rate',WalletCards]];
  return <><ModuleHeader page="Reports" onAdd={onAdd}/><div className="report-grid">{cards.map(([title,desc,Icon]:any)=><button className="report-card" key={title}><div className="report-icon"><Icon size={19}/></div><div><strong>{title}</strong><span>{desc}</span></div><ArrowUpRight size={17}/></button>)}</div><div className="panel insight-panel"><div><span className="panel-kicker">Executive intelligence</span><h2>September portfolio summary</h2><p>Occupancy improved while maintenance spend rose above budget. Collection performance remains strong, but 6 high-value arrears cases account for 54% of overdue rent.</p></div><div className="insight-score"><strong>84</strong><span>Portfolio health</span></div></div></>;
}

export function AIAssistantPage(){
  const prompts=['Which properties have the highest arrears?','Show leases expiring in the next 60 days','Why did maintenance spend increase?','Draft an owner summary for September'];
  const [query,setQuery]=useState('');
  const [messages,setMessages]=useState<{role:string;text:string}[]>([{role:'ai',text:'Good morning, Alex. I can analyze rent, leases, properties, maintenance, owners and tenant activity. What would you like to know?'}]);
  function send(){if(!query.trim())return;setMessages(m=>[...m,{role:'user',text:query},{role:'ai',text:'Greenview Apartments and Parkline Residences currently account for the largest overdue balances. Greenview has KES 624,000 outstanding across 8 tenants, while Parkline has KES 418,000 across 6. I can turn this into a collection workflow.'}]);setQuery('')}
  return <div className="ai-page"><div className="ai-hero"><div className="ai-orb"><Bot size={28}/></div><span>POLYIZON INTELLIGENCE</span><h1>Your portfolio, conversationally.</h1><p>Ask questions, uncover risks and turn insight into action.</p></div><div className="prompt-grid">{prompts.map(p=><button key={p} onClick={()=>setQuery(p)}>{p}<ArrowUpRight size={15}/></button>)}</div><div className="ai-chat">{messages.map((m,i)=><div className={`ai-message ${m.role}`} key={i}>{m.role==='ai'&&<div className="ai-mini"><Sparkles size={14}/></div>}<p>{m.text}</p></div>)}<div className="ai-input"><Sparkles size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask Polyizon AI about your portfolio…"/><button onClick={send}><Send size={16}/></button></div></div></div>;
}

export function TeamPage(){
  const team=[['Alex N.','Company Admin','All properties','Active'],['Sarah Njeri','Property Manager','Greenview + 3','Active'],['Peter Mwangi','Caretaker','Greenview','Active'],['Grace Muthoni','Accountant','All properties','Active'],['Miriam Wambui','Property Manager','Parkline + 2','Active']];
  return <><div className="module-header"><div><div className="eyebrow">Administration</div><h1>Team & roles</h1><p>Control who can access properties, finance, tenants and operational data.</p></div><button className="primary-button">+ Invite member</button></div><div className="metric-grid three"><MetricCard label="Team members" value="14" note="12 active · 2 invited" icon={MessageSquareText}/><MetricCard label="Roles" value="6" note="Granular permission profiles" icon={CheckCircle2} tone="success"/><MetricCard label="Audit events" value="284" note="Last 7 days" icon={BarChart3} tone="info"/></div><Panel title="Workspace team" kicker="Access control"><DataTable headers={['Member','Role','Scope','Status']} rows={team.map(t=>[...t.slice(0,3),<Status value={t[3]}/>])}/></Panel></>;
}

export function SettingsPage(){
  const settings=[['Workspace profile','Company identity, logo, address, timezone and currency'],['Payments','M-Pesa Paybill, Till, banks, cards and reconciliation'],['Accounting','Chart of accounts, fees, tax and owner statements'],['Messaging','WhatsApp, SMS, email and notification templates'],['Automations','Rent reminders, lease renewals, maintenance and collections'],['Security','MFA, session policy, audit logs and trusted devices'],['Roles & permissions','Granular access by role, property and module'],['Integrations','M-Pesa Daraja, banks, storage, maps and external APIs']];
  return <><div className="module-header"><div><div className="eyebrow">Administration</div><h1>Settings</h1><p>Configure workspace identity, finance, integrations and automation.</p></div><button className="primary-button">Save changes</button></div><div className="settings-grid">{settings.map(([title,desc])=><button className="settings-card" key={title}><div><strong>{title}</strong><span>{desc}</span></div><ArrowUpRight size={17}/></button>)}</div></>;
}
