import { useState } from 'react';
import { AlertTriangle, ArrowUpRight, BarChart3, Bot, CalendarDays, CheckCircle2, ClipboardCheck, Clock3, Landmark, MessageSquareText, PieChart, Send, Sparkles, TimerReset, WalletCards, Wrench } from 'lucide-react';
import { conversations, inspections, workOrders } from '../data';
import { DataTable, MetricCard, ModuleHeader, Panel, Status } from '../ui';

export function MaintenancePage({onAdd}:{onAdd:()=>void}){
  const lanes=[['New',6],['Assigned',9],['In progress',11],['Awaiting approval',5]];
  return <><ModuleHeader page="Maintenance" onAdd={onAdd}/><div className="maintenance-hero"><div><span>OPERATIONS CONTROL</span><strong>31 open work orders</strong><p>4 urgent issues need attention. Average first response is 28 minutes.</p></div><div className="maintenance-sla"><span>SLA compliance</span><strong>92.4%</strong><small>+3.1 pts this month</small></div></div><div className="maintenance-lanes">{lanes.map((l,i)=><article key={l[0]}><div><span>0{i+1}</span><strong>{l[0]}</strong></div><b>{l[1]}</b><small>{i===0?'2 urgent':i===1?'4 vendor assigned':i===2?'3 overdue':'KES 84K pending'}</small></article>)}</div><div className="split-grid"><Panel title="Priority dispatch" kicker="Live maintenance"><DataTable headers={['Work order','Issue','Location','Priority','Assigned to','Age','Status']} rows={workOrders.map(w=>[...w.slice(0,6),<Status value={w[6]}/>])}/></Panel><Panel title="Service pulse" kicker="Today"><div className="service-pulse"><div><span>Avg response</span><strong>28m</strong><TimerReset size={17}/></div><div><span>Avg resolution</span><strong>6.2h</strong><Clock3 size={17}/></div><div><span>Vendor acceptance</span><strong>96%</strong><CheckCircle2 size={17}/></div><div><span>Spend today</span><strong>KES 84K</strong><WalletCards size={17}/></div></div></Panel></div></>;
}

export function InspectionsPage({onAdd}:{onAdd:()=>void}){
  return <><ModuleHeader page="Inspections" onAdd={onAdd}/><div className="inspection-overview"><div className="inspection-score"><span>PROPERTY CONDITION SCORE</span><strong>88</strong><small>Across 12 active properties</small></div><div className="inspection-breakdown"><div><span>Scheduled</span><strong>18</strong></div><div><span>Completed</span><strong>11</strong></div><div><span>Flagged defects</span><strong>7</strong></div><div><span>Awaiting review</span><strong>4</strong></div></div></div><Panel title="Inspection schedule" kicker="Condition & compliance"><DataTable headers={['Inspection','Type','Property / unit','Schedule','Inspector','Status']} rows={inspections.map(i=>[...i.slice(0,5),<Status value={i[5]}/>])}/></>;
}

export function InboxPage({onAdd}:{onAdd:()=>void}){
  const [selected,setSelected]=useState(0);
  return <><ModuleHeader page="Inbox" onAdd={onAdd}/><div className="inbox-premium-head"><div><span>UNIFIED COMMUNICATIONS</span><strong>4 conversations need attention</strong></div><div><button className="channel-pill active">All</button><button className="channel-pill">WhatsApp</button><button className="channel-pill">SMS</button><button className="channel-pill">Email</button></div></div><div className="inbox-shell premium-inbox"><div className="conversation-list"><div className="conversation-search">Search conversations…</div>{conversations.map((c,i)=><button className={`conversation ${i===selected?'active':''}`} onClick={()=>setSelected(i)} key={c.name}><div className="tenant-avatar">{c.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{c.name}</strong><span>{c.meta} · {c.channel}</span><p>{c.preview}</p></div><div><small>{c.time}</small>{c.unread&&<i/>}</div></button>)}</div><div className="chat-panel"><div className="chat-head"><div className="tenant-avatar">{conversations[selected].name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{conversations[selected].name}</strong><span>{conversations[selected].meta} · {conversations[selected].channel}</span></div><button className="context-button">Open tenant profile <ArrowUpRight size={13}/></button></div><div className="chat-body"><div className="chat-day">Today</div><div className="bubble incoming">Hello, the water pressure is very low again in the kitchen.<span>08:41</span></div><div className="bubble outgoing">Thanks for reporting this. I’ve created a maintenance request and alerted the property team.<span>08:42</span></div><div className="system-message"><Wrench size={14}/> WO-2183 created automatically · Priority: Medium</div><div className="bubble incoming">Okay, thank you. Please let me know when someone is coming.<span>08:43</span></div></div><div className="composer"><input placeholder="Write a message…"/><button><Send size={16}/></button></div></div></div></>;
}

export function ReportsPage({onAdd}:{onAdd:()=>void}){
  const cards=[['Rent roll','Current tenant, unit, rent and balance register',BarChart3,'Updated 8m ago'],['Owner statements','Income, expenses, fees and owner payable',Landmark,'14 ready'],['Income statement','Portfolio revenue and operating expenses',BarChart3,'September'],['Arrears aging','Outstanding balances grouped by age',AlertTriangle,'KES 1.86M'],['Occupancy report','Vacancy and occupancy performance',PieChart,'91.8%'],['Maintenance cost','Work-order cost by property and vendor',Wrench,'KES 824K'],['Lease expirations','Upcoming renewals and move-outs',CalendarDays,'12 upcoming'],['Collection report','Payment methods and collection rate',WalletCards,'87.5%']];
  return <><ModuleHeader page="Reports" onAdd={onAdd}/><div className="reports-hero"><div><span>EXECUTIVE REPORTING</span><strong>Portfolio intelligence center</strong><p>Financial, operational and owner-ready reporting from one verified data layer.</p></div><div className="report-health"><span>Data freshness</span><strong>Live</strong><small>Last sync 2 min ago</small></div></div><div className="report-grid premium-report-grid">{cards.map(([title,desc,Icon,meta]:any)=><button className="report-card" key={title}><div className="report-icon"><Icon size={18}/></div><div><strong>{title}</strong><span>{desc}</span><small>{meta}</small></div><ArrowUpRight size={16}/></button>)}</div><div className="panel insight-panel premium-insight"><div><span className="panel-kicker">Polyizon Intelligence</span><h2>September executive summary</h2><p>Occupancy improved while maintenance spend rose above budget. Collection performance remains strong, but six high-value arrears cases now account for more than half of aged debt.</p><button className="section-action">Generate board summary <ArrowUpRight size={13}/></button></div><div className="insight-score"><strong>84</strong><span>Portfolio health</span></div></div></>;
}

export function AIAssistantPage(){
  const prompts=['Which properties have the highest arrears?','Show leases expiring in the next 60 days','Why did maintenance spend increase?','Draft an owner summary for September'];
  const [query,setQuery]=useState('');
  const [messages,setMessages]=useState<{role:string;text:string}[]>([{role:'ai',text:'Good morning, Alex. I can analyze rent, leases, properties, maintenance, owners and tenant activity. What would you like to know?'}]);
  function send(){if(!query.trim())return;setMessages(m=>[...m,{role:'user',text:query},{role:'ai',text:'Greenview Apartments and Parkline Residences currently account for the largest overdue balances. Greenview has KES 624,000 outstanding across 8 tenants, while Parkline has KES 418,000 across 6. I can turn this into a collection workflow.'}]);setQuery('')}
  return <div className="ai-page premium-ai"><div className="ai-hero"><div className="ai-orb"><Bot size={28}/></div><span>POLYIZON INTELLIGENCE</span><h1>Ask the portfolio.</h1><p>Analyze performance, surface risk, draft communications and launch workflows from one conversation.</p></div><div className="ai-context-strip"><span>Context</span><strong>Alpha Properties · 742 units · September 2026</strong><em>Live data</em></div><div className="prompt-grid">{prompts.map(p=><button key={p} onClick={()=>setQuery(p)}>{p}<ArrowUpRight size={15}/></button>)}</div><div className="ai-chat">{messages.map((m,i)=><div className={`ai-message ${m.role}`} key={i}>{m.role==='ai'&&<div className="ai-mini"><Sparkles size={14}/></div>}<p>{m.text}</p></div>)}<div className="ai-input"><Sparkles size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask Polyizon AI about your portfolio…"/><button onClick={send}><Send size={16}/></button></div></div></div>;
}

export function TeamPage(){
  const team=[['Alex N.','Company Admin','All properties','Active'],['Sarah Njeri','Property Manager','Greenview + 3','Active'],['Peter Mwangi','Caretaker','Greenview','Active'],['Grace Muthoni','Accountant','All properties','Active'],['Miriam Wambui','Property Manager','Parkline + 2','Active']];
  return <><div className="module-header"><div><div className="eyebrow">Administration</div><h1>Team & roles</h1><p>Granular people, access and property-level permissions.</p></div><button className="primary-button">+ Invite member</button></div><div className="access-hero"><div><span>ACCESS POSTURE</span><strong>14 workspace members</strong><p>12 active, 2 invited. MFA enabled for all privileged roles.</p></div><div><span>Security score</span><strong>96</strong><small>Strong</small></div></div><Panel title="Workspace team" kicker="Access control"><DataTable headers={['Member','Role','Scope','Status']} rows={team.map(t=>[...t.slice(0,3),<Status value={t[3]}/>])}/></>;
}

export function SettingsPage(){
  const settings=[['Workspace profile','Company identity, logo, address, timezone and currency'],['Payments','M-Pesa Paybill, Till, banks, cards and reconciliation'],['Accounting','Chart of accounts, fees, tax and owner statements'],['Messaging','WhatsApp, SMS, email and notification templates'],['Automations','Rent reminders, lease renewals, maintenance and collections'],['Security','MFA, session policy, audit logs and trusted devices'],['Roles & permissions','Granular access by role, property and module'],['Integrations','M-Pesa Daraja, banks, storage, maps and external APIs']];
  return <><div className="module-header"><div><div className="eyebrow">Administration</div><h1>Settings</h1><p>Configure the operational foundation of this workspace.</p></div><button className="primary-button">Save changes</button></div><div className="settings-intro"><div><span>WORKSPACE</span><strong>Alpha Properties Ltd</strong><small>Nairobi · KES · Africa/Nairobi</small></div><div className="settings-status"><span><i/> Payments connected</span><span><i/> Messaging active</span><span><i/> MFA enforced</span></div></div><div className="settings-grid premium-settings-grid">{settings.map(([title,desc],i)=><button className="settings-card" key={title}><div className="settings-index">0{i+1}</div><div><strong>{title}</strong><span>{desc}</span></div><ArrowUpRight size={16}/></button>)}</div></>;
}
