import { Activity, ArrowUpRight, Building2, CreditCard, Database, ServerCog, ShieldCheck, TrendingUp, Users, WalletCards } from 'lucide-react';
import { DataTable, MetricCard, Status } from '../ui';

const organizations = [
  ['Alpha Properties Ltd','742 units','Business','KES 92,000/mo','Active','08 Sep 2026'],
  ['Metro Homes','318 units','Growth','KES 42,000/mo','Active','08 Sep 2026'],
  ['Karibu Realtors','83 units','Starter','KES 14,000/mo','Trial','07 Sep 2026'],
  ['Apex Property Group','1,284 units','Enterprise','Custom','Active','07 Sep 2026'],
  ['Juja Student Homes','206 units','Growth','KES 42,000/mo','Active','06 Sep 2026'],
];

export function OperatorPage({onAdd}:{onAdd:()=>void}){
  return <><div className="operator-hero"><div><div className="eyebrow">Polyizon platform operator</div><h1>PropOS Control Plane</h1><p>Operate the SaaS business, onboard companies, observe platform health and understand usage across every workspace.</p><div className="operator-actions"><button className="primary-button" onClick={onAdd}>+ Onboard company</button><button className="secondary-button">View platform activity</button></div></div><div className="operator-mrr"><span>PLATFORM MRR</span><strong>KES 3.84M</strong><small>+8.7% month over month</small><div className="operator-sparkline"><i/><i/><i/><i/><i/><i/><i/><i/></div></div></div>
  <div className="metric-grid four"><MetricCard label="Organizations" value="184" note="173 active · 11 trial" icon={Building2}/><MetricCard label="Units managed" value="18,420" note="+624 in the last 30 days" icon={Activity} tone="success"/><MetricCard label="Admin users" value="612" note="Across all organizations" icon={Users} tone="info"/><MetricCard label="Net retention" value="108.4%" note="Expansion exceeds churn" icon={TrendingUp} tone="primary"/></div>
  <div className="operator-grid"><article className="panel"><div className="panel-head"><div><span className="panel-kicker">SaaS organizations</span><h2>Customer workspaces</h2></div><button className="section-action">View all <ArrowUpRight size={13}/></button></div><DataTable headers={['Organization','Usage','Plan','Subscription','Status','Last activity']} rows={organizations.map(o=>[...o.slice(0,4),<Status value={o[4]}/>,o[5]])}/></article><article className="panel"><div className="panel-head"><div><span className="panel-kicker">Platform health</span><h2>Infrastructure status</h2></div><Status value="Healthy"/></div><div className="platform-health-grid"><div><ServerCog size={17}/><span>API cluster</span><strong>99.99%</strong><small>42 ms p95</small></div><div><Database size={17}/><span>Database</span><strong>Healthy</strong><small>14% load</small></div><div><CreditCard size={17}/><span>M-Pesa callbacks</span><strong>99.97%</strong><small>12.8K today</small></div><div><Activity size={17}/><span>Background jobs</span><strong>Healthy</strong><small>3,842 runs</small></div></div></article></div>
  <div className="operator-bottom"><article className="panel"><div className="panel-head"><div><span className="panel-kicker">Commercial intelligence</span><h2>Plan distribution</h2></div></div><div className="plan-distribution"><div><span>Starter</span><strong>48</strong><i style={{width:'26%'}}/></div><div><span>Growth</span><strong>76</strong><i style={{width:'41%'}}/></div><div><span>Business</span><strong>44</strong><i style={{width:'24%'}}/></div><div><span>Enterprise</span><strong>16</strong><i style={{width:'9%'}}/></div></div></article><article className="panel"><div className="panel-head"><div><span className="panel-kicker">Risk & trust</span><h2>Operator safeguards</h2></div></div><div className="operator-controls"><div><ShieldCheck size={17}/><div><strong>Tenant isolation</strong><span>All workspace-scoped queries enforced</span></div><em>Active</em></div><div><WalletCards size={17}/><div><strong>Payment monitoring</strong><span>7 unmatched callbacks across platform</span></div><em>Review</em></div><div><Activity size={17}/><div><strong>Audit trail</strong><span>2,941 admin events in last 24h</span></div><em>Healthy</em></div></div></article></div></>;
}
