import { AlertTriangle, ArrowUpRight, Banknote, BarChart3, BedDouble, Building2, CalendarClock, CheckCircle2, CircleDollarSign, CircleGauge, CreditCard, Home, KeyRound, Landmark, Layers3, MapPin, MoreHorizontal, ReceiptText, Sparkles, Users, WalletCards } from 'lucide-react';
import { arrears, leases, owners, payments, properties, tenants, units } from '../data';
import { DataTable, MetricCard, ModuleHeader, Panel, Status } from '../ui';

type Navigate=(page:string)=>void;
function SectionAction({label,onClick}:{label:string;onClick?:()=>void}){return <button className="section-action" onClick={onClick}>{label}<ArrowUpRight size={13}/></button>}

export function PropertiesPage({onAdd,onNavigate}:{onAdd:()=>void;onNavigate?:Navigate}){
  return <><ModuleHeader page="Properties" onAdd={onAdd}/><div className="asset-hero"><div><span>PORTFOLIO VALUE LAYER</span><strong>12 assets · 742 units</strong><p>Residential, commercial and mixed-use properties with live occupancy, income and operational health.</p></div><div className="asset-hero-stats"><div><span>Occupancy</span><strong>91.8%</strong></div><div><span>Monthly income</span><strong>KES 18.4M</strong></div><div><span>NOI margin</span><strong>84.2%</strong></div></div></div><div className="property-grid premium-property-grid">{properties.map((p,i)=><article className="property-card premium-property interactive-card" key={p.name} tabIndex={0} onClick={()=>onNavigate?.('Property Profile')} onKeyDown={e=>e.key==='Enter'&&onNavigate?.('Property Profile')}><div className={`property-cover cover-${i%4}`}><div className="property-pattern"/><div className="property-cover-top"><span className="asset-code">PROP-{String(i+1).padStart(3,'0')}</span><Status value={p.status}/></div><div className="property-cover-bottom"><div><MapPin size={12}/><span>{p.location}</span></div><button onClick={e=>e.stopPropagation()}><MoreHorizontal size={15}/></button></div></div><div className="property-body"><div className="property-title"><div><h3>{p.name}</h3><span>{p.type} · Manager {p.manager}</span></div><button className="open-asset"><ArrowUpRight size={15}/></button></div><div className="asset-health-line"><div style={{width:`${Math.min(100,p.occupancy)}%`}}/><span>{p.occupancy}% occupied</span></div><div className="property-stats"><div><span>Units</span><strong>{p.units}</strong></div><div><span>Income</span><strong>{p.income}</strong></div><div><span>Health</span><strong>{i===2?'78':'94'}</strong></div></div></div></article>)}</div></>;
}

export function UnitsPage({onAdd,onNavigate}:{onAdd:()=>void;onNavigate?:Navigate}){
  const featured=units.slice(0,8);
  return <><ModuleHeader page="Units" onAdd={onAdd}/><div className="metric-grid four"><MetricCard label="Total units" value="742" note="Across 12 properties" icon={Layers3}/><MetricCard label="Occupied" value="681" note="91.8% occupancy" icon={Home} tone="success"/><MetricCard label="Vacant" value="42" note="5.7% of portfolio" icon={BedDouble} tone="info"/><MetricCard label="Maintenance" value="19" note="7 overdue work orders" icon={AlertTriangle} tone="danger"/></div><div className="unit-board"><div className="unit-board-head"><div><span>LIVE UNIT MAP</span><strong>Greenview Apartments · Block A</strong></div><div className="unit-legend"><span><i className="occupied"/>Occupied</span><span><i className="vacant"/>Vacant</span><span><i className="maintenance"/>Maintenance</span></div></div><div className="unit-tiles">{featured.map((u,i)=><article className={`unit-tile ${String(u.status).toLowerCase()} interactive-card`} key={u.unit} tabIndex={0} onClick={()=>onNavigate?.('Unit Profile')} onKeyDown={e=>e.key==='Enter'&&onNavigate?.('Unit Profile')}><div><span>{u.unit}</span><Status value={u.status}/></div><strong>{u.type}</strong><small>{u.rent} · {u.tenant}</small><div className="unit-tile-foot"><span>Floor {Math.floor(i/4)+1}</span><ArrowUpRight size={13}/></div></article>)}</div></div><Panel title="Unit register" kicker="Complete inventory"><DataTable headers={['Unit','Property','Type','Rent','Tenant','Status']} rows={units.map(u=>[u.unit,u.property,u.type,u.rent,u.tenant,<Status value={u.status}/>])} onRowClick={()=>onNavigate?.('Unit Profile')}/></Panel></>;
}

export function OwnersPage({onAdd,onNavigate}:{onAdd:()=>void;onNavigate?:Navigate}){
  return <><ModuleHeader page="Owners" onAdd={onAdd}/><div className="owner-summary"><div className="owner-summary-main"><div className="owner-summary-icon"><Landmark size={22}/></div><div><span>September distributions</span><strong>KES 8.42M</strong><p>14 of 18 owner statements are ready for release after reconciliation.</p></div></div><div className="owner-summary-mini"><div><span>Gross collected</span><strong>KES 12.96M</strong></div><div><span>Management fees</span><strong>KES 648K</strong></div><div><span>Expenses held</span><strong>KES 1.22M</strong></div></div></div><Panel title="Owner portfolio" kicker="Ownership & distributions"><DataTable headers={['Owner','Portfolio','Units','Gross rent','Net payable','Occupancy']} rows={owners} onRowClick={()=>onNavigate?.('Owner Profile')}/></Panel></>;
}

export function TenantsPage({onAdd,onNavigate}:{onAdd:()=>void;onNavigate?:Navigate}){
  const spotlight=tenants[0];
  return <><ModuleHeader page="Tenants" onAdd={onAdd}/><div className="tenant-layout"><div className="tenant-spotlight interactive-card" tabIndex={0} onClick={()=>onNavigate?.('Tenant 360')} onKeyDown={e=>e.key==='Enter'&&onNavigate?.('Tenant 360')}><div className="spotlight-top"><div className="profile-orb">MW</div><div><span>TENANT SPOTLIGHT</span><strong>{spotlight?.[0] || 'Mercy Wanjiku'}</strong><small>Greenview Apartments · A-12</small></div><Status value="Good standing"/></div><div className="spotlight-grid"><div><span>Monthly rent</span><strong>KES 32,000</strong></div><div><span>Balance</span><strong>KES 0</strong></div><div><span>Lease ends</span><strong>30 Jun 2027</strong></div><div><span>Last payment</span><strong>08 Sep · M-Pesa</strong></div></div><div className="tenant-timeline"><span>08 Sep</span><p>Payment received and allocated automatically.</p><span>06 Sep</span><p>Rent reminder delivered via WhatsApp.</p><span>24 Aug</span><p>Maintenance request WO-2183 closed.</p></div></div><div className="tenant-side-metrics"><MetricCard label="Active tenants" value="681" note="Across 742 units" icon={Users}/><MetricCard label="Good standing" value="637" note="93.5% of active tenants" icon={CheckCircle2} tone="success"/><MetricCard label="Outstanding" value="KES 1.86M" note="24 tenants with balances" icon={CircleDollarSign} tone="danger"/></div></div><Panel title="Tenant CRM" kicker="Resident portfolio"><DataTable headers={['Tenant','Unit','Phone','Monthly rent','Balance','Status']} rows={tenants.map(t=>[...t.slice(0,5),<Status value={t[5]}/>])} onRowClick={()=>onNavigate?.('Tenant 360')}/></Panel></>;
}

export function LeasingPage({onAdd,onNavigate}:{onAdd:()=>void;onNavigate?:Navigate}){
  const stages=[['Inquiry',23,'New prospects'],['Viewing',14,'Scheduled tours'],['Application',9,'Documents received'],['Screening',6,'Checks running'],['Approved',5,'Awaiting deposit'],['Signing',3,'Lease documents']];
  return <><ModuleHeader page="Leasing" onAdd={onAdd}/><div className="leasing-overview"><div><span>LEASING VELOCITY</span><strong>60 active opportunities</strong><p>Average time from inquiry to move-in is 8.4 days.</p></div><div className="leasing-conversion"><span>Conversion</span><strong>21.7%</strong><small>+3.4 pts vs August</small></div></div><div className="premium-pipeline">{stages.map((s,i)=><button className="pipeline-card interactive-card" key={s[0]} onClick={()=>onNavigate?.(i<3?'Application Workspace':'Lease Workspace')}><div className="pipeline-number">0{i+1}</div><span>{s[0]}</span><strong>{s[1]}</strong><small>{s[2]}</small><div className="pipeline-bar"><i style={{width:`${Math.max(20,100-i*13)}%`}}/></div></button>)}</div><Panel title="Active leases" kicker="Lease register"><DataTable headers={['Lease','Tenant','Unit','Start','Expiry','Rent','Status']} rows={leases.map(l=>[...l.slice(0,6),<Status value={l[6]}/>])} onRowClick={()=>onNavigate?.('Lease Workspace')}/></Panel></>;
}

export function CollectionsPage({onAdd,onNavigate}:{onAdd:()=>void;onNavigate?:Navigate}){
  return <><ModuleHeader page="Collections" onAdd={onAdd}/><div className="collections-hero"><div className="collection-rate"><span>SEPTEMBER COLLECTION RATE</span><strong>87.5%</strong><small>KES 12.96M of KES 14.82M</small><div className="collection-progress"><i/></div></div><div className="collection-breakdown"><div><span>M-Pesa</span><strong>KES 9.48M</strong><small>73.1%</small></div><div><span>Bank</span><strong>KES 2.31M</strong><small>17.8%</small></div><div><span>Other</span><strong>KES 1.17M</strong><small>9.1%</small></div><div className="collection-alert"><AlertTriangle size={17}/><span>7 unmatched</span><strong>KES 48,500</strong></div></div></div><div className="reconciliation-strip"><div><CreditCard size={17}/><span>Auto-matched today</span><strong>184 transactions</strong></div><div><Sparkles size={17}/><span>Match confidence</span><strong>99.2%</strong></div><div><CalendarClock size={17}/><span>Next reconciliation</span><strong>14:30</strong></div><SectionAction label="Open reconciliation" onClick={()=>onNavigate?.('M-Pesa Reconciliation')}/></div><Panel title="Recent transactions" kicker="Payment feed"><DataTable headers={['Reference','Tenant','Unit','Amount','Method','Time','Status']} rows={payments.map(p=>[...p.slice(0,6),<Status value={p[6]}/>])} onRowClick={()=>onNavigate?.('Payment Detail')}/></Panel></>;
}

export function AccountingPage({onAdd,onNavigate}:{onAdd:()=>void;onNavigate?:Navigate}){
 const accounts=[['Rental income','Income','KES 14,820,000','+7.2%'],['Service charge','Income','KES 1,220,000','+1.8%'],['Tenant receivables','Asset','KES 1,859,600','-4.1%'],['Tenant deposits','Liability','KES 8,940,000','+0.6%'],['Repairs & maintenance','Expense','KES 824,500','+12.4%'],['Owner payables','Liability','KES 8,420,000','+3.7%']];
 return <><ModuleHeader page="Accounting" onAdd={onAdd}/><div className="finance-scoreboard"><div><span>NET OPERATING INCOME</span><strong>KES 13.73M</strong><small>+5.8% month over month</small></div><div className="finance-scoreboard-grid"><div><span>Gross income</span><strong>KES 16.04M</strong></div><div><span>Expenses</span><strong>KES 2.31M</strong></div><div><span>Expense ratio</span><strong>14.4%</strong></div><div><span>Owner payable</span><strong>KES 8.42M</strong></div></div></div><div className="split-grid"><Panel title="Account balances" kicker="General ledger"><DataTable headers={['Account','Type','Balance','Movement']} rows={accounts} onRowClick={i=>i===3?onNavigate?.('Deposit Ledger'):undefined}/></Panel><Panel title="Month-end close" kicker="Controls"><div className="close-checklist">{['M-Pesa clearing reconciled','Bank statement matched','Vendor bills approved','Owner statements generated','Management fees posted'].map((x,i)=><div key={x}><CheckCircle2 size={17} className={i<3?'done':''}/><span>{x}</span><strong>{i<3?'Complete':'Pending'}</strong></div>)}</div><div className="close-progress"><span>Close progress</span><strong>60%</strong><i><b/></i></div></Panel></div></>;
}

export function ArrearsPage({onAdd,onNavigate}:{onAdd:()=>void;onNavigate?:Navigate}){
 return <><ModuleHeader page="Arrears" onAdd={onAdd}/><div className="arrears-hero"><div><AlertTriangle size={19}/><span>TOTAL OUTSTANDING</span><strong>KES 1.86M</strong><small>24 tenants · 18 require active follow-up</small></div><div className="arrears-focus"><span>Highest risk</span><strong>6 tenants = 61% of aged debt</strong><button onClick={()=>onNavigate?.('Collections Case')}>Build recovery plan <ArrowUpRight size={13}/></button></div></div><div className="aging-grid">{[['0–7 days','KES 420K','8 tenants'],['8–30 days','KES 680K','9 tenants'],['31–60 days','KES 315K','4 tenants'],['61–90 days','KES 194K','2 tenants'],['90+ days','KES 250K','1 tenant']].map((a,i)=><article key={a[0]} className={`aging-card a${i}`}><span>{a[0]}</span><strong>{a[1]}</strong><small>{a[2]}</small></article>)}</div><Panel title="Collection queue" kicker="Debt recovery"><DataTable headers={['Tenant','Unit','Age','Amount','Bucket','Collection stage']} rows={arrears.map(a=>[...a.slice(0,5),<Status value={a[5]}/>])} onRowClick={()=>onNavigate?.('Collections Case')}/></Panel></>;
}
