import { Router } from 'express';
import { z } from 'zod';
import { query, withTransaction } from './db.js';
import { requirePermission, type AuthedRequest } from './auth.js';

const router=Router();
function org(req:AuthedRequest){if(!req.auth?.organizationId)throw new Error('Organization context missing');return req.auth.organizationId;}
function scope(req:AuthedRequest){return req.auth?.propertyScope||[];}
function inScope(req:AuthedRequest,propertyId:string){const s=scope(req);return s.length===0||s.includes(propertyId);}
function monthKey(date:string){return date.slice(0,7).replace('-','');}
async function tenantAccess(req:AuthedRequest,tenantParam:string|string[]){
 const tenantId=Array.isArray(tenantParam)?tenantParam[0]:tenantParam;
 const result=await query<{id:string;property_id:string|null}>(`SELECT rt.id,(SELECT u.property_id FROM leases l JOIN units u ON u.id=l.unit_id WHERE l.organization_id=rt.organization_id AND l.tenant_id=rt.id AND l.status IN ('active','expiring') ORDER BY l.end_date DESC LIMIT 1) property_id FROM rental_tenants rt WHERE rt.id=$1 AND rt.organization_id=$2`,[tenantId,org(req)]);
 if(!result.rowCount)throw Object.assign(new Error('Tenant not found'),{status:404});
 const propertyId=result.rows[0].property_id;if(propertyId&&!inScope(req,propertyId))throw Object.assign(new Error('Tenant is outside your property scope'),{status:403});
 return result.rows[0];
}

router.get('/rental/rent-schedules',async(req:AuthedRequest,res)=>{
 const result=await query(`SELECT rs.*,l.lease_number,l.tenant_id,u.unit_number,p.id property_id,p.name property_name,rt.first_name||' '||rt.last_name tenant_name FROM rent_schedules rs JOIN leases l ON l.id=rs.lease_id JOIN units u ON u.id=l.unit_id JOIN properties p ON p.id=u.property_id JOIN rental_tenants rt ON rt.id=l.tenant_id WHERE rs.organization_id=$1 AND (cardinality($2::uuid[])=0 OR p.id=ANY($2::uuid[])) ORDER BY p.name,u.unit_number,rs.starts_on`,[org(req),scope(req)]);
 res.json(result.rows);
});

router.post('/rental/rent-schedules',requirePermission('lease.write'),async(req:AuthedRequest,res)=>{
 const input=z.object({leaseId:z.string().uuid(),amount:z.number().positive(),frequency:z.enum(['monthly','quarterly','annual']).default('monthly'),dueDay:z.number().int().min(1).max(28).optional(),startsOn:z.string(),endsOn:z.string().optional(),escalationType:z.enum(['fixed','percent','cpi']).optional(),escalationValue:z.number().nonnegative().optional(),nextEscalationOn:z.string().optional(),graceDays:z.number().int().min(0).max(60).default(0),prorationMethod:z.enum(['daily','thirty_day','none']).default('daily')}).safeParse(req.body);
 if(!input.success)return res.status(400).json({error:input.error.flatten()});
 const lease=await query<{property_id:string}>(`SELECT u.property_id FROM leases l JOIN units u ON u.id=l.unit_id WHERE l.id=$1 AND l.organization_id=$2`,[input.data.leaseId,org(req)]);
 if(!lease.rowCount)return res.status(404).json({error:'Lease not found'}); if(!inScope(req,lease.rows[0].property_id))return res.status(403).json({error:'Lease is outside your property scope'});
 const d=input.data,result=await query(`INSERT INTO rent_schedules(organization_id,lease_id,amount,frequency,due_day,starts_on,ends_on,escalation_type,escalation_value,next_escalation_on,grace_days,proration_method) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[org(req),d.leaseId,d.amount,d.frequency,d.dueDay||null,d.startsOn,d.endsOn||null,d.escalationType||null,d.escalationValue??null,d.nextEscalationOn||null,d.graceDays,d.prorationMethod]);
 res.status(201).json(result.rows[0]);
});

async function billingCandidates(req:AuthedRequest,periodStart:string,periodEnd:string,propertyId?:string){
 if(propertyId&&!inScope(req,propertyId))throw Object.assign(new Error('Property is outside your assigned scope'),{status:403});
 const propertyFilter=propertyId?[propertyId]:scope(req);
 const result=await query(`SELECT l.id lease_id,l.lease_number,l.tenant_id,l.monthly_rent,l.due_day,l.start_date,l.end_date,u.unit_number,p.id property_id,p.name property_name,rt.first_name||' '||rt.last_name tenant_name,coalesce(rs.amount,l.monthly_rent) scheduled_amount,coalesce(rs.due_day,l.due_day) scheduled_due_day,coalesce(rs.grace_days,l.grace_days) grace_days FROM leases l JOIN units u ON u.id=l.unit_id JOIN properties p ON p.id=u.property_id JOIN rental_tenants rt ON rt.id=l.tenant_id LEFT JOIN LATERAL (SELECT * FROM rent_schedules x WHERE x.lease_id=l.id AND x.organization_id=l.organization_id AND x.active=true AND x.starts_on<=$3::date AND (x.ends_on IS NULL OR x.ends_on>=$2::date) ORDER BY x.starts_on DESC LIMIT 1) rs ON true WHERE l.organization_id=$1 AND l.status IN ('active','expiring') AND l.start_date<=$3::date AND l.end_date>=$2::date AND (cardinality($4::uuid[])=0 OR p.id=ANY($4::uuid[])) ORDER BY p.name,u.unit_number`,[org(req),periodStart,periodEnd,propertyFilter]);
 return result.rows;
}

router.post('/rental/billing/preview',requirePermission('finance.read'),async(req:AuthedRequest,res)=>{
 const input=z.object({periodStart:z.string(),periodEnd:z.string(),propertyId:z.string().uuid().optional()}).safeParse(req.body); if(!input.success)return res.status(400).json({error:input.error.flatten()});
 const rows=await billingCandidates(req,input.data.periodStart,input.data.periodEnd,input.data.propertyId); const total=rows.reduce((sum:any,r:any)=>sum+Number(r.scheduled_amount),0);
 res.json({periodStart:input.data.periodStart,periodEnd:input.data.periodEnd,count:rows.length,total,items:rows});
});

router.post('/rental/billing/post',requirePermission('finance.write'),async(req:AuthedRequest,res)=>{
 const input=z.object({periodStart:z.string(),periodEnd:z.string(),propertyId:z.string().uuid().optional(),runKey:z.string().min(8).max(120)}).safeParse(req.body); if(!input.success)return res.status(400).json({error:input.error.flatten()});
 const d=input.data,existing=await query(`SELECT * FROM billing_runs WHERE organization_id=$1 AND run_key=$2`,[org(req),d.runKey]); if(existing.rowCount)return res.json({...existing.rows[0],idempotentReplay:true});
 const candidates=await billingCandidates(req,d.periodStart,d.periodEnd,d.propertyId);
 const result=await withTransaction(async client=>{
  const run=await client.query(`INSERT INTO billing_runs(organization_id,run_key,period_start,period_end,property_id,status,created_by) VALUES($1,$2,$3,$4,$5,'previewed',$6) RETURNING *`,[org(req),d.runKey,d.periodStart,d.periodEnd,d.propertyId||null,req.auth!.userId]);
  let count=0,total=0;
  for(const row of candidates as any[]){
   const amount=Number(row.scheduled_amount); const dueDay=Math.max(1,Math.min(28,Number(row.scheduled_due_day||5))); const dueDate=`${d.periodStart.slice(0,7)}-${String(dueDay).padStart(2,'0')}`; const number=`RNT-${monthKey(d.periodStart)}-${String(row.lease_number).replace(/[^A-Za-z0-9]/g,'').slice(-12)}`;
   const invoice=await client.query(`INSERT INTO invoices(organization_id,tenant_id,lease_id,invoice_number,period_start,period_end,due_date,subtotal,total,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8,'issued') ON CONFLICT DO NOTHING RETURNING id`,[org(req),row.tenant_id,row.lease_id,number,d.periodStart,d.periodEnd,dueDate,amount]);
   if(invoice.rowCount){await client.query(`INSERT INTO invoice_items(organization_id,invoice_id,item_type,description,quantity,unit_price,total) VALUES($1,$2,'rent',$3,1,$4,$4)`,[org(req),invoice.rows[0].id,`Rent · ${row.property_name} ${row.unit_number}`,amount]);count+=1;total+=amount;}
  }
  await client.query(`UPDATE billing_runs SET status='posted',invoice_count=$1,total_amount=$2,posted_at=now(),metadata=$3::jsonb WHERE id=$4`,[count,total,JSON.stringify({candidateCount:candidates.length,skipped:candidates.length-count}),run.rows[0].id]);
  await client.query(`INSERT INTO audit_logs(organization_id,user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'billing.run.post','billing_run',$3,$4::jsonb)`,[org(req),req.auth!.userId,run.rows[0].id,JSON.stringify({periodStart:d.periodStart,periodEnd:d.periodEnd,count,total})]);
  return {...run.rows[0],status:'posted',invoice_count:count,total_amount:total,posted_at:new Date().toISOString(),skipped:candidates.length-count};
 });
 res.status(201).json(result);
});
router.get('/rental/billing/runs',requirePermission('finance.read'),async(req:AuthedRequest,res)=>{const r=await query(`SELECT br.*,p.name property_name FROM billing_runs br LEFT JOIN properties p ON p.id=br.property_id WHERE br.organization_id=$1 ORDER BY br.created_at DESC LIMIT 100`,[org(req)]);res.json(r.rows)});

router.get('/rental/tenant/:tenantId/lifecycle',async(req:AuthedRequest,res)=>{
 await tenantAccess(req,req.params.tenantId);
 const tenantId=req.params.tenantId,o=org(req);
 const [tenant,contacts,kyc,leases,wallet,plans,maintenance,documents]=await Promise.all([
  query(`SELECT rt.*,l.id lease_id,l.lease_number,l.start_date,l.end_date,l.monthly_rent,l.deposit_amount,l.status lease_status,u.unit_number,p.id property_id,p.name property_name FROM rental_tenants rt LEFT JOIN LATERAL (SELECT * FROM leases x WHERE x.organization_id=rt.organization_id AND x.tenant_id=rt.id ORDER BY CASE WHEN x.status IN ('active','expiring') THEN 0 ELSE 1 END,x.end_date DESC LIMIT 1) l ON true LEFT JOIN units u ON u.id=l.unit_id LEFT JOIN properties p ON p.id=u.property_id WHERE rt.organization_id=$1 AND rt.id=$2`,[o,tenantId]),
  query(`SELECT * FROM tenant_contacts WHERE organization_id=$1 AND tenant_id=$2 ORDER BY is_primary DESC,created_at`,[o,tenantId]),
  query(`SELECT * FROM tenant_kyc WHERE organization_id=$1 AND tenant_id=$2 ORDER BY created_at DESC`,[o,tenantId]),
  query(`SELECT l.*,u.unit_number,p.name property_name,(SELECT json_agg(lp ORDER BY lp.party_type,lp.name) FROM lease_parties lp WHERE lp.organization_id=l.organization_id AND lp.lease_id=l.id) parties,(SELECT json_agg(la ORDER BY la.version DESC) FROM lease_amendments la WHERE la.organization_id=l.organization_id AND la.lease_id=l.id) amendments FROM leases l JOIN units u ON u.id=l.unit_id JOIN properties p ON p.id=u.property_id WHERE l.organization_id=$1 AND l.tenant_id=$2 ORDER BY l.end_date DESC`,[o,tenantId]),
  query(`SELECT * FROM tenant_wallet_entries WHERE organization_id=$1 AND tenant_id=$2 ORDER BY posted_at DESC LIMIT 100`,[o,tenantId]),
  query(`SELECT * FROM payment_plans WHERE organization_id=$1 AND tenant_id=$2 ORDER BY created_at DESC`,[o,tenantId]),
  query(`SELECT mr.*,p.name property_name,u.unit_number FROM maintenance_requests mr JOIN properties p ON p.id=mr.property_id LEFT JOIN units u ON u.id=mr.unit_id WHERE mr.organization_id=$1 AND mr.tenant_id=$2 ORDER BY mr.created_at DESC LIMIT 50`,[o,tenantId]),
  query(`SELECT d.* FROM documents d WHERE d.organization_id=$1 AND ((d.entity_type='tenant' AND d.entity_id=$2) OR (d.entity_type='lease' AND d.entity_id IN (SELECT id FROM leases WHERE organization_id=$1 AND tenant_id=$2))) ORDER BY d.created_at DESC LIMIT 50`,[o,tenantId])
 ]);
 const walletBalance=wallet.rows.reduce((sum:any,e:any)=>sum+(e.entry_type==='debit'?-Number(e.amount):Number(e.amount)),0);
 res.json({tenant:tenant.rows[0],contacts:contacts.rows,kyc:kyc.rows,leases:leases.rows,wallet:{balance:walletBalance,entries:wallet.rows},paymentPlans:plans.rows,maintenance:maintenance.rows,documents:documents.rows});
});

router.get('/rental/tenant/:tenantId/contacts',async(req:AuthedRequest,res)=>{await tenantAccess(req,req.params.tenantId);const r=await query(`SELECT * FROM tenant_contacts WHERE organization_id=$1 AND tenant_id=$2 ORDER BY is_primary DESC,created_at`,[org(req),req.params.tenantId]);res.json(r.rows)});
router.post('/rental/tenant/:tenantId/contacts',requirePermission('tenant.write'),async(req:AuthedRequest,res)=>{await tenantAccess(req,req.params.tenantId);const input=z.object({contactType:z.enum(['emergency','next_of_kin','employer','reference','household','other']),name:z.string().min(2),phone:z.string().optional(),email:z.string().email().optional(),relationship:z.string().optional(),isPrimary:z.boolean().default(false)}).safeParse(req.body);if(!input.success)return res.status(400).json({error:input.error.flatten()});const d=input.data,r=await query(`INSERT INTO tenant_contacts(organization_id,tenant_id,contact_type,name,phone,email,relationship,is_primary) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[org(req),req.params.tenantId,d.contactType,d.name,d.phone||null,d.email||null,d.relationship||null,d.isPrimary]);res.status(201).json(r.rows[0])});

router.get('/rental/tenant/:tenantId/kyc',async(req:AuthedRequest,res)=>{await tenantAccess(req,req.params.tenantId);const r=await query(`SELECT * FROM tenant_kyc WHERE organization_id=$1 AND tenant_id=$2 ORDER BY created_at DESC`,[org(req),req.params.tenantId]);res.json(r.rows)});
router.post('/rental/tenant/:tenantId/kyc',requirePermission('tenant.write'),async(req:AuthedRequest,res)=>{await tenantAccess(req,req.params.tenantId);const input=z.object({documentType:z.string().optional(),documentNumber:z.string().optional(),employer:z.string().optional(),status:z.enum(['pending','verified','rejected']).default('pending'),metadata:z.record(z.string(),z.any()).default({})}).safeParse(req.body);if(!input.success)return res.status(400).json({error:input.error.flatten()});const d=input.data,r=await query(`INSERT INTO tenant_kyc(organization_id,tenant_id,document_type,document_number,employer,status,verified_at,metadata) VALUES($1,$2,$3,$4,$5,$6,CASE WHEN $6='verified' THEN now() END,$7::jsonb) RETURNING *`,[org(req),req.params.tenantId,d.documentType||null,d.documentNumber||null,d.employer||null,d.status,JSON.stringify(d.metadata)]);res.status(201).json(r.rows[0])});

router.get('/rental/tenant/:tenantId/wallet',requirePermission('finance.read'),async(req:AuthedRequest,res)=>{await tenantAccess(req,req.params.tenantId);const r=await query(`SELECT * FROM tenant_wallet_entries WHERE organization_id=$1 AND tenant_id=$2 ORDER BY posted_at DESC LIMIT 200`,[org(req),req.params.tenantId]);const balance=r.rows.reduce((sum:any,e:any)=>sum+(e.entry_type==='debit'?-Number(e.amount):Number(e.amount)),0);res.json({balance,entries:r.rows})});
router.post('/rental/tenant/:tenantId/wallet',requirePermission('finance.write'),async(req:AuthedRequest,res)=>{await tenantAccess(req,req.params.tenantId);const input=z.object({entryType:z.enum(['credit','debit']),amount:z.number().positive(),reference:z.string().min(2),sourceType:z.string().optional(),sourceId:z.string().uuid().optional(),metadata:z.record(z.string(),z.any()).default({})}).safeParse(req.body);if(!input.success)return res.status(400).json({error:input.error.flatten()});const d=input.data,r=await query(`INSERT INTO tenant_wallet_entries(organization_id,tenant_id,entry_type,amount,reference,source_type,source_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb) RETURNING *`,[org(req),req.params.tenantId,d.entryType,d.amount,d.reference,d.sourceType||null,d.sourceId||null,JSON.stringify(d.metadata)]);res.status(201).json(r.rows[0])});

router.get('/rental/tenant/:tenantId/payment-plans',requirePermission('finance.read'),async(req:AuthedRequest,res)=>{await tenantAccess(req,req.params.tenantId);const r=await query(`SELECT * FROM payment_plans WHERE organization_id=$1 AND tenant_id=$2 ORDER BY created_at DESC`,[org(req),req.params.tenantId]);res.json(r.rows)});
router.post('/rental/tenant/:tenantId/payment-plans',requirePermission('finance.write'),async(req:AuthedRequest,res)=>{await tenantAccess(req,req.params.tenantId);const input=z.object({leaseId:z.string().uuid().optional(),originalBalance:z.number().positive(),installmentAmount:z.number().positive(),frequency:z.enum(['weekly','biweekly','monthly']).default('monthly'),startsOn:z.string(),nextDueOn:z.string().optional()}).safeParse(req.body);if(!input.success)return res.status(400).json({error:input.error.flatten()});const d=input.data,r=await query(`INSERT INTO payment_plans(organization_id,tenant_id,lease_id,original_balance,installment_amount,frequency,starts_on,next_due_on,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[org(req),req.params.tenantId,d.leaseId||null,d.originalBalance,d.installmentAmount,d.frequency,d.startsOn,d.nextDueOn||d.startsOn,req.auth!.userId]);res.status(201).json(r.rows[0])});

router.get('/rental/lease/:leaseId/parties',async(req:AuthedRequest,res)=>{const lease=await query<{tenant_id:string;property_id:string}>(`SELECT l.tenant_id,u.property_id FROM leases l JOIN units u ON u.id=l.unit_id WHERE l.id=$1 AND l.organization_id=$2`,[req.params.leaseId,org(req)]);if(!lease.rowCount)return res.status(404).json({error:'Lease not found'});if(!inScope(req,lease.rows[0].property_id))return res.status(403).json({error:'Lease is outside your property scope'});const r=await query(`SELECT * FROM lease_parties WHERE organization_id=$1 AND lease_id=$2 ORDER BY party_type,name`,[org(req),req.params.leaseId]);res.json(r.rows)});
router.post('/rental/lease/:leaseId/parties',requirePermission('lease.write'),async(req:AuthedRequest,res)=>{const lease=await query<{property_id:string}>(`SELECT u.property_id FROM leases l JOIN units u ON u.id=l.unit_id WHERE l.id=$1 AND l.organization_id=$2`,[req.params.leaseId,org(req)]);if(!lease.rowCount)return res.status(404).json({error:'Lease not found'});if(!inScope(req,lease.rows[0].property_id))return res.status(403).json({error:'Lease is outside your property scope'});const input=z.object({tenantId:z.string().uuid().optional(),partyType:z.enum(['co_tenant','guarantor','occupant']),name:z.string().min(2),phone:z.string().optional(),email:z.string().email().optional(),liabilityPercent:z.number().min(0).max(100).optional(),guaranteeAmount:z.number().nonnegative().optional(),startDate:z.string().optional(),endDate:z.string().optional(),metadata:z.record(z.string(),z.any()).default({})}).safeParse(req.body);if(!input.success)return res.status(400).json({error:input.error.flatten()});const d=input.data,r=await query(`INSERT INTO lease_parties(organization_id,lease_id,tenant_id,party_type,name,phone,email,liability_percent,guarantee_amount,start_date,end_date,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) RETURNING *`,[org(req),req.params.leaseId,d.tenantId||null,d.partyType,d.name,d.phone||null,d.email||null,d.liabilityPercent??null,d.guaranteeAmount??null,d.startDate||null,d.endDate||null,JSON.stringify(d.metadata)]);res.status(201).json(r.rows[0])});

router.get('/rental/lease/:leaseId/amendments',async(req:AuthedRequest,res)=>{const lease=await query<{property_id:string}>(`SELECT u.property_id FROM leases l JOIN units u ON u.id=l.unit_id WHERE l.id=$1 AND l.organization_id=$2`,[req.params.leaseId,org(req)]);if(!lease.rowCount)return res.status(404).json({error:'Lease not found'});if(!inScope(req,lease.rows[0].property_id))return res.status(403).json({error:'Lease is outside your property scope'});const r=await query(`SELECT * FROM lease_amendments WHERE organization_id=$1 AND lease_id=$2 ORDER BY version DESC`,[org(req),req.params.leaseId]);res.json(r.rows)});
router.post('/rental/lease/:leaseId/amendments',requirePermission('lease.write'),async(req:AuthedRequest,res)=>{const lease=await query<{property_id:string}>(`SELECT u.property_id FROM leases l JOIN units u ON u.id=l.unit_id WHERE l.id=$1 AND l.organization_id=$2`,[req.params.leaseId,org(req)]);if(!lease.rowCount)return res.status(404).json({error:'Lease not found'});if(!inScope(req,lease.rows[0].property_id))return res.status(403).json({error:'Lease is outside your property scope'});const input=z.object({amendmentType:z.string().min(2),effectiveOn:z.string(),summary:z.string().min(3),terms:z.record(z.string(),z.any()).default({}),status:z.enum(['draft','pending_signature','executed','cancelled']).default('draft')}).safeParse(req.body);if(!input.success)return res.status(400).json({error:input.error.flatten()});const version=await query<{next:number}>(`SELECT coalesce(max(version),0)+1 next FROM lease_amendments WHERE organization_id=$1 AND lease_id=$2`,[org(req),req.params.leaseId]);const d=input.data,r=await query(`INSERT INTO lease_amendments(organization_id,lease_id,version,amendment_type,effective_on,summary,terms,status,signed_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,CASE WHEN $8='executed' THEN now() END,$9) RETURNING *`,[org(req),req.params.leaseId,version.rows[0].next,d.amendmentType,d.effectiveOn,d.summary,JSON.stringify(d.terms),d.status,req.auth!.userId]);res.status(201).json(r.rows[0])});

router.get('/rental/turnovers',async(req:AuthedRequest,res)=>{const r=await query(`SELECT vt.*,u.unit_number,p.name property_name,p.id property_id FROM vacancy_turnovers vt JOIN units u ON u.id=vt.unit_id JOIN properties p ON p.id=u.property_id WHERE vt.organization_id=$1 AND (cardinality($2::uuid[])=0 OR p.id=ANY($2::uuid[])) ORDER BY coalesce(vt.target_ready_on,current_date),p.name,u.unit_number`,[org(req),scope(req)]);res.json(r.rows)});

export default router;
