import { FormEvent, useMemo, useState } from 'react';
import { Bell, Building2, ChevronDown, ChevronRight, CircleDollarSign, ClipboardCheck, FileBarChart, Gauge, Inbox, KeyRound, Landmark, Layers3, Menu, Moon, Plus, ReceiptText, Search, Settings, Sparkles, Sun, UserRoundCog, Users, WalletCards, Wrench, X, Zap } from 'lucide-react';
import { properties, tenants, units } from './data';
import { pageMeta } from './ui';
import { OverviewPage } from './pages/dashboard';
import { AccountingPage, ArrearsPage, CollectionsPage, LeasingPage, OwnersPage, PropertiesPage, TenantsPage, UnitsPage } from './pages/portfolio';
import { AIAssistantPage, InboxPage, InspectionsPage, MaintenancePage, ReportsPage, SettingsPage, TeamPage } from './pages/operations';

const navigation = [
  {label:'Overview',icon:Gauge},{heading:'Portfolio'},{label:'Properties',icon:Building2},{label:'Units',icon:Layers3},{label:'Owners',icon:Landmark},{label:'Tenants',icon:Users},{label:'Leasing',icon:KeyRound},{heading:'Finance'},{label:'Collections',icon:WalletCards},{label:'Accounting',icon:ReceiptText},{label:'Arrears',icon:CircleDollarSign,badge:18},{heading:'Operations'},{label:'Maintenance',icon:Wrench,badge:7},{label:'Inspections',icon:ClipboardCheck},{label:'Inbox',icon:Inbox,badge:4},{heading:'Intelligence'},{label:'Reports',icon:FileBarChart},{label:'AI Assistant',icon:Sparkles,accent:true}
] as const;

function AddModal({page,onClose}:{page:string;onClose:()=>void}){
  const [saved,setSaved]=useState(false);
  function submit(e:FormEvent){e.preventDefault();setSaved(true);setTimeout(onClose,700)}
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><span className="panel-kicker">Quick create</span><h2>{pageMeta[page]?.action || 'Add record'}</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={17}/></button></div>{saved?<div className="success-state"><strong>Saved successfully</strong><span>The record has been added to this workspace.</span></div>:<><div className="form-grid"><label><span>Name / reference</span><input required placeholder="Enter name"/></label><label><span>Property</span><select><option>Greenview Apartments</option><option>Riverside Heights</option><option>Parkline Residences</option></select></label><label><span>Phone / contact</span><input placeholder="07…"/></label><label><span>Amount / rent</span><input placeholder="KES"/></label><label className="full"><span>Notes</span><textarea rows={4} placeholder="Add details…"/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" className="primary-button">Save record</button></div></>}</form></div>;
}

export default function App(){
  const [dark,setDark]=useState(false), [mobileOpen,setMobileOpen]=useState(false), [page,setPage]=useState('Overview'), [addOpen,setAddOpen]=useState(false), [globalSearch,setGlobalSearch]=useState('');
  const searchResults=useMemo(()=>{if(!globalSearch.trim())return [];const q=globalSearch.toLowerCase();return [...properties.map(p=>({type:'Property',name:p.name,meta:p.location})),...tenants.map(t=>({type:'Tenant',name:t[0],meta:t[1]})),...units.map(u=>({type:'Unit',name:u.unit,meta:u.property}))].filter(x=>(x.name+' '+x.meta).toLowerCase().includes(q)).slice(0,6)},[globalSearch]);
  const onAdd=()=>setAddOpen(true);
  function content(){switch(page){case'Properties':return <PropertiesPage onAdd={onAdd}/>;case'Units':return <UnitsPage onAdd={onAdd}/>;case'Owners':return <OwnersPage onAdd={onAdd}/>;case'Tenants':return <TenantsPage onAdd={onAdd}/>;case'Leasing':return <LeasingPage onAdd={onAdd}/>;case'Collections':return <CollectionsPage onAdd={onAdd}/>;case'Accounting':return <AccountingPage onAdd={onAdd}/>;case'Arrears':return <ArrearsPage onAdd={onAdd}/>;case'Maintenance':return <MaintenancePage onAdd={onAdd}/>;case'Inspections':return <InspectionsPage onAdd={onAdd}/>;case'Inbox':return <InboxPage onAdd={onAdd}/>;case'Reports':return <ReportsPage onAdd={onAdd}/>;case'AI Assistant':return <AIAssistantPage/>;case'Team & roles':return <TeamPage/>;case'Settings':return <SettingsPage/>;default:return <OverviewPage/>}}
  return <div className={dark?'app dark':'app'}>
    <aside className={mobileOpen?'sidebar open':'sidebar'}><div className="brand-row"><div className="brand-mark"><Building2 size={20}/></div><div><strong>Polyizon</strong><span>PropOS</span></div><button className="icon-button mobile-close" onClick={()=>setMobileOpen(false)}><X size={18}/></button></div><button className="workspace-card"><div className="workspace-avatar">AP</div><div className="workspace-copy"><strong>Alpha Properties</strong><span>Business workspace · 742 units</span></div><ChevronDown size={16}/></button><nav>{navigation.map((item:any,i)=>item.heading?<div className="nav-heading" key={i}>{item.heading}</div>:<button key={item.label} onClick={()=>{setPage(item.label);setMobileOpen(false)}} className={`nav-item ${page===item.label?'active':''} ${item.accent?'ai':''}`}>{item.icon&&<item.icon size={18}/>}<span>{item.label}</span>{item.badge&&<em>{item.badge}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="plan-card"><div className="plan-icon"><Zap size={16}/></div><div><strong>Business plan</strong><span>742 / 1,000 units</span></div><ChevronRight size={16}/></div><button onClick={()=>setPage('Team & roles')} className={`nav-item ${page==='Team & roles'?'active':''}`}><UserRoundCog size={18}/><span>Team & roles</span></button><button onClick={()=>setPage('Settings')} className={`nav-item ${page==='Settings'?'active':''}`}><Settings size={18}/><span>Settings</span></button></div></aside>
    <main className="main"><header className="topbar"><div className="left-tools"><button className="icon-button menu" onClick={()=>setMobileOpen(true)}><Menu size={20}/></button><div className="global-search"><Search size={18}/><input value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)} placeholder="Search properties, tenants, units, payments..."/><kbd>⌘ K</kbd>{searchResults.length>0&&<div className="search-results">{searchResults.map((r,i)=><button key={i} onClick={()=>{setGlobalSearch('');setPage(r.type==='Property'?'Properties':r.type==='Tenant'?'Tenants':'Units')}}><span>{r.type}</span><strong>{r.name}</strong><small>{r.meta}</small></button>)}</div>}</div></div><div className="top-actions"><button className="icon-button" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button notify"><Bell size={18}/><i/></button><button className="add-button" onClick={onAdd}><Plus size={17}/> Add new</button><div className="profile"><div className="profile-avatar">AN</div><div><strong>Alex</strong><span>Company Admin</span></div><ChevronDown size={14}/></div></div></header><section className="content">{content()}</section></main>
    {mobileOpen&&<button className="scrim" onClick={()=>setMobileOpen(false)}/>} {addOpen&&<AddModal page={page} onClose={()=>setAddOpen(false)}/>} 
  </div>;
}
